(module gl-unsafe mzscheme
  (require "gl-wrapper-helper.ss")
  (provide (all-defined))
  
  (r glEdgeFlagPointer)
  (r glTexCoordPointer)
  (r glColorPointer)
  (r glIndexPointer)
  (r glNormalPointer)
  (r glVertexPointer)
  (r glArrayElement)
  (r glDrawArrays)
  (r glDrawElements)
  (r glInterleavedArrays)
  (r glGetBooleanv)
  (r glGetDoublev)
  (r glGetFloatv)
  (r glGetIntegerv)
  (r glGetMapdv)
  (r glGetMapfv)
  (r glGetMapiv)
  (r glGetPixelMapfv)
  (r glGetPixelMapuiv)
  (r glGetPixelMapusv)
  (r glGetPointerv)
  (r glGetTexEnvfv)
  (r glGetTexEnviv)
  (r glGetTexGenfv)
  (r glGetTexGeniv)
  (r glGetTexImage)
  (r glGetTexLevelParameterfv)
  (r glGetTexLevelParameteriv)
  (r glGetTexParameterfv)
  (r glGetTexParameteriv)
  
  (r12f glDrawRangeElements)
  (r12f glGetColorTable)
  (r12f glGetConvolutionFilter)
  (r12f glGetHistogram)
  (r12f glGetMinmax)
  (r12f glGetSeparableFilter)
  
  (r13f glCompressedTexImage1D)
  (r13f glCompressedTexImage2D)
  (r13f glCompressedTexImage3D)
  (r13f glCompressedTexSubImage1D)
  (r13f glCompressedTexSubImage2D)
  (r13f glCompressedTexSubImage3D)
  (r13f glGetCompressedTexImage)
  )