(module gl-unsafe mzscheme
  (require "gl-wrapper-helper.ss")
  (provide (all-defined))

  (define p '(lib "gl-prims-unsafe.ss" "sgl"))
  
  (r p glEdgeFlagPointer)
  (r p glTexCoordPointer)
  (r p glColorPointer)
  (r p glIndexPointer)
  (r p glNormalPointer)
  (r p glVertexPointer)
  (r p glArrayElement)
  (r p glDrawArrays)
  (r p glDrawElements)
  (r p glInterleavedArrays)
  (r p glGetBooleanv)
  (r p glGetDoublev)
  (r p glGetFloatv)
  (r p glGetIntegerv)
  (r p glGetMapdv)
  (r p glGetMapfv)
  (r p glGetMapiv)
  (r p glGetPixelMapfv)
  (r p glGetPixelMapuiv)
  (r p glGetPixelMapusv)
  (r p glGetPointerv)
  (r p glGetTexEnvfv)
  (r p glGetTexEnviv)
  (r p glGetTexGenfv)
  (r p glGetTexGeniv)
  (r p glGetTexImage)
  (r p glGetTexLevelParameterfv)
  (r p glGetTexLevelParameteriv)
  (r p glGetTexParameterfv)
  (r p glGetTexParameteriv)
  
  (r12f p glDrawRangeElements)
  (r12f p glGetColorTable)
  (r12f p glGetConvolutionFilter)
  (r12f p glGetHistogram)
  (r12f p glGetMinmax)
  (r12f p glGetSeparableFilter)
  
  (r13f p glCompressedTexImage1D)
  (r13f p glCompressedTexImage2D)
  (r13f p glCompressedTexImage3D)
  (r13f p glCompressedTexSubImage1D)
  (r13f p glCompressedTexSubImage2D)
  (r13f p glCompressedTexSubImage3D)
  (r13f p glGetCompressedTexImage)
  )