(require-library "cores.ss")
(require-library "userspcs.ss" "userspce")
(require-library "graphics.ss" "graphics")
(require-library "turtles.ss" "graphics")

(define-signature plt:userspace^
  ((open mzlib:pretty-print^)
   (open mzlib:file^)
   (open mzlib:function^)
   (open mzlib:compat^)
   (open mzlib:string^)
   (open ricedefs^)
   (open graphics^)
   (open turtle^)
   (open mred^)))
