(reference-library "cores.ss")
(reference-library "userspcs.ss" "userspce")
(reference-library "graphics.ss" "graphics")
(reference-library "turtles.ss" "graphics")

(define-signature plt:userspace^
  ((open mzlib:pretty-print^)
   (open mzlib:file^)
   (open mzlib:function^)
   (open mzlib:compat^)
   (open mzlib:string^)
   (open ricedefs^)
   (open graphics^)
   (open turtle^)
   (unit mred : mred^)
   (unit wx : wx^)))
