
(load-relative "utilssig.ss")

(define-signature params^
  (US-PIECE-WEIGHT
   US-MIDDLE-PIECE-WEIGHT
   US-LINE-PIECE-WEIGHT
   US-CONNECT-PIECE-WEIGHT

   THEM-PIECE-WEIGHT
   THEM-MIDDLE-PIECE-WEIGHT
   THEM-LINE-PIECE-WEIGHT
   THEM-CONNECT-PIECE-WEIGHT
   
   turn-number))
