(module info (lib "infotab.ss" "setup")
  (define name "ProfessorJ")
  (define tools (list (list "tool.ss")))
  (define compile-subcollections (list (list "profj" "parsers")
                                       ;(list "profj" "libs" "draw")
                                       (list "profj" "libs" "java" "lang")
				       (list "profj" "libs" "java" "io"))))
