
(require-library "zmath.ss")
(require-library "constant.ss")

(constant mzlib:zmath^)
(constant mzlib:zmath@)

(constant zsqrt)
(constant e)
(constant pi)
(constant make-complex)
(constant zabs)
(constant sgn)
(constant conjugate)
(constant zsin)
(constant ztan)
(constant zcos)
(constant cosh)
(constant sinh)
(constant zexp)
(constant zlog)
(constant zatan)
(constant zacos)
(constant zasin)
