

; Test info extracted from the documentation

(hash-table-put! classinfo bitmap%
 (list bitmap%-example-list 'bitmap%
  (list
     (list  [unknown "list of chars"] integer-example-list integer-example-list)
     (list  integer-example-list integer-example-list integer-example-list)
     (list  integer-example-list integer-example-list)
     (list  string-example-list symbol-example-list)
     (list  string-example-list))
  (list 'get-depth  integer-example-list)
  (list 'get-height  integer-example-list)
  (list 'get-width  integer-example-list)
  (list 'load-file  boolean-example-list string-example-list symbol-example-list)
  (list 'load-file  boolean-example-list string-example-list)
  (list 'ok?  boolean-example-list)
  (list 'save-file  boolean-example-list string-example-list integer-example-list)))

(hash-table-put! classinfo brush%
 (list brush%-example-list 'brush%
  (list
     (list )
     (list  color%-example-list integer-example-list)
     (list  string-example-list integer-example-list))
  (list 'get-color  color%-example-list)
  (list 'get-stipple  (optional #f bitmap%-example-list))
  (list 'get-style  integer-example-list)
  (list 'set-color  void-example-list color%-example-list)
  (list 'set-color  void-example-list string-example-list)
  (list 'set-color  void-example-list integer-example-list integer-example-list integer-example-list)
  (list 'set-stipple  void-example-list (optional #f bitmap%-example-list))
  (list 'set-style  void-example-list integer-example-list)))

(hash-table-put! classinfo brush-list%
 (list brush-list%-example-list 'brush-list%
  (list
     (list ))
  (list 'find-or-create-brush  brush%-example-list color%-example-list integer-example-list)
  (list 'find-or-create-brush  (optional #f brush%-example-list) string-example-list integer-example-list)))

(hash-table-put! classinfo canvas-dc%
 (list canvas-dc%-example-list 'canvas-dc%
  (list)
  (list 'begin-drawing  void-example-list)
  (list 'begin-set-pixel  void-example-list)
  (list 'blit  boolean-example-list real-example-list real-example-list real-example-list real-example-list canvas-dc%-example-list real-example-list real-example-list integer-example-list)
  (list 'blit  boolean-example-list real-example-list real-example-list real-example-list real-example-list canvas-dc%-example-list real-example-list real-example-list)
  (list 'clear  void-example-list)
  (list 'destroy-clipping-region  void-example-list)
  (list 'draw-arc  void-example-list real-example-list real-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-ellipse  void-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-icon  void-example-list icon%-example-list real-example-list real-example-list)
  (list 'draw-line  void-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-lines  void-example-list [unknown "list of \\iscmclass{point} objects"] real-example-list real-example-list)
  (list 'draw-lines  void-example-list [unknown "list of \\iscmclass{point} objects"] real-example-list)
  (list 'draw-lines  void-example-list [unknown "list of \\iscmclass{point} objects"])
  (list 'draw-point  void-example-list real-example-list real-example-list)
  (list 'draw-polygon  void-example-list [unknown "list of \\iscmclass{point} objects"] real-example-list real-example-list symbol-example-list)
  (list 'draw-polygon  void-example-list [unknown "list of \\iscmclass{point} objects"] real-example-list real-example-list)
  (list 'draw-polygon  void-example-list [unknown "list of \\iscmclass{point} objects"] real-example-list)
  (list 'draw-polygon  void-example-list [unknown "list of \\iscmclass{point} objects"])
  (list 'draw-rectangle  void-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-rounded-rectangle  void-example-list real-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-rounded-rectangle  void-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-spline  void-example-list real-example-list real-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-text  void-example-list string-example-list real-example-list real-example-list)
  (list 'end-doc  void-example-list)
  (list 'end-drawing  void-example-list)
  (list 'end-page  void-example-list)
  (list 'end-set-pixel  void-example-list)
  (list 'get-background  brush%-example-list)
  (list 'get-background-mode  symbol-example-list)
  (list 'get-brush  brush%-example-list)
  (list 'get-char-height  real-example-list)
  (list 'get-char-width  real-example-list)
  (list 'get-clipping-region  void-example-list (boxed real-example-list) (boxed real-example-list) (boxed real-example-list) (boxed real-example-list))
  (list 'get-font  font%-example-list)
  (list 'get-logical-function  integer-example-list)
  (list 'get-pen  pen%-example-list)
  (list 'get-pixel  boolean-example-list real-example-list real-example-list color%-example-list)
  (list 'get-size  void-example-list (boxed real-example-list) (boxed real-example-list))
  (list 'get-text-background  color%-example-list)
  (list 'get-text-extent  void-example-list string-example-list (boxed real-example-list) (boxed real-example-list) (optional #f (boxed real-example-list)) (optional #f (boxed real-example-list)) (optional #f font%-example-list))
  (list 'get-text-extent  void-example-list string-example-list (boxed real-example-list) (boxed real-example-list) (optional #f (boxed real-example-list)) (optional #f (boxed real-example-list)))
  (list 'get-text-extent  void-example-list string-example-list (boxed real-example-list) (boxed real-example-list) (optional #f (boxed real-example-list)))
  (list 'get-text-extent  void-example-list string-example-list (boxed real-example-list) (boxed real-example-list))
  (list 'get-text-foreground  color%-example-list)
  (list 'ok?  boolean-example-list)
  (list 'set-background  void-example-list brush%-example-list)
  (list 'set-background-mode  void-example-list symbol-example-list)
  (list 'set-brush  void-example-list brush%-example-list)
  (list 'set-clipping-region  void-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'set-device-origin  void-example-list real-example-list real-example-list)
  (list 'set-font  void-example-list font%-example-list)
  (list 'set-logical-function  void-example-list integer-example-list)
  (list 'set-pen  void-example-list pen%-example-list)
  (list 'set-pixel  void-example-list real-example-list real-example-list color%-example-list)
  (list 'set-text-background  void-example-list color%-example-list)
  (list 'set-text-foreground  void-example-list color%-example-list)
  (list 'set-user-scale  void-example-list real-example-list real-example-list)
  (list 'start-doc  boolean-example-list string-example-list)
  (list 'start-page  boolean-example-list)
  (list 'try-color  void-example-list color%-example-list color%-example-list)))

(hash-table-put! classinfo color%
 (list color%-example-list 'color%
  (list
     (list  0-to-255-example-list 0-to-255-example-list 0-to-255-example-list)
     (list  string-example-list))
  (list '=  color%-example-list color%-example-list)
  (list 'blue  0-to-255-example-list)
  (list 'green  0-to-255-example-list)
  (list 'ok?  boolean-example-list)
  (list 'red  0-to-255-example-list)
  (list 'set  void-example-list 0-to-255-example-list 0-to-255-example-list 0-to-255-example-list)))

(hash-table-put! classinfo color-database%
 (list color-database%-example-list 'color-database%
  (list)
  (list 'append  void-example-list string-example-list color%-example-list)
  (list 'find-color  (optional #f color%-example-list) string-example-list)
  (list 'find-name  (optional #f string-example-list) color%-example-list)))

(hash-table-put! classinfo dc<%>
 (list dc<%>-example-list 'dc<%>
  (list)
  (list 'begin-drawing  void-example-list)
  (list 'blit  boolean-example-list real-example-list real-example-list real-example-list real-example-list canvas-dc%-example-list real-example-list real-example-list integer-example-list)
  (list 'blit  boolean-example-list real-example-list real-example-list real-example-list real-example-list canvas-dc%-example-list real-example-list real-example-list)
  (list 'clear  void-example-list)
  (list 'destroy-clipping-region  void-example-list)
  (list 'draw-arc  void-example-list real-example-list real-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-ellipse  void-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-icon  void-example-list icon%-example-list real-example-list real-example-list)
  (list 'draw-line  void-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-lines  void-example-list [unknown "list of \\iscmclass{point} objects"] real-example-list real-example-list)
  (list 'draw-lines  void-example-list [unknown "list of \\iscmclass{point} objects"] real-example-list)
  (list 'draw-lines  void-example-list [unknown "list of \\iscmclass{point} objects"])
  (list 'draw-point  void-example-list real-example-list real-example-list)
  (list 'draw-polygon  void-example-list [unknown "list of \\iscmclass{point} objects"] real-example-list real-example-list symbol-example-list)
  (list 'draw-polygon  void-example-list [unknown "list of \\iscmclass{point} objects"] real-example-list real-example-list)
  (list 'draw-polygon  void-example-list [unknown "list of \\iscmclass{point} objects"] real-example-list)
  (list 'draw-polygon  void-example-list [unknown "list of \\iscmclass{point} objects"])
  (list 'draw-rectangle  void-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-rounded-rectangle  void-example-list real-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-rounded-rectangle  void-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-spline  void-example-list real-example-list real-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-text  void-example-list string-example-list real-example-list real-example-list)
  (list 'end-doc  void-example-list)
  (list 'end-drawing  void-example-list)
  (list 'end-page  void-example-list)
  (list 'get-background  brush%-example-list)
  (list 'get-background-mode  symbol-example-list)
  (list 'get-brush  brush%-example-list)
  (list 'get-char-height  real-example-list)
  (list 'get-char-width  real-example-list)
  (list 'get-clipping-region  void-example-list (boxed real-example-list) (boxed real-example-list) (boxed real-example-list) (boxed real-example-list))
  (list 'get-font  font%-example-list)
  (list 'get-logical-function  integer-example-list)
  (list 'get-pen  pen%-example-list)
  (list 'get-size  void-example-list (boxed real-example-list) (boxed real-example-list))
  (list 'get-text-background  color%-example-list)
  (list 'get-text-extent  void-example-list string-example-list (boxed real-example-list) (boxed real-example-list) (optional #f (boxed real-example-list)) (optional #f (boxed real-example-list)) (optional #f font%-example-list))
  (list 'get-text-extent  void-example-list string-example-list (boxed real-example-list) (boxed real-example-list) (optional #f (boxed real-example-list)) (optional #f (boxed real-example-list)))
  (list 'get-text-extent  void-example-list string-example-list (boxed real-example-list) (boxed real-example-list) (optional #f (boxed real-example-list)))
  (list 'get-text-extent  void-example-list string-example-list (boxed real-example-list) (boxed real-example-list))
  (list 'get-text-foreground  color%-example-list)
  (list 'ok?  boolean-example-list)
  (list 'set-background  void-example-list brush%-example-list)
  (list 'set-background-mode  void-example-list symbol-example-list)
  (list 'set-brush  void-example-list brush%-example-list)
  (list 'set-clipping-region  void-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'set-device-origin  void-example-list real-example-list real-example-list)
  (list 'set-font  void-example-list font%-example-list)
  (list 'set-logical-function  void-example-list integer-example-list)
  (list 'set-pen  void-example-list pen%-example-list)
  (list 'set-text-background  void-example-list color%-example-list)
  (list 'set-text-foreground  void-example-list color%-example-list)
  (list 'set-user-scale  void-example-list real-example-list real-example-list)
  (list 'start-doc  boolean-example-list string-example-list)
  (list 'start-page  boolean-example-list)
  (list 'try-color  void-example-list color%-example-list color%-example-list)))

(hash-table-put! classinfo font%
 (list font%-example-list 'font%
  (list
     (list )
     (list  integer-example-list symbol-example-list symbol-example-list symbol-example-list boolean-example-list)
     (list  integer-example-list symbol-example-list symbol-example-list symbol-example-list)
     (list  integer-example-list string-example-list symbol-example-list symbol-example-list symbol-example-list boolean-example-list)
     (list  integer-example-list string-example-list symbol-example-list symbol-example-list symbol-example-list))
  (list 'get-face  (optional #f string-example-list))
  (list 'get-family  symbol-example-list)
  (list 'get-font-id  integer-example-list)
  (list 'get-point-size  integer-example-list)
  (list 'get-style  symbol-example-list)
  (list 'get-underlined  boolean-example-list)
  (list 'get-weight  symbol-example-list)))

(hash-table-put! classinfo font-list%
 (list font-list%-example-list 'font-list%
  (list
     (list ))
  (list 'find-or-create-font  font%-example-list integer-example-list symbol-example-list symbol-example-list symbol-example-list boolean-example-list)
  (list 'find-or-create-font  font%-example-list integer-example-list symbol-example-list symbol-example-list symbol-example-list)
  (list 'find-or-create-font  void-example-list integer-example-list string-example-list symbol-example-list symbol-example-list symbol-example-list boolean-example-list)
  (list 'find-or-create-font  void-example-list integer-example-list string-example-list symbol-example-list symbol-example-list symbol-example-list)))

(hash-table-put! classinfo font-name-directory<%>
 (list font-name-directory<%>-example-list 'font-name-directory<%>
  (list)
  (list 'find-family-default-font-id  integer-example-list symbol-example-list)
  (list 'find-or-create-font-id  integer-example-list string-example-list symbol-example-list)
  (list 'get-afm-name  (optional #f string-example-list) integer-example-list symbol-example-list symbol-example-list)
  (list 'get-face-name  (optional #f string-example-list) integer-example-list)
  (list 'get-family  symbol-example-list integer-example-list)
  (list 'get-font-id  integer-example-list string-example-list)
  (list 'get-new-font-id  integer-example-list)
  (list 'get-post-script-name  (optional #f string-example-list) integer-example-list symbol-example-list symbol-example-list)
  (list 'get-screen-name  (optional #f string-example-list) integer-example-list symbol-example-list symbol-example-list)
  (list 'initialize  void-example-list integer-example-list symbol-example-list string-example-list)))

(hash-table-put! classinfo icon%
 (list icon%-example-list 'icon%
  (list
     (list  string-example-list symbol-example-list))
  (list 'get-depth  integer-example-list)
  (list 'get-height  integer-example-list)
  (list 'get-width  integer-example-list)
  (list 'load-file  boolean-example-list string-example-list symbol-example-list)
  (list 'load-file  boolean-example-list string-example-list)
  (list 'ok?  boolean-example-list)
  (list 'save-file  boolean-example-list string-example-list integer-example-list)))

(hash-table-put! classinfo memory-dc%
 (list memory-dc%-example-list 'memory-dc%
  (list
     (list ))
  (list 'begin-drawing  void-example-list)
  (list 'begin-set-pixel  void-example-list)
  (list 'blit  boolean-example-list real-example-list real-example-list real-example-list real-example-list canvas-dc%-example-list real-example-list real-example-list integer-example-list)
  (list 'blit  boolean-example-list real-example-list real-example-list real-example-list real-example-list canvas-dc%-example-list real-example-list real-example-list)
  (list 'clear  void-example-list)
  (list 'destroy-clipping-region  void-example-list)
  (list 'draw-arc  void-example-list real-example-list real-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-ellipse  void-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-icon  void-example-list icon%-example-list real-example-list real-example-list)
  (list 'draw-line  void-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-lines  void-example-list [unknown "list of \\iscmclass{point} objects"] real-example-list real-example-list)
  (list 'draw-lines  void-example-list [unknown "list of \\iscmclass{point} objects"] real-example-list)
  (list 'draw-lines  void-example-list [unknown "list of \\iscmclass{point} objects"])
  (list 'draw-point  void-example-list real-example-list real-example-list)
  (list 'draw-polygon  void-example-list [unknown "list of \\iscmclass{point} objects"] real-example-list real-example-list symbol-example-list)
  (list 'draw-polygon  void-example-list [unknown "list of \\iscmclass{point} objects"] real-example-list real-example-list)
  (list 'draw-polygon  void-example-list [unknown "list of \\iscmclass{point} objects"] real-example-list)
  (list 'draw-polygon  void-example-list [unknown "list of \\iscmclass{point} objects"])
  (list 'draw-rectangle  void-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-rounded-rectangle  void-example-list real-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-rounded-rectangle  void-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-spline  void-example-list real-example-list real-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-text  void-example-list string-example-list real-example-list real-example-list)
  (list 'end-doc  void-example-list)
  (list 'end-drawing  void-example-list)
  (list 'end-page  void-example-list)
  (list 'end-set-pixel  void-example-list)
  (list 'get-background  brush%-example-list)
  (list 'get-background-mode  symbol-example-list)
  (list 'get-brush  brush%-example-list)
  (list 'get-char-height  real-example-list)
  (list 'get-char-width  real-example-list)
  (list 'get-clipping-region  void-example-list (boxed real-example-list) (boxed real-example-list) (boxed real-example-list) (boxed real-example-list))
  (list 'get-font  font%-example-list)
  (list 'get-logical-function  integer-example-list)
  (list 'get-pen  pen%-example-list)
  (list 'get-pixel  boolean-example-list real-example-list real-example-list color%-example-list)
  (list 'get-size  void-example-list (boxed real-example-list) (boxed real-example-list))
  (list 'get-text-background  color%-example-list)
  (list 'get-text-extent  void-example-list string-example-list (boxed real-example-list) (boxed real-example-list) (optional #f (boxed real-example-list)) (optional #f (boxed real-example-list)) (optional #f font%-example-list))
  (list 'get-text-extent  void-example-list string-example-list (boxed real-example-list) (boxed real-example-list) (optional #f (boxed real-example-list)) (optional #f (boxed real-example-list)))
  (list 'get-text-extent  void-example-list string-example-list (boxed real-example-list) (boxed real-example-list) (optional #f (boxed real-example-list)))
  (list 'get-text-extent  void-example-list string-example-list (boxed real-example-list) (boxed real-example-list))
  (list 'get-text-foreground  color%-example-list)
  (list 'ok?  boolean-example-list)
  (list 'select-object  void-example-list (optional #f bitmap%-example-list))
  (list 'set-background  void-example-list brush%-example-list)
  (list 'set-background-mode  void-example-list symbol-example-list)
  (list 'set-brush  void-example-list brush%-example-list)
  (list 'set-clipping-region  void-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'set-device-origin  void-example-list real-example-list real-example-list)
  (list 'set-font  void-example-list font%-example-list)
  (list 'set-logical-function  void-example-list integer-example-list)
  (list 'set-pen  void-example-list pen%-example-list)
  (list 'set-pixel  void-example-list real-example-list real-example-list color%-example-list)
  (list 'set-text-background  void-example-list color%-example-list)
  (list 'set-text-foreground  void-example-list color%-example-list)
  (list 'set-user-scale  void-example-list real-example-list real-example-list)
  (list 'start-doc  boolean-example-list string-example-list)
  (list 'start-page  boolean-example-list)
  (list 'try-color  void-example-list color%-example-list color%-example-list)))

(hash-table-put! classinfo meta-file%
 (list meta-file%-example-list 'meta-file%
  (list)
  (list 'ok?  boolean-example-list)
  (list 'play  boolean-example-list dc<%>-example-list)
  (list 'set-clipboard  boolean-example-list integer-example-list integer-example-list)
  (list 'set-clipboard  boolean-example-list integer-example-list)
  (list 'set-clipboard  boolean-example-list)))

(hash-table-put! classinfo meta-file-dc%
 (list meta-file-dc%-example-list 'meta-file-dc%
  (list
     (list  string-example-list)
     (list ))
  (list 'begin-drawing  void-example-list)
  (list 'blit  boolean-example-list real-example-list real-example-list real-example-list real-example-list canvas-dc%-example-list real-example-list real-example-list integer-example-list)
  (list 'blit  boolean-example-list real-example-list real-example-list real-example-list real-example-list canvas-dc%-example-list real-example-list real-example-list)
  (list 'clear  void-example-list)
  (list 'close  meta-file%-example-list)
  (list 'destroy-clipping-region  void-example-list)
  (list 'draw-arc  void-example-list real-example-list real-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-ellipse  void-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-icon  void-example-list icon%-example-list real-example-list real-example-list)
  (list 'draw-line  void-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-lines  void-example-list [unknown "list of \\iscmclass{point} objects"] real-example-list real-example-list)
  (list 'draw-lines  void-example-list [unknown "list of \\iscmclass{point} objects"] real-example-list)
  (list 'draw-lines  void-example-list [unknown "list of \\iscmclass{point} objects"])
  (list 'draw-point  void-example-list real-example-list real-example-list)
  (list 'draw-polygon  void-example-list [unknown "list of \\iscmclass{point} objects"] real-example-list real-example-list symbol-example-list)
  (list 'draw-polygon  void-example-list [unknown "list of \\iscmclass{point} objects"] real-example-list real-example-list)
  (list 'draw-polygon  void-example-list [unknown "list of \\iscmclass{point} objects"] real-example-list)
  (list 'draw-polygon  void-example-list [unknown "list of \\iscmclass{point} objects"])
  (list 'draw-rectangle  void-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-rounded-rectangle  void-example-list real-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-rounded-rectangle  void-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-spline  void-example-list real-example-list real-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-text  void-example-list string-example-list real-example-list real-example-list)
  (list 'end-doc  void-example-list)
  (list 'end-drawing  void-example-list)
  (list 'end-page  void-example-list)
  (list 'get-background  brush%-example-list)
  (list 'get-background-mode  symbol-example-list)
  (list 'get-brush  brush%-example-list)
  (list 'get-char-height  real-example-list)
  (list 'get-char-width  real-example-list)
  (list 'get-clipping-region  void-example-list (boxed real-example-list) (boxed real-example-list) (boxed real-example-list) (boxed real-example-list))
  (list 'get-font  font%-example-list)
  (list 'get-logical-function  integer-example-list)
  (list 'get-pen  pen%-example-list)
  (list 'get-size  void-example-list (boxed real-example-list) (boxed real-example-list))
  (list 'get-text-background  color%-example-list)
  (list 'get-text-extent  void-example-list string-example-list (boxed real-example-list) (boxed real-example-list) (optional #f (boxed real-example-list)) (optional #f (boxed real-example-list)) (optional #f font%-example-list))
  (list 'get-text-extent  void-example-list string-example-list (boxed real-example-list) (boxed real-example-list) (optional #f (boxed real-example-list)) (optional #f (boxed real-example-list)))
  (list 'get-text-extent  void-example-list string-example-list (boxed real-example-list) (boxed real-example-list) (optional #f (boxed real-example-list)))
  (list 'get-text-extent  void-example-list string-example-list (boxed real-example-list) (boxed real-example-list))
  (list 'get-text-foreground  color%-example-list)
  (list 'ok?  boolean-example-list)
  (list 'set-background  void-example-list brush%-example-list)
  (list 'set-background-mode  void-example-list symbol-example-list)
  (list 'set-brush  void-example-list brush%-example-list)
  (list 'set-clipping-region  void-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'set-device-origin  void-example-list real-example-list real-example-list)
  (list 'set-font  void-example-list font%-example-list)
  (list 'set-logical-function  void-example-list integer-example-list)
  (list 'set-pen  void-example-list pen%-example-list)
  (list 'set-text-background  void-example-list color%-example-list)
  (list 'set-text-foreground  void-example-list color%-example-list)
  (list 'set-user-scale  void-example-list real-example-list real-example-list)
  (list 'start-doc  boolean-example-list string-example-list)
  (list 'start-page  boolean-example-list)
  (list 'try-color  void-example-list color%-example-list color%-example-list)))

(hash-table-put! classinfo pen%
 (list pen%-example-list 'pen%
  (list
     (list )
     (list  color%-example-list integer-example-list integer-example-list)
     (list  string-example-list integer-example-list integer-example-list))
  (list 'get-cap  integer-example-list)
  (list 'get-color  color%-example-list)
  (list 'get-join  integer-example-list)
  (list 'get-stipple  (optional #f bitmap%-example-list))
  (list 'get-style  integer-example-list)
  (list 'get-width  integer-example-list)
  (list 'set-cap  void-example-list integer-example-list)
  (list 'set-color  void-example-list color%-example-list)
  (list 'set-color  void-example-list string-example-list)
  (list 'set-color  void-example-list 0-to-255-example-list 0-to-255-example-list 0-to-255-example-list)
  (list 'set-join  void-example-list integer-example-list)
  (list 'set-stipple  void-example-list (optional #f bitmap%-example-list))
  (list 'set-style  void-example-list integer-example-list)
  (list 'set-width  void-example-list integer-example-list)))

(hash-table-put! classinfo pen-list%
 (list pen-list%-example-list 'pen-list%
  (list
     (list ))
  (list 'find-or-create-pen  pen%-example-list color%-example-list integer-example-list integer-example-list)
  (list 'find-or-create-pen  (optional #f pen%-example-list) string-example-list integer-example-list integer-example-list)))

(hash-table-put! classinfo point%
 (list point%-example-list 'point%
  (list
     (list )
     (list  real-example-list real-example-list))
  (list 'get-x  real-example-list)
  (list 'get-y  real-example-list)
  (list 'set-x  real-example-list)
  (list 'set-y  real-example-list)))

(hash-table-put! classinfo post-script-dc%
 (list post-script-dc%-example-list 'post-script-dc%
  (list
     (list  string-example-list boolean-example-list (optional #f (choice frame%-example-list dialog%-example-list)))
     (list  string-example-list boolean-example-list)
     (list  string-example-list))
  (list 'begin-drawing  void-example-list)
  (list 'blit  boolean-example-list real-example-list real-example-list real-example-list real-example-list canvas-dc%-example-list real-example-list real-example-list integer-example-list)
  (list 'blit  boolean-example-list real-example-list real-example-list real-example-list real-example-list canvas-dc%-example-list real-example-list real-example-list)
  (list 'clear  void-example-list)
  (list 'destroy-clipping-region  void-example-list)
  (list 'draw-arc  void-example-list real-example-list real-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-ellipse  void-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-icon  void-example-list icon%-example-list real-example-list real-example-list)
  (list 'draw-line  void-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-lines  void-example-list [unknown "list of \\iscmclass{point} objects"] real-example-list real-example-list)
  (list 'draw-lines  void-example-list [unknown "list of \\iscmclass{point} objects"] real-example-list)
  (list 'draw-lines  void-example-list [unknown "list of \\iscmclass{point} objects"])
  (list 'draw-point  void-example-list real-example-list real-example-list)
  (list 'draw-polygon  void-example-list [unknown "list of \\iscmclass{point} objects"] real-example-list real-example-list symbol-example-list)
  (list 'draw-polygon  void-example-list [unknown "list of \\iscmclass{point} objects"] real-example-list real-example-list)
  (list 'draw-polygon  void-example-list [unknown "list of \\iscmclass{point} objects"] real-example-list)
  (list 'draw-polygon  void-example-list [unknown "list of \\iscmclass{point} objects"])
  (list 'draw-rectangle  void-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-rounded-rectangle  void-example-list real-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-rounded-rectangle  void-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-spline  void-example-list real-example-list real-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-text  void-example-list string-example-list real-example-list real-example-list)
  (list 'end-doc  void-example-list)
  (list 'end-drawing  void-example-list)
  (list 'end-page  void-example-list)
  (list 'get-background  brush%-example-list)
  (list 'get-background-mode  symbol-example-list)
  (list 'get-brush  brush%-example-list)
  (list 'get-char-height  real-example-list)
  (list 'get-char-width  real-example-list)
  (list 'get-clipping-region  void-example-list (boxed real-example-list) (boxed real-example-list) (boxed real-example-list) (boxed real-example-list))
  (list 'get-font  font%-example-list)
  (list 'get-logical-function  integer-example-list)
  (list 'get-pen  pen%-example-list)
  (list 'get-size  void-example-list (boxed real-example-list) (boxed real-example-list))
  (list 'get-text-background  color%-example-list)
  (list 'get-text-extent  void-example-list string-example-list (boxed real-example-list) (boxed real-example-list) (optional #f (boxed real-example-list)) (optional #f (boxed real-example-list)) (optional #f font%-example-list))
  (list 'get-text-extent  void-example-list string-example-list (boxed real-example-list) (boxed real-example-list) (optional #f (boxed real-example-list)) (optional #f (boxed real-example-list)))
  (list 'get-text-extent  void-example-list string-example-list (boxed real-example-list) (boxed real-example-list) (optional #f (boxed real-example-list)))
  (list 'get-text-extent  void-example-list string-example-list (boxed real-example-list) (boxed real-example-list))
  (list 'get-text-foreground  color%-example-list)
  (list 'ok?  boolean-example-list)
  (list 'set-background  void-example-list brush%-example-list)
  (list 'set-background-mode  void-example-list symbol-example-list)
  (list 'set-brush  void-example-list brush%-example-list)
  (list 'set-clipping-region  void-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'set-device-origin  void-example-list real-example-list real-example-list)
  (list 'set-font  void-example-list font%-example-list)
  (list 'set-logical-function  void-example-list integer-example-list)
  (list 'set-pen  void-example-list pen%-example-list)
  (list 'set-text-background  void-example-list color%-example-list)
  (list 'set-text-foreground  void-example-list color%-example-list)
  (list 'set-user-scale  void-example-list real-example-list real-example-list)
  (list 'start-doc  boolean-example-list string-example-list)
  (list 'start-page  boolean-example-list)
  (list 'try-color  void-example-list color%-example-list color%-example-list)))

(hash-table-put! classinfo printer-dc%
 (list printer-dc%-example-list 'printer-dc%
  (list
     (list  (optional #f string-example-list) (optional #f string-example-list) (optional #f string-example-list) boolean-example-list)
     (list  (optional #f string-example-list) (optional #f string-example-list) (optional #f string-example-list)))
  (list 'begin-drawing  void-example-list)
  (list 'blit  boolean-example-list real-example-list real-example-list real-example-list real-example-list canvas-dc%-example-list real-example-list real-example-list integer-example-list)
  (list 'blit  boolean-example-list real-example-list real-example-list real-example-list real-example-list canvas-dc%-example-list real-example-list real-example-list)
  (list 'clear  void-example-list)
  (list 'destroy-clipping-region  void-example-list)
  (list 'draw-arc  void-example-list real-example-list real-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-ellipse  void-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-icon  void-example-list icon%-example-list real-example-list real-example-list)
  (list 'draw-line  void-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-lines  void-example-list [unknown "list of \\iscmclass{point} objects"] real-example-list real-example-list)
  (list 'draw-lines  void-example-list [unknown "list of \\iscmclass{point} objects"] real-example-list)
  (list 'draw-lines  void-example-list [unknown "list of \\iscmclass{point} objects"])
  (list 'draw-point  void-example-list real-example-list real-example-list)
  (list 'draw-polygon  void-example-list [unknown "list of \\iscmclass{point} objects"] real-example-list real-example-list symbol-example-list)
  (list 'draw-polygon  void-example-list [unknown "list of \\iscmclass{point} objects"] real-example-list real-example-list)
  (list 'draw-polygon  void-example-list [unknown "list of \\iscmclass{point} objects"] real-example-list)
  (list 'draw-polygon  void-example-list [unknown "list of \\iscmclass{point} objects"])
  (list 'draw-rectangle  void-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-rounded-rectangle  void-example-list real-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-rounded-rectangle  void-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-spline  void-example-list real-example-list real-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'draw-text  void-example-list string-example-list real-example-list real-example-list)
  (list 'end-doc  void-example-list)
  (list 'end-drawing  void-example-list)
  (list 'end-page  void-example-list)
  (list 'get-background  brush%-example-list)
  (list 'get-background-mode  symbol-example-list)
  (list 'get-brush  brush%-example-list)
  (list 'get-char-height  real-example-list)
  (list 'get-char-width  real-example-list)
  (list 'get-clipping-region  void-example-list (boxed real-example-list) (boxed real-example-list) (boxed real-example-list) (boxed real-example-list))
  (list 'get-font  font%-example-list)
  (list 'get-logical-function  integer-example-list)
  (list 'get-pen  pen%-example-list)
  (list 'get-size  void-example-list (boxed real-example-list) (boxed real-example-list))
  (list 'get-text-background  color%-example-list)
  (list 'get-text-extent  void-example-list string-example-list (boxed real-example-list) (boxed real-example-list) (optional #f (boxed real-example-list)) (optional #f (boxed real-example-list)) (optional #f font%-example-list))
  (list 'get-text-extent  void-example-list string-example-list (boxed real-example-list) (boxed real-example-list) (optional #f (boxed real-example-list)) (optional #f (boxed real-example-list)))
  (list 'get-text-extent  void-example-list string-example-list (boxed real-example-list) (boxed real-example-list) (optional #f (boxed real-example-list)))
  (list 'get-text-extent  void-example-list string-example-list (boxed real-example-list) (boxed real-example-list))
  (list 'get-text-foreground  color%-example-list)
  (list 'ok?  boolean-example-list)
  (list 'set-background  void-example-list brush%-example-list)
  (list 'set-background-mode  void-example-list symbol-example-list)
  (list 'set-brush  void-example-list brush%-example-list)
  (list 'set-clipping-region  void-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'set-device-origin  void-example-list real-example-list real-example-list)
  (list 'set-font  void-example-list font%-example-list)
  (list 'set-logical-function  void-example-list integer-example-list)
  (list 'set-pen  void-example-list pen%-example-list)
  (list 'set-text-background  void-example-list color%-example-list)
  (list 'set-text-foreground  void-example-list color%-example-list)
  (list 'set-user-scale  void-example-list real-example-list real-example-list)
  (list 'start-doc  boolean-example-list string-example-list)
  (list 'start-page  boolean-example-list)
  (list 'try-color  void-example-list color%-example-list color%-example-list)))

(hash-table-put! classinfo ps-setup%
 (list ps-setup%-example-list 'ps-setup%
  (list)
  (list 'copy-from  void-example-list ps-setup%-example-list)
  (list 'get-afm-path  (optional #f string-example-list))
  (list 'get-command  string-example-list)
  (list 'get-file  string-example-list)
  (list 'get-level-2  boolean-example-list)
  (list 'get-mode  symbol-example-list)
  (list 'get-options  string-example-list)
  (list 'get-orientation  symbol-example-list)
  (list 'get-paper-name  string-example-list)
  (list 'get-preview-command  string-example-list)
  (list 'get-scaling  void-example-list (boxed real-example-list) (boxed real-example-list))
  (list 'get-translation  void-example-list (boxed real-example-list) (boxed real-example-list))
  (list 'set-afm-path  void-example-list (optional #f string-example-list))
  (list 'set-command  void-example-list string-example-list)
  (list 'set-file  void-example-list string-example-list)
  (list 'set-level-2  void-example-list boolean-example-list)
  (list 'set-mode  void-example-list integer-example-list)
  (list 'set-options  void-example-list string-example-list)
  (list 'set-orientation  void-example-list integer-example-list)
  (list 'set-paper-name  void-example-list string-example-list)
  (list 'set-preview-command  void-example-list string-example-list)
  (list 'set-scaling  void-example-list real-example-list real-example-list)
  (list 'set-translation  void-example-list real-example-list real-example-list)))

(hash-table-put! classinfo '"Global Graphics and Screen"
 (list #f ''"Global Graphics and Screen"
  (list)
  (list 'current-ps-setup  ps-setup%-example-list)
  (list 'current-ps-setup  void-example-list ps-setup%-example-list)
  (list 'flush-display  void-example-list)
  (list 'get-display-depth  integer-example-list)
  (list 'get-display-size  'values)
  (list 'get-face-list  string-list-example-list)
  (list 'is-color-display?  boolean-example-list)
  (list 'make-meta-file-placeable  boolean-example-list string-example-list integer-example-list integer-example-list integer-example-list integer-example-list real-example-list)
  (list 'make-meta-file-placeable  boolean-example-list string-example-list integer-example-list integer-example-list integer-example-list integer-example-list)
  (list 'register-collecting-blit  void-example-list canvas%-example-list real-example-list real-example-list real-example-list real-example-list memory-dc%-example-list memory-dc%-example-list real-example-list real-example-list real-example-list real-example-list)
  (list 'register-collecting-blit  void-example-list canvas%-example-list real-example-list real-example-list real-example-list real-example-list memory-dc%-example-list memory-dc%-example-list real-example-list real-example-list real-example-list)
  (list 'register-collecting-blit  void-example-list canvas%-example-list real-example-list real-example-list real-example-list real-example-list memory-dc%-example-list memory-dc%-example-list real-example-list real-example-list)
  (list 'register-collecting-blit  void-example-list canvas%-example-list real-example-list real-example-list real-example-list real-example-list memory-dc%-example-list memory-dc%-example-list real-example-list)
  (list 'register-collecting-blit  void-example-list canvas%-example-list real-example-list real-example-list real-example-list real-example-list memory-dc%-example-list memory-dc%-example-list)
  'the-brush-list
  'the-color-database
  'the-font-list
  'the-font-name-directory
  'the-pen-list
  (list 'unregister-collecting-blit  void-example-list canvas%-example-list)))
