;; sigs.ss for srpersist collection

(define-signature srpersist:srpersist^ 

  ; utility

  (sql-make-length
   sql-read-length
   sql-make-indicator
   sql-read-indicator
   sql-set-indicator
   sql-read-row-status
   sql-read-op-parms
   sql-make-buffer
   sql-read-buffer
   sql-write-buffer

   ; ODBC procedures 

   sql-alloc-connect
   sql-alloc-env
   sql-alloc-handle
   sql-alloc-stmt
   sql-bind-col
   sql-bind-param
   sql-cancel
   sql-close-cursor
   sql-col-attribute
   sql-columns
   sql-connect
   sql-copy-desc
   sql-data-sources
   sql-describe-col
   sql-disconnect
   sql-end-tran
   sql-error
   sql-exec-direct
   sql-execute
   sql-fetch
   sql-fetch-scroll
   sql-free-connect
   sql-free-env
   sql-free-handle
   sql-free-stmt
   sql-get-connect-attr
   sql-get-connect-option
   sql-get-cursor-name
   sql-get-data
   sql-get-desc-field
   sql-get-desc-rec
   sql-get-diag-field
   sql-get-diag-rec
   sql-get-env-attr
   sql-get-functions
   sql-get-info
   sql-get-stmt-attr
   sql-get-stmt-option
   sql-get-type-info
   sql-num-result-cols
   sql-param-data
   sql-prepare
   sql-put-data
   sql-row-count
   sql-set-connect-attr
   sql-set-connect-option
   sql-set-cursor-name
   sql-set-desc-field
   sql-set-desc-rec
   sql-set-env-attr
   sql-set-param
   sql-set-stmt-attr
   sql-set-stmt-option
   sql-special-columns
   sql-statistics
   sql-tables
   sql-transact
   sql-driver-connect
   sql-browse-connect
   sql-col-attributes
   sql-column-privileges
   sql-describe-param
   sql-extended-fetch
   sql-foreign-keys
   sql-more-results
   sql-native-sql
   sql-num-params
   sql-param-options
   sql-primary-keys
   sql-procedure-columns
   sql-procedures
   sql-set-pos
   sql-table-privileges
   sql-drivers
   sql-bind-parameter
   sql-set-scroll-options

   ; implementation of ODBC macro

   sql-len-binary-attr

   ; structures

   struct:sql-numeric
   make-sql-numeric
   sql-numeric?
   sql-numeric-precision
   set-sql-numeric-precision!
   sql-numeric-scale
   set-sql-numeric-scale!
   sql-numeric-sign
   set-sql-numeric-sign!
   sql-numeric-val
   set-sql-numeric-val!
   struct:sql-date
   make-sql-date
   sql-date?
   sql-date-year
   set-sql-date-year!
   sql-date-month
   set-sql-date-month!
   sql-date-day
   set-sql-date-day!
   struct:sql-time
   make-sql-time
   sql-time?
   sql-time-hour
   set-sql-time-hour!
   sql-time-minute
   set-sql-time-minute!
   sql-time-second
   set-sql-time-second!
   struct:sql-timestamp
   make-sql-timestamp
   sql-timestamp?
   sql-timestamp-year
   set-sql-timestamp-year!
   sql-timestamp-month
   set-sql-timestamp-month!
   sql-timestamp-day
   set-sql-timestamp-day!
   sql-timestamp-hour
   set-sql-timestamp-hour!
   sql-timestamp-minute
   set-sql-timestamp-minute!
   sql-timestamp-second
   set-sql-timestamp-second!
   sql-timestamp-fraction
   set-sql-timestamp-fraction!
   struct:sql-guid
   make-sql-guid
   sql-guid?
   sql-guid-data1
   set-sql-guid-data1!
   sql-guid-data2
   set-sql-guid-data2!
   sql-guid-data3
   set-sql-guid-data3!
   sql-guid-data4
   set-sql-guid-data4!
   struct:sql-year-interval
   make-sql-year-interval
   sql-year-interval?
   sql-year-interval-sign
   set-sql-year-interval-sign!
   sql-year-interval-year
   set-sql-year-interval-year!
   struct:sql-month-interval
   make-sql-month-interval
   sql-month-interval?
   sql-month-interval-sign
   set-sql-month-interval-sign!
   sql-month-interval-month
   set-sql-month-interval-month!
   struct:sql-day-interval
   make-sql-day-interval
   sql-day-interval?
   sql-day-interval-sign
   set-sql-day-interval-sign!
   sql-day-interval-day
   set-sql-day-interval-day!
   struct:sql-hour-interval
   make-sql-hour-interval
   sql-hour-interval?
   sql-hour-interval-sign
   set-sql-hour-interval-sign!
   sql-hour-interval-hour
   set-sql-hour-interval-hour!
   struct:sql-minute-interval
   make-sql-minute-interval
   sql-minute-interval?
   sql-minute-interval-sign
   set-sql-minute-interval-sign!
   sql-minute-interval-minute
   set-sql-minute-interval-minute!
   struct:sql-second-interval
   make-sql-second-interval
   sql-second-interval?
   sql-second-interval-sign
   set-sql-second-interval-sign!
   sql-second-interval-second
   set-sql-second-interval-second!
   struct:sql-year-to-month-interval
   make-sql-year-to-month-interval
   sql-year-to-month-interval?
   sql-year-to-month-interval-sign
   set-sql-year-to-month-interval-sign!
   sql-year-to-month-interval-year
   set-sql-year-to-month-interval-year!
   sql-year-to-month-interval-month
   set-sql-year-to-month-interval-month!
   struct:sql-day-to-hour-interval
   make-sql-day-to-hour-interval
   sql-day-to-hour-interval?
   sql-day-to-hour-interval-sign
   set-sql-day-to-hour-interval-sign!
   sql-day-to-hour-interval-day
   set-sql-day-to-hour-interval-day!
   sql-day-to-hour-interval-hour
   set-sql-day-to-hour-interval-hour!
   struct:sql-day-to-minute-interval
   make-sql-day-to-minute-interval
   sql-day-to-minute-interval?
   sql-day-to-minute-interval-sign
   set-sql-day-to-minute-interval-sign!
   sql-day-to-minute-interval-day
   set-sql-day-to-minute-interval-day!
   sql-day-to-minute-interval-hour
   set-sql-day-to-minute-interval-hour!
   sql-day-to-minute-interval-minute
   set-sql-day-to-minute-interval-minute!
   struct:sql-day-to-second-interval
   make-sql-day-to-second-interval
   sql-day-to-second-interval?
   sql-day-to-second-interval-sign
   set-sql-day-to-second-interval-sign!
   sql-day-to-second-interval-day
   set-sql-day-to-second-interval-day!
   sql-day-to-second-interval-hour
   set-sql-day-to-second-interval-hour!
   sql-day-to-second-interval-minute
   set-sql-day-to-second-interval-minute!
   sql-day-to-second-interval-second
   set-sql-day-to-second-interval-second!
   struct:sql-hour-to-minute-interval
   make-sql-hour-to-minute-interval
   sql-hour-to-minute-interval?
   sql-hour-to-minute-interval-sign
   set-sql-hour-to-minute-interval-sign!
   sql-hour-to-minute-interval-hour
   set-sql-hour-to-minute-interval-hour!
   sql-hour-to-minute-interval-minute
   set-sql-hour-to-minute-interval-minute!
   struct:sql-hour-to-second-interval
   make-sql-hour-to-second-interval
   sql-hour-to-second-interval?
   sql-hour-to-second-interval-sign
   set-sql-hour-to-second-interval-sign!
   sql-hour-to-second-interval-hour
   set-sql-hour-to-second-interval-hour!
   sql-hour-to-second-interval-minute
   set-sql-hour-to-second-interval-minute!
   sql-hour-to-second-interval-second
   set-sql-hour-to-second-interval-second!
   struct:sql-minute-to-second-interval
   make-sql-minute-to-second-interval
   sql-minute-to-second-interval?
   sql-minute-to-second-interval-sign
   set-sql-minute-to-second-interval-sign!
   sql-minute-to-second-interval-minute
   set-sql-minute-to-second-interval-minute!
   sql-minute-to-second-interval-second
   set-sql-minute-to-second-interval-second!))
