/* Automatically generated by po2tbl.sed from wbuild.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"\
wbuild usage:\n\
wbuild [options] input-files\n\
-v, --version\t\tPrint version and exit\n\
-h, --help\t\tPrint this message and exit\n\
-l, --no-lines\t\tDon't generate #line directives\n\
-p, --include-prefix\tSpecify prefix for generated #include directives\n\
-O, --only\t\tSet class to output code for\n\
-i, --include-dir\tdirectory for generated include files\n\
-c, --c-dir\t\tdirectory for generated c files\n\
-d, --doc-dir, --documentation-dir\n\
\t\t\tdirectory for generated documentation files\n\
    --force\t\tForce regeneration of all files, ignoring timestamps\n\
    --no-init-file\tDo not read initialization file\n\
\n\
Report bugs to free-widgets-bugs@let.rug.nl\n", 2},
  {"\
Copyright (C) %s Joel N. Weber II\n\
This is free software; see the source for copying conditions.  There is NO\n\
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.\n", 3},
  {"Written by %s\n", 4},
  {"%s:%d: cyclic dependency found in superclasses of %s\n", 5},
  {"%s:%d: method \"%s\" or class \"%s\" not found\n", 6},
  {"superclass %s not found\n", 7},
  {"%s:%d: Missing type for `%s'\n", 8},
  {"%s:%d: unmatched \"|\" in text\n", 9},
  {"%s:%d: (in %s) no superclass (#) defined\n", 10},
  {"%s:%d: (in %s) identifier `#%s' is unknown\n", 11},
  {"%s:%d: (in %s) identifier `$%s' is unknown\n", 12},
  {"%s:%d: (in %s) missing `)' after `$%s(%s'\n", 13},
  {"%s:%d: (in %s) class `%s' is not a superclass\n", 14},
  {"%s:%d: (in %s) missing identifier after `$(%s)'\n", 15},
  {"%s:%d: (in %s) missing identifier after `$%s()'\n", 16},
};

int _msg_tbl_length = 16;
