(load-relative "util.ss")
(let ([check-check-syntax
       (lambda (str)
	 (let ([drs-frame (wait-for-drscheme-frame)])
	   (clear-definitions drs-frame)
	   (type-in-definitions drs-frame str)
	   (mred:test:button-push (ivar drs-frame check-syntax-button))
	   (let ([frame (mred:test:get-active-frame)])
	     (unless (eq? frame drs-frame)
	       (error 'check-syntax "unexpected window ~a" frame)))))])
  (check-check-syntax "x")
  (check-check-syntax ".")
  (check-check-syntax "(")
  (check-check-syntax "begin")
  (check-check-syntax "(begin)")
  (check-check-syntax "1")
  (check-check-syntax "add1")
  (check-check-syntax "(lambda (x) x)"))
