(require (lib "url.ss" "net")
         "util.ss")

(define (v-path=? p1 p2)
  (and (equal? (virtual-path-directory-part p1)
               (virtual-path-directory-part p2))
       (equal? (virtual-path-file-part p1)
               (virtual-path-file-part p2))))

(define test
  (lambda (d f vp)
    (display (v-path=? (make-virtual-path d f) vp))
    (newline)))

(define url1 (string->url "http://www.home.org"))
(define url2 (string->url "http://www.home.org/"))
(define url3 (string->url "http://www.home.org;param"))
(define url4 (string->url "http://www.home.org/;param"))
(define url5 (string->url "http://www.home.org/a"))
(define url6 (string->url "http://www.home.org/a;param"))

(test '() "" (url->virtual-path url1))
(test '() "" (url->virtual-path url2))
(test '() "" (url->virtual-path url3))
(test '() "" (url->virtual-path url4))
(test '() "a" (url->virtual-path url5))
(test '() "a" (url->virtual-path url6))
(newline)

(define url7 (string->url ""))
(define url8 (string->url "/"))
(define url9 (string->url ";param"))
(define url10 (string->url "/;param"))
(define url11 (string->url "/a"))
(define url12 (string->url "/a;param"))

(test '() "" (url->virtual-path url7))
(test '() "" (url->virtual-path url8))
(test '() "" (url->virtual-path url9))
(test '() "" (url->virtual-path url10))
(test '() "a" (url->virtual-path url11))
(test '() "a" (url->virtual-path url12))
(newline)

(define url13 (string->url "http://www.home.org/a/"))
(define url14 (string->url "http://www.home.org/a/;param"))
(define url15 (string->url "http://www.home.org/a/b;param"))
(define url16 (string->url "a/"))
(define url17 (string->url "a/;param"))
(define url18 (string->url "a/b;param"))

(test '("a") "" (url->virtual-path url13))
(test '("a") "" (url->virtual-path url14))
(test '("a") "b" (url->virtual-path url15))
(test '("a") "" (url->virtual-path url16))
(test '("a") "" (url->virtual-path url17))
(test '("a") "b" (url->virtual-path url18))
(newline)

(define url18 (string->url ""))
(define url19 (string->url ";"))
(define url20 (string->url "/a/"))
(define url21 (string->url "/a/;"))
(define url22 (string->url "/a/;param"))

(test '() "" (url->virtual-path url18))
(test '() "" (url->virtual-path url19))
(test '("a") "" (url->virtual-path url20))
(test '("a") "" (url->virtual-path url21))
(test '("a") "" (url->virtual-path url22))
(newline)

(define url23 (string->url "http://www.home.net/.."))
(define url24 (string->url "http://www.home.net/a/.."))
(define url25 (string->url "http://www.home.net/a/b/.."))
(define url26 (string->url ".."))
(define url27 (string->url "/.."))
(define url28 (string->url "a/.."))
(define url29 (string->url "/a/.."))
(define url30 (string->url "/a/b/.."))

(test '("..") "" (url->virtual-path url23))
(test '() "" (url->virtual-path url24))
(test '("a") "" (url->virtual-path url25))
(test '("..") "" (url->virtual-path url26))
(test '("..") "" (url->virtual-path url27))
(test '() "" (url->virtual-path url28))
(test '() "" (url->virtual-path url29))
(test '("a") "" (url->virtual-path url30))
(newline)

(define url31 (string->url "http://www.home.net/1/2/3/4/.."))
(define url32 (string->url "http://www.home.org/1/2/3/4/../../"))
(define url33 (string->url "http://www.home.org/1/2/3/4/../../.."))
(define url34 (string->url "http://www.home.org/1/2/3/4/../../../../"))
(define url35 (string->url "http://www.home.org/1/2/3/4/../../../../.."))
(define url36 (string->url "http://www.home.org/1/2/3/4/../../../../../../"))

(test '("1" "2" "3") "" (url->virtual-path url31))
(test '("1" "2") "" (url->virtual-path url32))
(test '("1") "" (url->virtual-path url33))
(test '() "" (url->virtual-path url34))
(test '("..") "" (url->virtual-path url35))
(test '(".." "..") "" (url->virtual-path url36))
(newline)

(define url37 (string->url "1/."))
(define url38 (string->url "2/./."))
(define url39 (string->url "3/././"))
(define url40 (string->url "http://www.home.org/1/./.."))
(define url41 (string->url "http://www.home.org/1/../."))
(define url42 (string->url "http://www.home.org/1/./../."))

(test '("1") "" (url->virtual-path url37))
(test '("2") "" (url->virtual-path url38))
(test '("3") "" (url->virtual-path url39))
(test '() "" (url->virtual-path url40))
(test '() "" (url->virtual-path url41))
(test '() "" (url->virtual-path url42))
(newline)

(define url43 (string->url "http://www.home.org/1/2/3/../4/../../5"))
(define url44 (string->url "http://www.home.org/1/2/3/../4/../../5/../../6"))
(define url45 (string->url "http://www.home.org/1/2/3/../4/../../5/../../6/../.."))
(define url46 (string->url "http://www.hme.org/1/2/3/../4/../../5/../../6/../../7/../"))
(define url47 (string->url "http://www.h.org/1/2/3/../4/../../5/../../6/../../7/../.."))
(define url48 (string->url "http://www.home.com/1/2/3/../../../a/b/c/d"))
(define url49 (string->url "http://www.home.com/1/2/3/../../../../a/b/c/d"))
(define url50 (string->url "http://www.home.net/1/2/3/../../../../a/b/./c/"))
(define url51 (string->url "http://www.home.gov;paramfirst/then/a/path"))

(test '("1") "5" (url->virtual-path url43))
(test '() "6" (url->virtual-path url44))
(test '("..") "" (url->virtual-path url45))
(test '("..") "" (url->virtual-path url46))
(test '(".." "..") "" (url->virtual-path url47))
(test '("a" "b" "c") "d" (url->virtual-path url48))
(test '(".." "a" "b" "c") "d" (url->virtual-path url49))
(test '(".." "a" "b" "c") "" (url->virtual-path url50))
(test '("then" "a") "path" (url->virtual-path url51))
(newline)
(display "Done!")
(newline)
