(module info (lib "infotab.ss" "setup")
  (define name "Test Suite")
  (define tools '(("private/test-suite-tool.ss")))
  (define tool-names (list "The Test Suite Tool"))
  (define tool-icons (list '("question-mark.jpeg" "test-suite" "private/icons"))))
