#!/bin/sh

PLTCOLLECTS=`pwd`/..:$PLTCOLLECTS

if [ "`basename $0`" = "go" ]; then
    TOOL=""
else
    TOOL="spidey-"
fi

if [ "$1" = "" ]; then
    ARG=""
else
    ARG="#f"
fi

exec mzscheme -x  -f invoke.ss -e "(zodiac:${TOOL}see ${ARG})"
