;;This file was generated by genrate-code.ss on Thursday, May 11th, 2000 10:54:57am

;; xml-single-content->html : Content (listof Html-element) -> Html-element
(define (xml-single-content->html x acc)
  (cond
   ((element? x)
    (cons
     (case (element-name x)
       ((html)
        (make-html
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((div)
        (make-div
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((center)
        (make-center
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((blockquote)
        (make-blockquote
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((ins)
        (make-ins
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((del)
        (make-del
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((dd)
        (make-dd
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((li)
        (make-li
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((th)
        (make-th
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((td)
        (make-td
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((iframe)
        (make-iframe
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((noframes)
        (make-noframes
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((noscript)
        (make-noscript
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((style)
        (make-style
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((script)
        (make-script
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((basefont)
        (make-basefont
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((br)
        (make-br
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((area)
        (make-area
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((link)
        (make-link
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((img)
        (make-img
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((param)
        (make-param
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((hr)
        (make-hr
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((input)
        (make-input
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((col)
        (make-col
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((isindex)
        (make-isindex
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((base)
        (make-base
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((meta)
        (make-meta
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((option)
        (make-option
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((textarea)
        (make-textarea
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((title)
        (make-title
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((head)
        (make-head
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((tr)
        (make-tr
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((colgroup)
        (make-colgroup
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((thead)
        (make-thead
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((tfoot)
        (make-tfoot
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((tbody)
        (make-tbody
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((tt)
        (make-tt
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((i)
        (make-i
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((b)
        (make-b
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((u)
        (make-u
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((s)
        (make-s
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((strike)
        (make-strike
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((big)
        (make-big
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((small)
        (make-small
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((em)
        (make-em
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((strong)
        (make-strong
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((dfn)
        (make-dfn
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((code)
        (make-code
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((samp)
        (make-samp
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((kbd)
        (make-kbd
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((var)
        (make-var
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((cite)
        (make-cite
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((abbr)
        (make-abbr
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((acronym)
        (make-acronym
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((sub)
        (make-sub
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((sup)
        (make-sup
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((span)
        (make-span
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((bdo)
        (make-bdo
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((font)
        (make-font
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((p)
        (make-p
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((h1)
        (make-h1
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((h2)
        (make-h2
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((h3)
        (make-h3
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((h4)
        (make-h4
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((h5)
        (make-h5
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((h6)
        (make-h6
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((q)
        (make-q
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((dt)
        (make-dt
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((legend)
        (make-legend
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((caption)
        (make-caption
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((table)
        (make-table
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((button)
        (make-button
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((fieldset)
        (make-fieldset
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((optgroup)
        (make-optgroup
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((select)
        (make-select
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((label)
        (make-label
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((form)
        (make-form
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((ol)
        (make-ol
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((ul)
        (make-ul
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((dir)
        (make-dir
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((menu)
        (make-menu
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((dl)
        (make-dl
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((pre)
        (make-pre
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((object)
        (make-object (element-attributes x)
          (xml-contents->html (element-content x))))
       ((applet)
        (make-applet
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((map)
        (make-map
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((a)
        (make-a
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((address)
        (make-address
          (element-attributes x)
          (xml-contents->html (element-content x))))
       ((body)
        (make-body
          (element-attributes x)
          (xml-contents->html (element-content x)))))
     acc))
   ((or (pcdata? x) (entity? x)) (cons x acc))
   (else acc)))
