#!/bin/sh
string=? ; exec mzscheme -qr $0 "$@"

; for john? 

; This list determines the order of libraries in the index file:
(define libraries
  '("Convert"
    "Guess"    
    "Mastermind"
    "Simple Drawing Exercises"
    "Hangman"
    "Arrows"
    "Documents"
    "Directories"
    "Graphing Functions"
    "GUI"
    "Lkup GUI"
    "Arrows GUI"
    "Guess GUI"
    "Elevator"
    "Simplified Scheme Web Servlets"
    "Scheme Web Servlets"
    "Show Queen"))

; Defines go to be the go from thtml2html
(define go
  (let* ([testpath (lambda (x) (and (directory-exists? x) x))]
         [trashy-path
          (or (testpath (format "~a/Packages/TrashyTeXTools/"
                                (or (getenv "HOMESCHEME")
                                    "/Users/matthias/")))
              (testpath (build-path (collection-path "mzlib") 'up 'up  'up "TrashyTeXTools")))])
    (unless trashy-path
      (error 'mkdocs "Couldn't find TrashyTeXTools"))
    
    ;; this dynamic-require should work, but require doesn't seem to
    ;; like absolute paths, so do a load manually.
    (dynamic-require `(file ,(build-path trashy-path "bin" "thtml2html.scm")) 'go)))

(require (lib "cmdline.ss"))

(parse-command-line
 "mkdocs"
 argv
 `()
 (lambda (-) (void))
 null)

(require (lib "list.ss"))

(define dest-dir (build-path (collection-path "doc") "teachpack"))

(unless (directory-exists? dest-dir)
  (make-directory dest-dir))

(define src-files
  (filter (lambda (x) (and (regexp-match "[.]thtml$" x)
			   (not (regexp-match "^index[.]thtml$" x))))
	  (directory-list)))

;; Get library names:

(define lib-names  
  ; Get list of (cons name file)
 (map (lambda (s)
	(with-input-from-file s
	  (lambda ()
	    (let loop ()
	      (let ([l (read-line)])
		(cond
		 [(eof-object? l)
		  (error 'mkdocs "EOF before library name found in ~s" s)]
		 [(regexp-match "#define LIBNAME (.*)" l)
		  => (lambda (m)
		       (cons (cadr m) s))]
		 [else (loop)]))))
          'text))
      src-files))

;; Check library list:

(for-each (lambda (s) (unless (member (car s) libraries)
                        (printf "libraries: ~s~n" libraries)
                        (error 'mkdocs "library not listed in mkdocs: ~s = ~s" 
			       (cdr s) (car s))))
	  lib-names)
(let ([found-libraries (map car lib-names)])
  (for-each (lambda (s) (unless (member s found-libraries)
			  (error 'mkdocs "non-existent library listed in mkdocs: ~a" 
				 s)))
	    libraries))
(let loop ([libs lib-names][saw null])
  (cond
   [(null? libs) (void)]
   [(assoc (caar libs) saw)
    => (lambda (m)
	 (error 'mkdocs "library ~a has two .thtml files: ~a and ~a" 
		(caar libs) (cdar libs) (cdr m)))]
   [else (loop (cdr libs) (cons (car libs) saw))]))

;; Make index.thtml:

(define (thtml-name->html s)
  (regexp-replace "thtml$" s "html"))

(with-output-to-file "index.thtml"
  (lambda ()
    (printf "<HTML>~n")
    (printf "<HEAD>~n")
    (printf "<TITLE>Teachpacks for How to Design Programs</TITLE>~n")
    (printf "</HEAD>~n")
    (printf "<BODY bgcolor=\"#ffffff\" text=\"#000000\" link=\"#009900\" vlink=\"#007700\" alink=\"#cc0000\">~n")
    (printf "<h1>Teachpacks for How to Design Programs</h1>~n")
    (printf "~n")
    (printf "<UL>~n")
    (for-each
     (lambda (libname)
       (let ([file (thtml-name->html (cdr (assoc libname lib-names)))])
	 (printf "<LI> <A HREF=~s>~a</A>~n" file libname)))
     libraries)
    (printf "</UL>~n~n")
    (printf "#include foot.tinc~n"))
  'replace)

(set! src-files (cons "index.thtml" src-files))

;; Make .html files:

(define dest-files
  (map (lambda (s)
	 (let ([html (thtml-name->html s)])
	   (build-path dest-dir html)))
       src-files))
		       
(for-each
 (lambda (src dest)
   (go (vector "html"
	       "-o"
	       dest
	       "-f"
	       src)))
 src-files dest-files)

;; Make hdindex file:

(let ([ifile (build-path dest-dir "hdindex")])
  (printf "Writing ~s~n" ifile)
  (with-output-to-file ifile
    (lambda ()
      (printf "(~n")
      (printf "~s~n"
              '("Teachpacks for \"How to Design Programs\""
                "index.html"
                "HtDP"
                "Arrows GUI teachpack"))
      (for-each
       (lambda (lib-name)
	 (let ([src (cdr lib-name)]
	       [title (car lib-name)])
	   (with-input-from-file src
	     (lambda ()
	       (let loop ()
		 (let ([l (read-line)])
		   (unless (eof-object? l)
		     (let ([m (regexp-match "<<LIBDESC>>{([^}]*)}" l)])
		       (when m
			 (printf "(~s ~s ~s ~s)~n" 
				 (cadr m) 
				 (thtml-name->html src) 
				 (cadr m)
				 (format "~a teachpack" title))))
		     (loop)))))
             'text)))
       lib-names)
      (printf ")~n"))
    'truncate))
