/* DO NOT EDIT THIS FILE. */
/* This file was generated by xctocc from "wxs_evnt.xc". */


#if defined(_MSC_VER)
# include "wx.h"
#endif

#include "wx_stdev.h"





#include "wxscheme.h"
#include "wxs_evnt.h"
#include "wxscomon.h"


static Scheme_Object *eventClass_wxTYPE_KEY_EVENT_sym = NULL;
static Scheme_Object *eventClass_wxTYPE_COMMAND_EVENT_sym = NULL;
static Scheme_Object *eventClass_wxTYPE_MOUSE_EVENT_sym = NULL;

static void init_symset_eventClass(void) {
  eventClass_wxTYPE_KEY_EVENT_sym = scheme_intern_symbol("key");
  eventClass_wxTYPE_COMMAND_EVENT_sym = scheme_intern_symbol("command");
  eventClass_wxTYPE_MOUSE_EVENT_sym = scheme_intern_symbol("mouse");
}

static int unbundle_symset_eventClass(Scheme_Object *v, const char *where) {
  if (!eventClass_wxTYPE_MOUSE_EVENT_sym) init_symset_eventClass();
  if (0) { }
  else if (v == eventClass_wxTYPE_KEY_EVENT_sym) { return wxTYPE_KEY_EVENT; }
  else if (v == eventClass_wxTYPE_COMMAND_EVENT_sym) { return wxTYPE_COMMAND_EVENT; }
  else if (v == eventClass_wxTYPE_MOUSE_EVENT_sym) { return wxTYPE_MOUSE_EVENT; }
  if (where) scheme_wrong_type(where, "eventClass symbol", -1, 0, &v);
  return 0;
}

static int istype_symset_eventClass(Scheme_Object *v, const char *where) {
  if (!eventClass_wxTYPE_MOUSE_EVENT_sym) init_symset_eventClass();
  if (0) { }
  else if (v == eventClass_wxTYPE_KEY_EVENT_sym) { return 1; }
  else if (v == eventClass_wxTYPE_COMMAND_EVENT_sym) { return 1; }
  else if (v == eventClass_wxTYPE_MOUSE_EVENT_sym) { return 1; }
  if (where) scheme_wrong_type(where, "eventClass symbol", -1, 0, &v);
  return 0;
}

static Scheme_Object *bundle_symset_eventClass(int v) {
  if (!eventClass_wxTYPE_MOUSE_EVENT_sym) init_symset_eventClass();
  switch (v) {
  case wxTYPE_KEY_EVENT: return eventClass_wxTYPE_KEY_EVENT_sym;
  case wxTYPE_COMMAND_EVENT: return eventClass_wxTYPE_COMMAND_EVENT_sym;
  case wxTYPE_MOUSE_EVENT: return eventClass_wxTYPE_MOUSE_EVENT_sym;
  default: return NULL;
  }
}




class os_wxEvent : public wxEvent {
 public:

  ~os_wxEvent();
};

Scheme_Object *os_wxEvent_class;

os_wxEvent::~os_wxEvent()
{
    objscheme_destroy(this, (Scheme_Object *)__gc_external);
}

static Scheme_Object *objscheme_wxEvent_GeteventClass(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  Scheme_Class_Object *cobj;
  int v;

  objscheme_check_valid(obj);
  if (n) scheme_wrong_count("get-event-class", 0, 0, n, p);
  cobj = (Scheme_Class_Object *)obj;
  if (cobj->primflag)
    v = ((os_wxEvent *)cobj->primdata)->wxEvent::eventClass;
  else
    v = ((wxEvent *)cobj->primdata)->eventClass;

  return bundle_symset_eventClass(v);
}

static Scheme_Object *objscheme_wxEvent_SeteventClass(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  objscheme_check_valid(obj);
  Scheme_Class_Object *cobj=(Scheme_Class_Object *)obj;
  int v;

  if (n != 1) scheme_wrong_count("set-event-class", 1, 1, n, p);

  v = unbundle_symset_eventClass(p[0], "wx:event%::event-class");
  ((wxEvent *)cobj->primdata)->eventClass = v;

  return scheme_void;
}

static Scheme_Object *objscheme_wxEvent_GeteventObject(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  Scheme_Class_Object *cobj;
  class wxObject* v;

  objscheme_check_valid(obj);
  if (n) scheme_wrong_count("get-event-object", 0, 0, n, p);
  cobj = (Scheme_Class_Object *)obj;
  if (cobj->primflag)
    v = ((os_wxEvent *)cobj->primdata)->wxEvent::eventObject;
  else
    v = ((wxEvent *)cobj->primdata)->eventObject;

  return objscheme_bundle_wxObject(v);
}

static Scheme_Object *objscheme_wxEvent_SeteventObject(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  objscheme_check_valid(obj);
  Scheme_Class_Object *cobj=(Scheme_Class_Object *)obj;
  class wxObject* v;

  if (n != 1) scheme_wrong_count("set-event-object", 1, 1, n, p);

  v = objscheme_unbundle_wxObject(p[0], "wx:event%::event-object", 1);
  ((wxEvent *)cobj->primdata)->eventObject = v;

  return scheme_void;
}

static Scheme_Object *objscheme_classname_os_wxEvent(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
 WXS_USE_ARGUMENT(obj);
  if (n) scheme_wrong_count("wx:event%" "::get-class-name", 0, 0, n, p);
  return scheme_intern_symbol("wx:event%");
}

void objscheme_setup_wxEvent(void *env)
{
if (os_wxEvent_class) {
    objscheme_add_global_class(os_wxEvent_class,  "wx:event%", env);
} else {
  os_wxEvent_class = objscheme_def_prim_class(env, "wx:event%", "wx:object%", NULL, 5);

  scheme_add_method_w_arity(os_wxEvent_class,"get-class-name",objscheme_classname_os_wxEvent, 0, 0);


  scheme_add_method_w_arity(os_wxEvent_class,"get-event-class", objscheme_wxEvent_GeteventClass, 0, 0);
  scheme_add_method_w_arity(os_wxEvent_class,"set-event-class", objscheme_wxEvent_SeteventClass, 1, 1);
  scheme_add_method_w_arity(os_wxEvent_class,"get-event-object", objscheme_wxEvent_GeteventObject, 0, 0);
  scheme_add_method_w_arity(os_wxEvent_class,"set-event-object", objscheme_wxEvent_SeteventObject, 1, 1);

  scheme_made_class(os_wxEvent_class);


}
}

int objscheme_istype_wxEvent(Scheme_Object *obj, const char *stop, int nullOK)
{
  if (nullOK && XC_SCHEME_NULLP(obj)) return 1;
  if (SAME_TYPE(SCHEME_TYPE(obj), scheme_object_type)
      && scheme_is_subclass(((Scheme_Class_Object *)obj)->sclass,          os_wxEvent_class))
    return 1;
  else {
    if (!stop)
       return 0;
    scheme_wrong_type(stop, nullOK ? "wx:event% object or " XC_NULL_STR: "wx:event% object", -1, 0, &obj);
    return 0;
  }
}

Scheme_Object *objscheme_bundle_wxEvent(class wxEvent *realobj)
{
  Scheme_Class_Object *obj;
  Scheme_Object *sobj;

  if (!realobj) return XC_SCHEME_NULL;

  if (realobj->__gc_external)
    return (Scheme_Object *)realobj->__gc_external;
  if ((sobj = objscheme_bundle_by_type(realobj, realobj->__type)))
    return sobj;
  obj = (Scheme_Class_Object *)scheme_make_uninited_object(os_wxEvent_class);

  obj->primdata = realobj;
  objscheme_register_primpointer(&obj->primdata);
  obj->primflag = 0;

  realobj->__gc_external = (void *)obj;
  objscheme_backpointer(&realobj->__gc_external);
  return (Scheme_Object *)obj;
}

class wxEvent *objscheme_unbundle_wxEvent(Scheme_Object *obj, const char *where, int nullOK)
{
  if (nullOK && XC_SCHEME_NULLP(obj)) return NULL;

  (void)objscheme_istype_wxEvent(obj, where, nullOK);
  Scheme_Class_Object *o = (Scheme_Class_Object *)obj;
  objscheme_check_valid(obj);
  if (o->primflag)
    return (os_wxEvent *)o->primdata;
  else
    return (wxEvent *)o->primdata;
}


static Scheme_Object *commandType_wxEVENT_TYPE_BUTTON_COMMAND_sym = NULL;
static Scheme_Object *commandType_wxEVENT_TYPE_CHECKBOX_COMMAND_sym = NULL;
static Scheme_Object *commandType_wxEVENT_TYPE_CHOICE_COMMAND_sym = NULL;
static Scheme_Object *commandType_wxEVENT_TYPE_LISTBOX_COMMAND_sym = NULL;
static Scheme_Object *commandType_wxEVENT_TYPE_TEXT_COMMAND_sym = NULL;
static Scheme_Object *commandType_wxEVENT_TYPE_SLIDER_COMMAND_sym = NULL;
static Scheme_Object *commandType_wxEVENT_TYPE_RADIOBOX_COMMAND_sym = NULL;
static Scheme_Object *commandType_wxEVENT_TYPE_TEXT_ENTER_COMMAND_sym = NULL;
static Scheme_Object *commandType_wxEVENT_TYPE_SET_FOCUS_sym = NULL;
static Scheme_Object *commandType_wxEVENT_TYPE_KILL_FOCUS_sym = NULL;
static Scheme_Object *commandType_wxEVENT_TYPE_SCROLL_TOP_sym = NULL;
static Scheme_Object *commandType_wxEVENT_TYPE_SCROLL_BOTTOM_sym = NULL;
static Scheme_Object *commandType_wxEVENT_TYPE_SCROLL_LINEUP_sym = NULL;
static Scheme_Object *commandType_wxEVENT_TYPE_SCROLL_LINEDOWN_sym = NULL;
static Scheme_Object *commandType_wxEVENT_TYPE_SCROLL_PAGEUP_sym = NULL;
static Scheme_Object *commandType_wxEVENT_TYPE_SCROLL_PAGEDOWN_sym = NULL;
static Scheme_Object *commandType_wxEVENT_TYPE_SCROLL_THUMBTRACK_sym = NULL;

static void init_symset_commandType(void) {
  commandType_wxEVENT_TYPE_BUTTON_COMMAND_sym = scheme_intern_symbol("button");
  commandType_wxEVENT_TYPE_CHECKBOX_COMMAND_sym = scheme_intern_symbol("check-box");
  commandType_wxEVENT_TYPE_CHOICE_COMMAND_sym = scheme_intern_symbol("choice");
  commandType_wxEVENT_TYPE_LISTBOX_COMMAND_sym = scheme_intern_symbol("list-box");
  commandType_wxEVENT_TYPE_TEXT_COMMAND_sym = scheme_intern_symbol("text");
  commandType_wxEVENT_TYPE_SLIDER_COMMAND_sym = scheme_intern_symbol("slider");
  commandType_wxEVENT_TYPE_RADIOBOX_COMMAND_sym = scheme_intern_symbol("radio-box");
  commandType_wxEVENT_TYPE_TEXT_ENTER_COMMAND_sym = scheme_intern_symbol("text-enter");
  commandType_wxEVENT_TYPE_SET_FOCUS_sym = scheme_intern_symbol("set-focus");
  commandType_wxEVENT_TYPE_KILL_FOCUS_sym = scheme_intern_symbol("kill-focus");
  commandType_wxEVENT_TYPE_SCROLL_TOP_sym = scheme_intern_symbol("scroll-top");
  commandType_wxEVENT_TYPE_SCROLL_BOTTOM_sym = scheme_intern_symbol("scroll-bottom");
  commandType_wxEVENT_TYPE_SCROLL_LINEUP_sym = scheme_intern_symbol("scroll-line-up");
  commandType_wxEVENT_TYPE_SCROLL_LINEDOWN_sym = scheme_intern_symbol("scroll-line-down");
  commandType_wxEVENT_TYPE_SCROLL_PAGEUP_sym = scheme_intern_symbol("scroll-page-up");
  commandType_wxEVENT_TYPE_SCROLL_PAGEDOWN_sym = scheme_intern_symbol("scroll-page-down");
  commandType_wxEVENT_TYPE_SCROLL_THUMBTRACK_sym = scheme_intern_symbol("scroll-thumb");
}

static int unbundle_symset_commandType(Scheme_Object *v, const char *where) {
  if (!commandType_wxEVENT_TYPE_SCROLL_THUMBTRACK_sym) init_symset_commandType();
  if (0) { }
  else if (v == commandType_wxEVENT_TYPE_BUTTON_COMMAND_sym) { return wxEVENT_TYPE_BUTTON_COMMAND; }
  else if (v == commandType_wxEVENT_TYPE_CHECKBOX_COMMAND_sym) { return wxEVENT_TYPE_CHECKBOX_COMMAND; }
  else if (v == commandType_wxEVENT_TYPE_CHOICE_COMMAND_sym) { return wxEVENT_TYPE_CHOICE_COMMAND; }
  else if (v == commandType_wxEVENT_TYPE_LISTBOX_COMMAND_sym) { return wxEVENT_TYPE_LISTBOX_COMMAND; }
  else if (v == commandType_wxEVENT_TYPE_TEXT_COMMAND_sym) { return wxEVENT_TYPE_TEXT_COMMAND; }
  else if (v == commandType_wxEVENT_TYPE_SLIDER_COMMAND_sym) { return wxEVENT_TYPE_SLIDER_COMMAND; }
  else if (v == commandType_wxEVENT_TYPE_RADIOBOX_COMMAND_sym) { return wxEVENT_TYPE_RADIOBOX_COMMAND; }
  else if (v == commandType_wxEVENT_TYPE_TEXT_ENTER_COMMAND_sym) { return wxEVENT_TYPE_TEXT_ENTER_COMMAND; }
  else if (v == commandType_wxEVENT_TYPE_SET_FOCUS_sym) { return wxEVENT_TYPE_SET_FOCUS; }
  else if (v == commandType_wxEVENT_TYPE_KILL_FOCUS_sym) { return wxEVENT_TYPE_KILL_FOCUS; }
  else if (v == commandType_wxEVENT_TYPE_SCROLL_TOP_sym) { return wxEVENT_TYPE_SCROLL_TOP; }
  else if (v == commandType_wxEVENT_TYPE_SCROLL_BOTTOM_sym) { return wxEVENT_TYPE_SCROLL_BOTTOM; }
  else if (v == commandType_wxEVENT_TYPE_SCROLL_LINEUP_sym) { return wxEVENT_TYPE_SCROLL_LINEUP; }
  else if (v == commandType_wxEVENT_TYPE_SCROLL_LINEDOWN_sym) { return wxEVENT_TYPE_SCROLL_LINEDOWN; }
  else if (v == commandType_wxEVENT_TYPE_SCROLL_PAGEUP_sym) { return wxEVENT_TYPE_SCROLL_PAGEUP; }
  else if (v == commandType_wxEVENT_TYPE_SCROLL_PAGEDOWN_sym) { return wxEVENT_TYPE_SCROLL_PAGEDOWN; }
  else if (v == commandType_wxEVENT_TYPE_SCROLL_THUMBTRACK_sym) { return wxEVENT_TYPE_SCROLL_THUMBTRACK; }
  if (where) scheme_wrong_type(where, "commandType symbol", -1, 0, &v);
  return 0;
}

static int istype_symset_commandType(Scheme_Object *v, const char *where) {
  if (!commandType_wxEVENT_TYPE_SCROLL_THUMBTRACK_sym) init_symset_commandType();
  if (0) { }
  else if (v == commandType_wxEVENT_TYPE_BUTTON_COMMAND_sym) { return 1; }
  else if (v == commandType_wxEVENT_TYPE_CHECKBOX_COMMAND_sym) { return 1; }
  else if (v == commandType_wxEVENT_TYPE_CHOICE_COMMAND_sym) { return 1; }
  else if (v == commandType_wxEVENT_TYPE_LISTBOX_COMMAND_sym) { return 1; }
  else if (v == commandType_wxEVENT_TYPE_TEXT_COMMAND_sym) { return 1; }
  else if (v == commandType_wxEVENT_TYPE_SLIDER_COMMAND_sym) { return 1; }
  else if (v == commandType_wxEVENT_TYPE_RADIOBOX_COMMAND_sym) { return 1; }
  else if (v == commandType_wxEVENT_TYPE_TEXT_ENTER_COMMAND_sym) { return 1; }
  else if (v == commandType_wxEVENT_TYPE_SET_FOCUS_sym) { return 1; }
  else if (v == commandType_wxEVENT_TYPE_KILL_FOCUS_sym) { return 1; }
  else if (v == commandType_wxEVENT_TYPE_SCROLL_TOP_sym) { return 1; }
  else if (v == commandType_wxEVENT_TYPE_SCROLL_BOTTOM_sym) { return 1; }
  else if (v == commandType_wxEVENT_TYPE_SCROLL_LINEUP_sym) { return 1; }
  else if (v == commandType_wxEVENT_TYPE_SCROLL_LINEDOWN_sym) { return 1; }
  else if (v == commandType_wxEVENT_TYPE_SCROLL_PAGEUP_sym) { return 1; }
  else if (v == commandType_wxEVENT_TYPE_SCROLL_PAGEDOWN_sym) { return 1; }
  else if (v == commandType_wxEVENT_TYPE_SCROLL_THUMBTRACK_sym) { return 1; }
  if (where) scheme_wrong_type(where, "commandType symbol", -1, 0, &v);
  return 0;
}

static Scheme_Object *bundle_symset_commandType(int v) {
  if (!commandType_wxEVENT_TYPE_SCROLL_THUMBTRACK_sym) init_symset_commandType();
  switch (v) {
  case wxEVENT_TYPE_BUTTON_COMMAND: return commandType_wxEVENT_TYPE_BUTTON_COMMAND_sym;
  case wxEVENT_TYPE_CHECKBOX_COMMAND: return commandType_wxEVENT_TYPE_CHECKBOX_COMMAND_sym;
  case wxEVENT_TYPE_CHOICE_COMMAND: return commandType_wxEVENT_TYPE_CHOICE_COMMAND_sym;
  case wxEVENT_TYPE_LISTBOX_COMMAND: return commandType_wxEVENT_TYPE_LISTBOX_COMMAND_sym;
  case wxEVENT_TYPE_TEXT_COMMAND: return commandType_wxEVENT_TYPE_TEXT_COMMAND_sym;
  case wxEVENT_TYPE_SLIDER_COMMAND: return commandType_wxEVENT_TYPE_SLIDER_COMMAND_sym;
  case wxEVENT_TYPE_RADIOBOX_COMMAND: return commandType_wxEVENT_TYPE_RADIOBOX_COMMAND_sym;
  case wxEVENT_TYPE_TEXT_ENTER_COMMAND: return commandType_wxEVENT_TYPE_TEXT_ENTER_COMMAND_sym;
  case wxEVENT_TYPE_SET_FOCUS: return commandType_wxEVENT_TYPE_SET_FOCUS_sym;
  case wxEVENT_TYPE_KILL_FOCUS: return commandType_wxEVENT_TYPE_KILL_FOCUS_sym;
  case wxEVENT_TYPE_SCROLL_TOP: return commandType_wxEVENT_TYPE_SCROLL_TOP_sym;
  case wxEVENT_TYPE_SCROLL_BOTTOM: return commandType_wxEVENT_TYPE_SCROLL_BOTTOM_sym;
  case wxEVENT_TYPE_SCROLL_LINEUP: return commandType_wxEVENT_TYPE_SCROLL_LINEUP_sym;
  case wxEVENT_TYPE_SCROLL_LINEDOWN: return commandType_wxEVENT_TYPE_SCROLL_LINEDOWN_sym;
  case wxEVENT_TYPE_SCROLL_PAGEUP: return commandType_wxEVENT_TYPE_SCROLL_PAGEUP_sym;
  case wxEVENT_TYPE_SCROLL_PAGEDOWN: return commandType_wxEVENT_TYPE_SCROLL_PAGEDOWN_sym;
  case wxEVENT_TYPE_SCROLL_THUMBTRACK: return commandType_wxEVENT_TYPE_SCROLL_THUMBTRACK_sym;
  default: return NULL;
  }
}


Bool CommandEventIsDoubleClick(wxCommandEvent *ce)
{
   return (ce->extraLong == 2);
}





// These will be removed in the next version
#define __commandInt commandInt
#define __commandString commandString
#define __extraLong extraLong

class os_wxCommandEvent : public wxCommandEvent {
 public:

  os_wxCommandEvent(Scheme_Object * obj, int x0);
  ~os_wxCommandEvent();
};

Scheme_Object *os_wxCommandEvent_class;

os_wxCommandEvent::os_wxCommandEvent(Scheme_Object * o, int x0)
: wxCommandEvent(x0)
{
  __gc_external = (void *)o;
  objscheme_backpointer(&__gc_external);
  objscheme_note_creation(o);
}

os_wxCommandEvent::~os_wxCommandEvent()
{
    objscheme_destroy(this, (Scheme_Object *)__gc_external);
}

#pragma argsused
static Scheme_Object *os_wxCommandEventCommandEventIsDoubleClick(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
 WXS_USE_ARGUMENT(n) WXS_USE_ARGUMENT(p)
  Bool r;
  objscheme_check_valid(obj);

  

  
  r = CommandEventIsDoubleClick(((wxCommandEvent *)((Scheme_Class_Object *)obj)->primdata));

  
  
  return (r ? scheme_true : scheme_false);
}

#pragma argsused
static Scheme_Object *os_wxCommandEventIsSelection(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
 WXS_USE_ARGUMENT(n) WXS_USE_ARGUMENT(p)
  Bool r;
  objscheme_check_valid(obj);

  

  
  r = ((wxCommandEvent *)((Scheme_Class_Object *)obj)->primdata)->IsSelection();

  
  
  return (r ? scheme_true : scheme_false);
}

#pragma argsused
static Scheme_Object *os_wxCommandEventChecked(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
 WXS_USE_ARGUMENT(n) WXS_USE_ARGUMENT(p)
  Bool r;
  objscheme_check_valid(obj);

  

  
  r = ((wxCommandEvent *)((Scheme_Class_Object *)obj)->primdata)->Checked();

  
  
  return (r ? scheme_true : scheme_false);
}

static Scheme_Object *objscheme_wxCommandEvent_GeteventType(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  Scheme_Class_Object *cobj;
  int v;

  objscheme_check_valid(obj);
  if (n) scheme_wrong_count("get-event-type", 0, 0, n, p);
  cobj = (Scheme_Class_Object *)obj;
  if (cobj->primflag)
    v = ((os_wxCommandEvent *)cobj->primdata)->wxCommandEvent::eventType;
  else
    v = ((wxCommandEvent *)cobj->primdata)->eventType;

  return bundle_symset_commandType(v);
}

static Scheme_Object *objscheme_wxCommandEvent_SeteventType(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  objscheme_check_valid(obj);
  Scheme_Class_Object *cobj=(Scheme_Class_Object *)obj;
  int v;

  if (n != 1) scheme_wrong_count("set-event-type", 1, 1, n, p);

  v = unbundle_symset_commandType(p[0], "wx:command-event%::event-type");
  ((wxCommandEvent *)cobj->primdata)->eventType = v;

  return scheme_void;
}

static Scheme_Object *objscheme_wxCommandEvent_GetextraLong(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  Scheme_Class_Object *cobj;
  long v;

  objscheme_check_valid(obj);
  if (n) scheme_wrong_count("get-selection-type", 0, 0, n, p);
  cobj = (Scheme_Class_Object *)obj;
  if (cobj->primflag)
    v = ((os_wxCommandEvent *)cobj->primdata)->wxCommandEvent::extraLong;
  else
    v = ((wxCommandEvent *)cobj->primdata)->extraLong;

  return scheme_make_integer(v);
}

static Scheme_Object *objscheme_wxCommandEvent_SetextraLong(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  objscheme_check_valid(obj);
  Scheme_Class_Object *cobj=(Scheme_Class_Object *)obj;
  long v;

  if (n != 1) scheme_wrong_count("set-selection-type", 1, 1, n, p);

  v = objscheme_unbundle_integer(p[0], "wx:command-event%::selection-type");
  ((wxCommandEvent *)cobj->primdata)->extraLong = v;

  return scheme_void;
}

static Scheme_Object *objscheme_wxCommandEvent_GetcommandInt(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  Scheme_Class_Object *cobj;
  int v;

  objscheme_check_valid(obj);
  if (n) scheme_wrong_count("get-selection", 0, 0, n, p);
  cobj = (Scheme_Class_Object *)obj;
  if (cobj->primflag)
    v = ((os_wxCommandEvent *)cobj->primdata)->wxCommandEvent::commandInt;
  else
    v = ((wxCommandEvent *)cobj->primdata)->commandInt;

  return scheme_make_integer(v);
}

static Scheme_Object *objscheme_wxCommandEvent_SetcommandInt(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  objscheme_check_valid(obj);
  Scheme_Class_Object *cobj=(Scheme_Class_Object *)obj;
  int v;

  if (n != 1) scheme_wrong_count("set-selection", 1, 1, n, p);

  v = objscheme_unbundle_integer(p[0], "wx:command-event%::selection");
  ((wxCommandEvent *)cobj->primdata)->commandInt = v;

  return scheme_void;
}

static Scheme_Object *objscheme_wxCommandEvent_GetcommandString(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  Scheme_Class_Object *cobj;
  nstring v;

  objscheme_check_valid(obj);
  if (n) scheme_wrong_count("get-string", 0, 0, n, p);
  cobj = (Scheme_Class_Object *)obj;
  if (cobj->primflag)
    v = ((os_wxCommandEvent *)cobj->primdata)->wxCommandEvent::commandString;
  else
    v = ((wxCommandEvent *)cobj->primdata)->commandString;

  return objscheme_bundle_string((char *)v);
}

static Scheme_Object *objscheme_wxCommandEvent_SetcommandString(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  objscheme_check_valid(obj);
  Scheme_Class_Object *cobj=(Scheme_Class_Object *)obj;
  nstring v;

  if (n != 1) scheme_wrong_count("set-string", 1, 1, n, p);

  v = (nstring)objscheme_unbundle_nullable_string(p[0], "wx:command-event%::string");
  ((wxCommandEvent *)cobj->primdata)->commandString = v;

  return scheme_void;
}

static Scheme_Object *objscheme_wxCommandEvent_Get__commandInt(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  Scheme_Class_Object *cobj;
  int v;

  objscheme_check_valid(obj);
  if (n) scheme_wrong_count("get-command-int", 0, 0, n, p);
  cobj = (Scheme_Class_Object *)obj;
  if (cobj->primflag)
    v = ((os_wxCommandEvent *)cobj->primdata)->wxCommandEvent::__commandInt;
  else
    v = ((wxCommandEvent *)cobj->primdata)->__commandInt;

  return scheme_make_integer(v);
}

static Scheme_Object *objscheme_wxCommandEvent_Set__commandInt(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  objscheme_check_valid(obj);
  Scheme_Class_Object *cobj=(Scheme_Class_Object *)obj;
  int v;

  if (n != 1) scheme_wrong_count("set-command-int", 1, 1, n, p);

  v = objscheme_unbundle_integer(p[0], "wx:command-event%::command-int");
  ((wxCommandEvent *)cobj->primdata)->__commandInt = v;

  return scheme_void;
}

static Scheme_Object *objscheme_wxCommandEvent_Get__commandString(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  Scheme_Class_Object *cobj;
  nstring v;

  objscheme_check_valid(obj);
  if (n) scheme_wrong_count("get-command-string", 0, 0, n, p);
  cobj = (Scheme_Class_Object *)obj;
  if (cobj->primflag)
    v = ((os_wxCommandEvent *)cobj->primdata)->wxCommandEvent::__commandString;
  else
    v = ((wxCommandEvent *)cobj->primdata)->__commandString;

  return objscheme_bundle_string((char *)v);
}

static Scheme_Object *objscheme_wxCommandEvent_Set__commandString(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  objscheme_check_valid(obj);
  Scheme_Class_Object *cobj=(Scheme_Class_Object *)obj;
  nstring v;

  if (n != 1) scheme_wrong_count("set-command-string", 1, 1, n, p);

  v = (nstring)objscheme_unbundle_nullable_string(p[0], "wx:command-event%::command-string");
  ((wxCommandEvent *)cobj->primdata)->__commandString = v;

  return scheme_void;
}

static Scheme_Object *objscheme_wxCommandEvent_Get__extraLong(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  Scheme_Class_Object *cobj;
  long v;

  objscheme_check_valid(obj);
  if (n) scheme_wrong_count("get-extra-long", 0, 0, n, p);
  cobj = (Scheme_Class_Object *)obj;
  if (cobj->primflag)
    v = ((os_wxCommandEvent *)cobj->primdata)->wxCommandEvent::__extraLong;
  else
    v = ((wxCommandEvent *)cobj->primdata)->__extraLong;

  return scheme_make_integer(v);
}

static Scheme_Object *objscheme_wxCommandEvent_Set__extraLong(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  objscheme_check_valid(obj);
  Scheme_Class_Object *cobj=(Scheme_Class_Object *)obj;
  long v;

  if (n != 1) scheme_wrong_count("set-extra-long", 1, 1, n, p);

  v = objscheme_unbundle_integer(p[0], "wx:command-event%::extra-long");
  ((wxCommandEvent *)cobj->primdata)->__extraLong = v;

  return scheme_void;
}

#pragma argsused
static Scheme_Object *os_wxCommandEvent_ConstructScheme(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  os_wxCommandEvent *realobj;
  int x0;

  
  if (n != 1) 
    scheme_wrong_count("wx:command-event%::initialization", 1, 1, n, p);
  x0 = objscheme_unbundle_integer(p[0], "wx:command-event%::initialization");

  
  realobj = new os_wxCommandEvent(obj, x0);
  
  
  ((Scheme_Class_Object *)obj)->primdata = realobj;
  objscheme_register_primpointer(&((Scheme_Class_Object *)obj)->primdata);
  ((Scheme_Class_Object *)obj)->primflag = 1;
  return obj;
}

static Scheme_Object *objscheme_classname_os_wxCommandEvent(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
 WXS_USE_ARGUMENT(obj);
  if (n) scheme_wrong_count("wx:command-event%" "::get-class-name", 0, 0, n, p);
  return scheme_intern_symbol("wx:command-event%");
}

void objscheme_setup_wxCommandEvent(void *env)
{
if (os_wxCommandEvent_class) {
    objscheme_add_global_class(os_wxCommandEvent_class,  "wx:command-event%", env);
} else {
  os_wxCommandEvent_class = objscheme_def_prim_class(env, "wx:command-event%", "wx:event%", os_wxCommandEvent_ConstructScheme, 18);

  scheme_add_method_w_arity(os_wxCommandEvent_class,"get-class-name",objscheme_classname_os_wxCommandEvent, 0, 0);

 scheme_add_method_w_arity(os_wxCommandEvent_class, "is-double-click?", os_wxCommandEventCommandEventIsDoubleClick, 0, 0);
 scheme_add_method_w_arity(os_wxCommandEvent_class, "is-selection?", os_wxCommandEventIsSelection, 0, 0);
 scheme_add_method_w_arity(os_wxCommandEvent_class, "checked?", os_wxCommandEventChecked, 0, 0);

  scheme_add_method_w_arity(os_wxCommandEvent_class,"get-event-type", objscheme_wxCommandEvent_GeteventType, 0, 0);
  scheme_add_method_w_arity(os_wxCommandEvent_class,"set-event-type", objscheme_wxCommandEvent_SeteventType, 1, 1);
  scheme_add_method_w_arity(os_wxCommandEvent_class,"get-selection-type", objscheme_wxCommandEvent_GetextraLong, 0, 0);
  scheme_add_method_w_arity(os_wxCommandEvent_class,"set-selection-type", objscheme_wxCommandEvent_SetextraLong, 1, 1);
  scheme_add_method_w_arity(os_wxCommandEvent_class,"get-selection", objscheme_wxCommandEvent_GetcommandInt, 0, 0);
  scheme_add_method_w_arity(os_wxCommandEvent_class,"set-selection", objscheme_wxCommandEvent_SetcommandInt, 1, 1);
  scheme_add_method_w_arity(os_wxCommandEvent_class,"get-string", objscheme_wxCommandEvent_GetcommandString, 0, 0);
  scheme_add_method_w_arity(os_wxCommandEvent_class,"set-string", objscheme_wxCommandEvent_SetcommandString, 1, 1);
  scheme_add_method_w_arity(os_wxCommandEvent_class,"get-command-int", objscheme_wxCommandEvent_Get__commandInt, 0, 0);
  scheme_add_method_w_arity(os_wxCommandEvent_class,"set-command-int", objscheme_wxCommandEvent_Set__commandInt, 1, 1);
  scheme_add_method_w_arity(os_wxCommandEvent_class,"get-command-string", objscheme_wxCommandEvent_Get__commandString, 0, 0);
  scheme_add_method_w_arity(os_wxCommandEvent_class,"set-command-string", objscheme_wxCommandEvent_Set__commandString, 1, 1);
  scheme_add_method_w_arity(os_wxCommandEvent_class,"get-extra-long", objscheme_wxCommandEvent_Get__extraLong, 0, 0);
  scheme_add_method_w_arity(os_wxCommandEvent_class,"set-extra-long", objscheme_wxCommandEvent_Set__extraLong, 1, 1);

  scheme_made_class(os_wxCommandEvent_class);


}
}

int objscheme_istype_wxCommandEvent(Scheme_Object *obj, const char *stop, int nullOK)
{
  if (nullOK && XC_SCHEME_NULLP(obj)) return 1;
  if (SAME_TYPE(SCHEME_TYPE(obj), scheme_object_type)
      && scheme_is_subclass(((Scheme_Class_Object *)obj)->sclass,          os_wxCommandEvent_class))
    return 1;
  else {
    if (!stop)
       return 0;
    scheme_wrong_type(stop, nullOK ? "wx:command-event% object or " XC_NULL_STR: "wx:command-event% object", -1, 0, &obj);
    return 0;
  }
}

Scheme_Object *objscheme_bundle_wxCommandEvent(class wxCommandEvent *realobj)
{
  Scheme_Class_Object *obj;
  Scheme_Object *sobj;

  if (!realobj) return XC_SCHEME_NULL;

  if (realobj->__gc_external)
    return (Scheme_Object *)realobj->__gc_external;
  if ((sobj = objscheme_bundle_by_type(realobj, realobj->__type)))
    return sobj;
  obj = (Scheme_Class_Object *)scheme_make_uninited_object(os_wxCommandEvent_class);

  obj->primdata = realobj;
  objscheme_register_primpointer(&obj->primdata);
  obj->primflag = 0;

  realobj->__gc_external = (void *)obj;
  objscheme_backpointer(&realobj->__gc_external);
  return (Scheme_Object *)obj;
}

class wxCommandEvent *objscheme_unbundle_wxCommandEvent(Scheme_Object *obj, const char *where, int nullOK)
{
  if (nullOK && XC_SCHEME_NULLP(obj)) return NULL;

  (void)objscheme_istype_wxCommandEvent(obj, where, nullOK);
  Scheme_Class_Object *o = (Scheme_Class_Object *)obj;
  objscheme_check_valid(obj);
  if (o->primflag)
    return (os_wxCommandEvent *)o->primdata;
  else
    return (wxCommandEvent *)o->primdata;
}


static Scheme_Object *keyCode_WXK_ESCAPE_sym = NULL;
static Scheme_Object *keyCode_WXK_START_sym = NULL;
static Scheme_Object *keyCode_WXK_LBUTTON_sym = NULL;
static Scheme_Object *keyCode_WXK_RBUTTON_sym = NULL;
static Scheme_Object *keyCode_WXK_CANCEL_sym = NULL;
static Scheme_Object *keyCode_WXK_MBUTTON_sym = NULL;
static Scheme_Object *keyCode_WXK_CLEAR_sym = NULL;
static Scheme_Object *keyCode_WXK_SHIFT_sym = NULL;
static Scheme_Object *keyCode_WXK_CONTROL_sym = NULL;
static Scheme_Object *keyCode_WXK_MENU_sym = NULL;
static Scheme_Object *keyCode_WXK_PAUSE_sym = NULL;
static Scheme_Object *keyCode_WXK_CAPITAL_sym = NULL;
static Scheme_Object *keyCode_WXK_PRIOR_sym = NULL;
static Scheme_Object *keyCode_WXK_NEXT_sym = NULL;
static Scheme_Object *keyCode_WXK_END_sym = NULL;
static Scheme_Object *keyCode_WXK_HOME_sym = NULL;
static Scheme_Object *keyCode_WXK_LEFT_sym = NULL;
static Scheme_Object *keyCode_WXK_UP_sym = NULL;
static Scheme_Object *keyCode_WXK_RIGHT_sym = NULL;
static Scheme_Object *keyCode_WXK_DOWN_sym = NULL;
static Scheme_Object *keyCode_WXK_SELECT_sym = NULL;
static Scheme_Object *keyCode_WXK_PRINT_sym = NULL;
static Scheme_Object *keyCode_WXK_EXECUTE_sym = NULL;
static Scheme_Object *keyCode_WXK_SNAPSHOT_sym = NULL;
static Scheme_Object *keyCode_WXK_INSERT_sym = NULL;
static Scheme_Object *keyCode_WXK_HELP_sym = NULL;
static Scheme_Object *keyCode_WXK_NUMPAD0_sym = NULL;
static Scheme_Object *keyCode_WXK_NUMPAD1_sym = NULL;
static Scheme_Object *keyCode_WXK_NUMPAD2_sym = NULL;
static Scheme_Object *keyCode_WXK_NUMPAD3_sym = NULL;
static Scheme_Object *keyCode_WXK_NUMPAD4_sym = NULL;
static Scheme_Object *keyCode_WXK_NUMPAD5_sym = NULL;
static Scheme_Object *keyCode_WXK_NUMPAD6_sym = NULL;
static Scheme_Object *keyCode_WXK_NUMPAD7_sym = NULL;
static Scheme_Object *keyCode_WXK_NUMPAD8_sym = NULL;
static Scheme_Object *keyCode_WXK_NUMPAD9_sym = NULL;
static Scheme_Object *keyCode_WXK_MULTIPLY_sym = NULL;
static Scheme_Object *keyCode_WXK_ADD_sym = NULL;
static Scheme_Object *keyCode_WXK_SEPARATOR_sym = NULL;
static Scheme_Object *keyCode_WXK_SUBTRACT_sym = NULL;
static Scheme_Object *keyCode_WXK_DECIMAL_sym = NULL;
static Scheme_Object *keyCode_WXK_DIVIDE_sym = NULL;
static Scheme_Object *keyCode_WXK_F1_sym = NULL;
static Scheme_Object *keyCode_WXK_F2_sym = NULL;
static Scheme_Object *keyCode_WXK_F3_sym = NULL;
static Scheme_Object *keyCode_WXK_F4_sym = NULL;
static Scheme_Object *keyCode_WXK_F5_sym = NULL;
static Scheme_Object *keyCode_WXK_F6_sym = NULL;
static Scheme_Object *keyCode_WXK_F7_sym = NULL;
static Scheme_Object *keyCode_WXK_F8_sym = NULL;
static Scheme_Object *keyCode_WXK_F9_sym = NULL;
static Scheme_Object *keyCode_WXK_F10_sym = NULL;
static Scheme_Object *keyCode_WXK_F11_sym = NULL;
static Scheme_Object *keyCode_WXK_F12_sym = NULL;
static Scheme_Object *keyCode_WXK_F13_sym = NULL;
static Scheme_Object *keyCode_WXK_F14_sym = NULL;
static Scheme_Object *keyCode_WXK_F15_sym = NULL;
static Scheme_Object *keyCode_WXK_F16_sym = NULL;
static Scheme_Object *keyCode_WXK_F17_sym = NULL;
static Scheme_Object *keyCode_WXK_F18_sym = NULL;
static Scheme_Object *keyCode_WXK_F19_sym = NULL;
static Scheme_Object *keyCode_WXK_F20_sym = NULL;
static Scheme_Object *keyCode_WXK_F21_sym = NULL;
static Scheme_Object *keyCode_WXK_F22_sym = NULL;
static Scheme_Object *keyCode_WXK_F23_sym = NULL;
static Scheme_Object *keyCode_WXK_F24_sym = NULL;
static Scheme_Object *keyCode_WXK_NUMLOCK_sym = NULL;
static Scheme_Object *keyCode_WXK_SCROLL_sym = NULL;

static void init_symset_keyCode(void) {
  keyCode_WXK_ESCAPE_sym = scheme_intern_symbol("escape");
  keyCode_WXK_START_sym = scheme_intern_symbol("start");
  keyCode_WXK_LBUTTON_sym = scheme_intern_symbol("lbutton");
  keyCode_WXK_RBUTTON_sym = scheme_intern_symbol("rbutton");
  keyCode_WXK_CANCEL_sym = scheme_intern_symbol("cancel");
  keyCode_WXK_MBUTTON_sym = scheme_intern_symbol("mbutton");
  keyCode_WXK_CLEAR_sym = scheme_intern_symbol("clear");
  keyCode_WXK_SHIFT_sym = scheme_intern_symbol("shift");
  keyCode_WXK_CONTROL_sym = scheme_intern_symbol("control");
  keyCode_WXK_MENU_sym = scheme_intern_symbol("menu");
  keyCode_WXK_PAUSE_sym = scheme_intern_symbol("pause");
  keyCode_WXK_CAPITAL_sym = scheme_intern_symbol("capital");
  keyCode_WXK_PRIOR_sym = scheme_intern_symbol("prior");
  keyCode_WXK_NEXT_sym = scheme_intern_symbol("next");
  keyCode_WXK_END_sym = scheme_intern_symbol("end");
  keyCode_WXK_HOME_sym = scheme_intern_symbol("home");
  keyCode_WXK_LEFT_sym = scheme_intern_symbol("left");
  keyCode_WXK_UP_sym = scheme_intern_symbol("up");
  keyCode_WXK_RIGHT_sym = scheme_intern_symbol("right");
  keyCode_WXK_DOWN_sym = scheme_intern_symbol("down");
  keyCode_WXK_SELECT_sym = scheme_intern_symbol("select");
  keyCode_WXK_PRINT_sym = scheme_intern_symbol("print");
  keyCode_WXK_EXECUTE_sym = scheme_intern_symbol("execute");
  keyCode_WXK_SNAPSHOT_sym = scheme_intern_symbol("snapshot");
  keyCode_WXK_INSERT_sym = scheme_intern_symbol("insert");
  keyCode_WXK_HELP_sym = scheme_intern_symbol("help");
  keyCode_WXK_NUMPAD0_sym = scheme_intern_symbol("numpad0");
  keyCode_WXK_NUMPAD1_sym = scheme_intern_symbol("numpad1");
  keyCode_WXK_NUMPAD2_sym = scheme_intern_symbol("numpad2");
  keyCode_WXK_NUMPAD3_sym = scheme_intern_symbol("numpad3");
  keyCode_WXK_NUMPAD4_sym = scheme_intern_symbol("numpad4");
  keyCode_WXK_NUMPAD5_sym = scheme_intern_symbol("numpad5");
  keyCode_WXK_NUMPAD6_sym = scheme_intern_symbol("numpad6");
  keyCode_WXK_NUMPAD7_sym = scheme_intern_symbol("numpad7");
  keyCode_WXK_NUMPAD8_sym = scheme_intern_symbol("numpad8");
  keyCode_WXK_NUMPAD9_sym = scheme_intern_symbol("numpad9");
  keyCode_WXK_MULTIPLY_sym = scheme_intern_symbol("multiply");
  keyCode_WXK_ADD_sym = scheme_intern_symbol("add");
  keyCode_WXK_SEPARATOR_sym = scheme_intern_symbol("separator");
  keyCode_WXK_SUBTRACT_sym = scheme_intern_symbol("subtract");
  keyCode_WXK_DECIMAL_sym = scheme_intern_symbol("decimal");
  keyCode_WXK_DIVIDE_sym = scheme_intern_symbol("divide");
  keyCode_WXK_F1_sym = scheme_intern_symbol("f1");
  keyCode_WXK_F2_sym = scheme_intern_symbol("f2");
  keyCode_WXK_F3_sym = scheme_intern_symbol("f3");
  keyCode_WXK_F4_sym = scheme_intern_symbol("f4");
  keyCode_WXK_F5_sym = scheme_intern_symbol("f5");
  keyCode_WXK_F6_sym = scheme_intern_symbol("f6");
  keyCode_WXK_F7_sym = scheme_intern_symbol("f7");
  keyCode_WXK_F8_sym = scheme_intern_symbol("f8");
  keyCode_WXK_F9_sym = scheme_intern_symbol("f9");
  keyCode_WXK_F10_sym = scheme_intern_symbol("f10");
  keyCode_WXK_F11_sym = scheme_intern_symbol("f11");
  keyCode_WXK_F12_sym = scheme_intern_symbol("f12");
  keyCode_WXK_F13_sym = scheme_intern_symbol("f13");
  keyCode_WXK_F14_sym = scheme_intern_symbol("f14");
  keyCode_WXK_F15_sym = scheme_intern_symbol("f15");
  keyCode_WXK_F16_sym = scheme_intern_symbol("f16");
  keyCode_WXK_F17_sym = scheme_intern_symbol("f17");
  keyCode_WXK_F18_sym = scheme_intern_symbol("f18");
  keyCode_WXK_F19_sym = scheme_intern_symbol("f19");
  keyCode_WXK_F20_sym = scheme_intern_symbol("f20");
  keyCode_WXK_F21_sym = scheme_intern_symbol("f21");
  keyCode_WXK_F22_sym = scheme_intern_symbol("f22");
  keyCode_WXK_F23_sym = scheme_intern_symbol("f23");
  keyCode_WXK_F24_sym = scheme_intern_symbol("f24");
  keyCode_WXK_NUMLOCK_sym = scheme_intern_symbol("numlock");
  keyCode_WXK_SCROLL_sym = scheme_intern_symbol("scroll");
}

static int unbundle_symset_keyCode(Scheme_Object *v, const char *where) {
  if (!keyCode_WXK_SCROLL_sym) init_symset_keyCode();
  if (0) { }
  else if (SCHEME_CHARP(v)) { return SCHEME_CHAR_VAL(v); }
  else if (v == keyCode_WXK_ESCAPE_sym) { return WXK_ESCAPE; }
  else if (v == keyCode_WXK_START_sym) { return WXK_START; }
  else if (v == keyCode_WXK_LBUTTON_sym) { return WXK_LBUTTON; }
  else if (v == keyCode_WXK_RBUTTON_sym) { return WXK_RBUTTON; }
  else if (v == keyCode_WXK_CANCEL_sym) { return WXK_CANCEL; }
  else if (v == keyCode_WXK_MBUTTON_sym) { return WXK_MBUTTON; }
  else if (v == keyCode_WXK_CLEAR_sym) { return WXK_CLEAR; }
  else if (v == keyCode_WXK_SHIFT_sym) { return WXK_SHIFT; }
  else if (v == keyCode_WXK_CONTROL_sym) { return WXK_CONTROL; }
  else if (v == keyCode_WXK_MENU_sym) { return WXK_MENU; }
  else if (v == keyCode_WXK_PAUSE_sym) { return WXK_PAUSE; }
  else if (v == keyCode_WXK_CAPITAL_sym) { return WXK_CAPITAL; }
  else if (v == keyCode_WXK_PRIOR_sym) { return WXK_PRIOR; }
  else if (v == keyCode_WXK_NEXT_sym) { return WXK_NEXT; }
  else if (v == keyCode_WXK_END_sym) { return WXK_END; }
  else if (v == keyCode_WXK_HOME_sym) { return WXK_HOME; }
  else if (v == keyCode_WXK_LEFT_sym) { return WXK_LEFT; }
  else if (v == keyCode_WXK_UP_sym) { return WXK_UP; }
  else if (v == keyCode_WXK_RIGHT_sym) { return WXK_RIGHT; }
  else if (v == keyCode_WXK_DOWN_sym) { return WXK_DOWN; }
  else if (v == keyCode_WXK_SELECT_sym) { return WXK_SELECT; }
  else if (v == keyCode_WXK_PRINT_sym) { return WXK_PRINT; }
  else if (v == keyCode_WXK_EXECUTE_sym) { return WXK_EXECUTE; }
  else if (v == keyCode_WXK_SNAPSHOT_sym) { return WXK_SNAPSHOT; }
  else if (v == keyCode_WXK_INSERT_sym) { return WXK_INSERT; }
  else if (v == keyCode_WXK_HELP_sym) { return WXK_HELP; }
  else if (v == keyCode_WXK_NUMPAD0_sym) { return WXK_NUMPAD0; }
  else if (v == keyCode_WXK_NUMPAD1_sym) { return WXK_NUMPAD1; }
  else if (v == keyCode_WXK_NUMPAD2_sym) { return WXK_NUMPAD2; }
  else if (v == keyCode_WXK_NUMPAD3_sym) { return WXK_NUMPAD3; }
  else if (v == keyCode_WXK_NUMPAD4_sym) { return WXK_NUMPAD4; }
  else if (v == keyCode_WXK_NUMPAD5_sym) { return WXK_NUMPAD5; }
  else if (v == keyCode_WXK_NUMPAD6_sym) { return WXK_NUMPAD6; }
  else if (v == keyCode_WXK_NUMPAD7_sym) { return WXK_NUMPAD7; }
  else if (v == keyCode_WXK_NUMPAD8_sym) { return WXK_NUMPAD8; }
  else if (v == keyCode_WXK_NUMPAD9_sym) { return WXK_NUMPAD9; }
  else if (v == keyCode_WXK_MULTIPLY_sym) { return WXK_MULTIPLY; }
  else if (v == keyCode_WXK_ADD_sym) { return WXK_ADD; }
  else if (v == keyCode_WXK_SEPARATOR_sym) { return WXK_SEPARATOR; }
  else if (v == keyCode_WXK_SUBTRACT_sym) { return WXK_SUBTRACT; }
  else if (v == keyCode_WXK_DECIMAL_sym) { return WXK_DECIMAL; }
  else if (v == keyCode_WXK_DIVIDE_sym) { return WXK_DIVIDE; }
  else if (v == keyCode_WXK_F1_sym) { return WXK_F1; }
  else if (v == keyCode_WXK_F2_sym) { return WXK_F2; }
  else if (v == keyCode_WXK_F3_sym) { return WXK_F3; }
  else if (v == keyCode_WXK_F4_sym) { return WXK_F4; }
  else if (v == keyCode_WXK_F5_sym) { return WXK_F5; }
  else if (v == keyCode_WXK_F6_sym) { return WXK_F6; }
  else if (v == keyCode_WXK_F7_sym) { return WXK_F7; }
  else if (v == keyCode_WXK_F8_sym) { return WXK_F8; }
  else if (v == keyCode_WXK_F9_sym) { return WXK_F9; }
  else if (v == keyCode_WXK_F10_sym) { return WXK_F10; }
  else if (v == keyCode_WXK_F11_sym) { return WXK_F11; }
  else if (v == keyCode_WXK_F12_sym) { return WXK_F12; }
  else if (v == keyCode_WXK_F13_sym) { return WXK_F13; }
  else if (v == keyCode_WXK_F14_sym) { return WXK_F14; }
  else if (v == keyCode_WXK_F15_sym) { return WXK_F15; }
  else if (v == keyCode_WXK_F16_sym) { return WXK_F16; }
  else if (v == keyCode_WXK_F17_sym) { return WXK_F17; }
  else if (v == keyCode_WXK_F18_sym) { return WXK_F18; }
  else if (v == keyCode_WXK_F19_sym) { return WXK_F19; }
  else if (v == keyCode_WXK_F20_sym) { return WXK_F20; }
  else if (v == keyCode_WXK_F21_sym) { return WXK_F21; }
  else if (v == keyCode_WXK_F22_sym) { return WXK_F22; }
  else if (v == keyCode_WXK_F23_sym) { return WXK_F23; }
  else if (v == keyCode_WXK_F24_sym) { return WXK_F24; }
  else if (v == keyCode_WXK_NUMLOCK_sym) { return WXK_NUMLOCK; }
  else if (v == keyCode_WXK_SCROLL_sym) { return WXK_SCROLL; }
  if (where) scheme_wrong_type(where, "keyCode symbol", -1, 0, &v);
  return 0;
}

static int istype_symset_keyCode(Scheme_Object *v, const char *where) {
  if (!keyCode_WXK_SCROLL_sym) init_symset_keyCode();
  if (0) { }
  else if (SCHEME_CHARP(v)) { return 1; }
  else if (v == keyCode_WXK_ESCAPE_sym) { return 1; }
  else if (v == keyCode_WXK_START_sym) { return 1; }
  else if (v == keyCode_WXK_LBUTTON_sym) { return 1; }
  else if (v == keyCode_WXK_RBUTTON_sym) { return 1; }
  else if (v == keyCode_WXK_CANCEL_sym) { return 1; }
  else if (v == keyCode_WXK_MBUTTON_sym) { return 1; }
  else if (v == keyCode_WXK_CLEAR_sym) { return 1; }
  else if (v == keyCode_WXK_SHIFT_sym) { return 1; }
  else if (v == keyCode_WXK_CONTROL_sym) { return 1; }
  else if (v == keyCode_WXK_MENU_sym) { return 1; }
  else if (v == keyCode_WXK_PAUSE_sym) { return 1; }
  else if (v == keyCode_WXK_CAPITAL_sym) { return 1; }
  else if (v == keyCode_WXK_PRIOR_sym) { return 1; }
  else if (v == keyCode_WXK_NEXT_sym) { return 1; }
  else if (v == keyCode_WXK_END_sym) { return 1; }
  else if (v == keyCode_WXK_HOME_sym) { return 1; }
  else if (v == keyCode_WXK_LEFT_sym) { return 1; }
  else if (v == keyCode_WXK_UP_sym) { return 1; }
  else if (v == keyCode_WXK_RIGHT_sym) { return 1; }
  else if (v == keyCode_WXK_DOWN_sym) { return 1; }
  else if (v == keyCode_WXK_SELECT_sym) { return 1; }
  else if (v == keyCode_WXK_PRINT_sym) { return 1; }
  else if (v == keyCode_WXK_EXECUTE_sym) { return 1; }
  else if (v == keyCode_WXK_SNAPSHOT_sym) { return 1; }
  else if (v == keyCode_WXK_INSERT_sym) { return 1; }
  else if (v == keyCode_WXK_HELP_sym) { return 1; }
  else if (v == keyCode_WXK_NUMPAD0_sym) { return 1; }
  else if (v == keyCode_WXK_NUMPAD1_sym) { return 1; }
  else if (v == keyCode_WXK_NUMPAD2_sym) { return 1; }
  else if (v == keyCode_WXK_NUMPAD3_sym) { return 1; }
  else if (v == keyCode_WXK_NUMPAD4_sym) { return 1; }
  else if (v == keyCode_WXK_NUMPAD5_sym) { return 1; }
  else if (v == keyCode_WXK_NUMPAD6_sym) { return 1; }
  else if (v == keyCode_WXK_NUMPAD7_sym) { return 1; }
  else if (v == keyCode_WXK_NUMPAD8_sym) { return 1; }
  else if (v == keyCode_WXK_NUMPAD9_sym) { return 1; }
  else if (v == keyCode_WXK_MULTIPLY_sym) { return 1; }
  else if (v == keyCode_WXK_ADD_sym) { return 1; }
  else if (v == keyCode_WXK_SEPARATOR_sym) { return 1; }
  else if (v == keyCode_WXK_SUBTRACT_sym) { return 1; }
  else if (v == keyCode_WXK_DECIMAL_sym) { return 1; }
  else if (v == keyCode_WXK_DIVIDE_sym) { return 1; }
  else if (v == keyCode_WXK_F1_sym) { return 1; }
  else if (v == keyCode_WXK_F2_sym) { return 1; }
  else if (v == keyCode_WXK_F3_sym) { return 1; }
  else if (v == keyCode_WXK_F4_sym) { return 1; }
  else if (v == keyCode_WXK_F5_sym) { return 1; }
  else if (v == keyCode_WXK_F6_sym) { return 1; }
  else if (v == keyCode_WXK_F7_sym) { return 1; }
  else if (v == keyCode_WXK_F8_sym) { return 1; }
  else if (v == keyCode_WXK_F9_sym) { return 1; }
  else if (v == keyCode_WXK_F10_sym) { return 1; }
  else if (v == keyCode_WXK_F11_sym) { return 1; }
  else if (v == keyCode_WXK_F12_sym) { return 1; }
  else if (v == keyCode_WXK_F13_sym) { return 1; }
  else if (v == keyCode_WXK_F14_sym) { return 1; }
  else if (v == keyCode_WXK_F15_sym) { return 1; }
  else if (v == keyCode_WXK_F16_sym) { return 1; }
  else if (v == keyCode_WXK_F17_sym) { return 1; }
  else if (v == keyCode_WXK_F18_sym) { return 1; }
  else if (v == keyCode_WXK_F19_sym) { return 1; }
  else if (v == keyCode_WXK_F20_sym) { return 1; }
  else if (v == keyCode_WXK_F21_sym) { return 1; }
  else if (v == keyCode_WXK_F22_sym) { return 1; }
  else if (v == keyCode_WXK_F23_sym) { return 1; }
  else if (v == keyCode_WXK_F24_sym) { return 1; }
  else if (v == keyCode_WXK_NUMLOCK_sym) { return 1; }
  else if (v == keyCode_WXK_SCROLL_sym) { return 1; }
  if (where) scheme_wrong_type(where, "keyCode symbol", -1, 0, &v);
  return 0;
}

static Scheme_Object *bundle_symset_keyCode(int v) {
  if (!keyCode_WXK_SCROLL_sym) init_symset_keyCode();
  switch (v) {
  case WXK_ESCAPE: return keyCode_WXK_ESCAPE_sym;
  case WXK_START: return keyCode_WXK_START_sym;
  case WXK_LBUTTON: return keyCode_WXK_LBUTTON_sym;
  case WXK_RBUTTON: return keyCode_WXK_RBUTTON_sym;
  case WXK_CANCEL: return keyCode_WXK_CANCEL_sym;
  case WXK_MBUTTON: return keyCode_WXK_MBUTTON_sym;
  case WXK_CLEAR: return keyCode_WXK_CLEAR_sym;
  case WXK_SHIFT: return keyCode_WXK_SHIFT_sym;
  case WXK_CONTROL: return keyCode_WXK_CONTROL_sym;
  case WXK_MENU: return keyCode_WXK_MENU_sym;
  case WXK_PAUSE: return keyCode_WXK_PAUSE_sym;
  case WXK_CAPITAL: return keyCode_WXK_CAPITAL_sym;
  case WXK_PRIOR: return keyCode_WXK_PRIOR_sym;
  case WXK_NEXT: return keyCode_WXK_NEXT_sym;
  case WXK_END: return keyCode_WXK_END_sym;
  case WXK_HOME: return keyCode_WXK_HOME_sym;
  case WXK_LEFT: return keyCode_WXK_LEFT_sym;
  case WXK_UP: return keyCode_WXK_UP_sym;
  case WXK_RIGHT: return keyCode_WXK_RIGHT_sym;
  case WXK_DOWN: return keyCode_WXK_DOWN_sym;
  case WXK_SELECT: return keyCode_WXK_SELECT_sym;
  case WXK_PRINT: return keyCode_WXK_PRINT_sym;
  case WXK_EXECUTE: return keyCode_WXK_EXECUTE_sym;
  case WXK_SNAPSHOT: return keyCode_WXK_SNAPSHOT_sym;
  case WXK_INSERT: return keyCode_WXK_INSERT_sym;
  case WXK_HELP: return keyCode_WXK_HELP_sym;
  case WXK_NUMPAD0: return keyCode_WXK_NUMPAD0_sym;
  case WXK_NUMPAD1: return keyCode_WXK_NUMPAD1_sym;
  case WXK_NUMPAD2: return keyCode_WXK_NUMPAD2_sym;
  case WXK_NUMPAD3: return keyCode_WXK_NUMPAD3_sym;
  case WXK_NUMPAD4: return keyCode_WXK_NUMPAD4_sym;
  case WXK_NUMPAD5: return keyCode_WXK_NUMPAD5_sym;
  case WXK_NUMPAD6: return keyCode_WXK_NUMPAD6_sym;
  case WXK_NUMPAD7: return keyCode_WXK_NUMPAD7_sym;
  case WXK_NUMPAD8: return keyCode_WXK_NUMPAD8_sym;
  case WXK_NUMPAD9: return keyCode_WXK_NUMPAD9_sym;
  case WXK_MULTIPLY: return keyCode_WXK_MULTIPLY_sym;
  case WXK_ADD: return keyCode_WXK_ADD_sym;
  case WXK_SEPARATOR: return keyCode_WXK_SEPARATOR_sym;
  case WXK_SUBTRACT: return keyCode_WXK_SUBTRACT_sym;
  case WXK_DECIMAL: return keyCode_WXK_DECIMAL_sym;
  case WXK_DIVIDE: return keyCode_WXK_DIVIDE_sym;
  case WXK_F1: return keyCode_WXK_F1_sym;
  case WXK_F2: return keyCode_WXK_F2_sym;
  case WXK_F3: return keyCode_WXK_F3_sym;
  case WXK_F4: return keyCode_WXK_F4_sym;
  case WXK_F5: return keyCode_WXK_F5_sym;
  case WXK_F6: return keyCode_WXK_F6_sym;
  case WXK_F7: return keyCode_WXK_F7_sym;
  case WXK_F8: return keyCode_WXK_F8_sym;
  case WXK_F9: return keyCode_WXK_F9_sym;
  case WXK_F10: return keyCode_WXK_F10_sym;
  case WXK_F11: return keyCode_WXK_F11_sym;
  case WXK_F12: return keyCode_WXK_F12_sym;
  case WXK_F13: return keyCode_WXK_F13_sym;
  case WXK_F14: return keyCode_WXK_F14_sym;
  case WXK_F15: return keyCode_WXK_F15_sym;
  case WXK_F16: return keyCode_WXK_F16_sym;
  case WXK_F17: return keyCode_WXK_F17_sym;
  case WXK_F18: return keyCode_WXK_F18_sym;
  case WXK_F19: return keyCode_WXK_F19_sym;
  case WXK_F20: return keyCode_WXK_F20_sym;
  case WXK_F21: return keyCode_WXK_F21_sym;
  case WXK_F22: return keyCode_WXK_F22_sym;
  case WXK_F23: return keyCode_WXK_F23_sym;
  case WXK_F24: return keyCode_WXK_F24_sym;
  case WXK_NUMLOCK: return keyCode_WXK_NUMLOCK_sym;
  case WXK_SCROLL: return keyCode_WXK_SCROLL_sym;
  default: return ((v >= 0) && (v <= 255)) ? scheme_make_character(v) : scheme_make_character(0);
  }
}





// @ "key-code" : SYM[keyCode] KeyCode();



class os_wxKeyEvent : public wxKeyEvent {
 public:

  os_wxKeyEvent(Scheme_Object * obj, int x0 = wxEVENT_TYPE_CHAR);
  ~os_wxKeyEvent();
};

Scheme_Object *os_wxKeyEvent_class;

os_wxKeyEvent::os_wxKeyEvent(Scheme_Object * o, int x0)
: wxKeyEvent(x0)
{
  __gc_external = (void *)o;
  objscheme_backpointer(&__gc_external);
  objscheme_note_creation(o);
}

os_wxKeyEvent::~os_wxKeyEvent()
{
    objscheme_destroy(this, (Scheme_Object *)__gc_external);
}

static Scheme_Object *objscheme_wxKeyEvent_GetkeyCode(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  Scheme_Class_Object *cobj;
  int v;

  objscheme_check_valid(obj);
  if (n) scheme_wrong_count("get-key-code", 0, 0, n, p);
  cobj = (Scheme_Class_Object *)obj;
  if (cobj->primflag)
    v = ((os_wxKeyEvent *)cobj->primdata)->wxKeyEvent::keyCode;
  else
    v = ((wxKeyEvent *)cobj->primdata)->keyCode;

  return bundle_symset_keyCode(v);
}

static Scheme_Object *objscheme_wxKeyEvent_SetkeyCode(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  objscheme_check_valid(obj);
  Scheme_Class_Object *cobj=(Scheme_Class_Object *)obj;
  int v;

  if (n != 1) scheme_wrong_count("set-key-code", 1, 1, n, p);

  v = unbundle_symset_keyCode(p[0], "wx:key-event%::key-code");
  ((wxKeyEvent *)cobj->primdata)->keyCode = v;

  return scheme_void;
}

static Scheme_Object *objscheme_wxKeyEvent_GetshiftDown(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  Scheme_Class_Object *cobj;
  Bool v;

  objscheme_check_valid(obj);
  if (n) scheme_wrong_count("get-shift-down", 0, 0, n, p);
  cobj = (Scheme_Class_Object *)obj;
  if (cobj->primflag)
    v = ((os_wxKeyEvent *)cobj->primdata)->wxKeyEvent::shiftDown;
  else
    v = ((wxKeyEvent *)cobj->primdata)->shiftDown;

  return (v ? scheme_true : scheme_false);
}

static Scheme_Object *objscheme_wxKeyEvent_SetshiftDown(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  objscheme_check_valid(obj);
  Scheme_Class_Object *cobj=(Scheme_Class_Object *)obj;
  Bool v;

  if (n != 1) scheme_wrong_count("set-shift-down", 1, 1, n, p);

  v = objscheme_unbundle_bool(p[0], "wx:key-event%::shift-down");
  ((wxKeyEvent *)cobj->primdata)->shiftDown = v;

  return scheme_void;
}

static Scheme_Object *objscheme_wxKeyEvent_GetcontrolDown(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  Scheme_Class_Object *cobj;
  Bool v;

  objscheme_check_valid(obj);
  if (n) scheme_wrong_count("get-control-down", 0, 0, n, p);
  cobj = (Scheme_Class_Object *)obj;
  if (cobj->primflag)
    v = ((os_wxKeyEvent *)cobj->primdata)->wxKeyEvent::controlDown;
  else
    v = ((wxKeyEvent *)cobj->primdata)->controlDown;

  return (v ? scheme_true : scheme_false);
}

static Scheme_Object *objscheme_wxKeyEvent_SetcontrolDown(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  objscheme_check_valid(obj);
  Scheme_Class_Object *cobj=(Scheme_Class_Object *)obj;
  Bool v;

  if (n != 1) scheme_wrong_count("set-control-down", 1, 1, n, p);

  v = objscheme_unbundle_bool(p[0], "wx:key-event%::control-down");
  ((wxKeyEvent *)cobj->primdata)->controlDown = v;

  return scheme_void;
}

static Scheme_Object *objscheme_wxKeyEvent_GetmetaDown(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  Scheme_Class_Object *cobj;
  Bool v;

  objscheme_check_valid(obj);
  if (n) scheme_wrong_count("get-meta-down", 0, 0, n, p);
  cobj = (Scheme_Class_Object *)obj;
  if (cobj->primflag)
    v = ((os_wxKeyEvent *)cobj->primdata)->wxKeyEvent::metaDown;
  else
    v = ((wxKeyEvent *)cobj->primdata)->metaDown;

  return (v ? scheme_true : scheme_false);
}

static Scheme_Object *objscheme_wxKeyEvent_SetmetaDown(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  objscheme_check_valid(obj);
  Scheme_Class_Object *cobj=(Scheme_Class_Object *)obj;
  Bool v;

  if (n != 1) scheme_wrong_count("set-meta-down", 1, 1, n, p);

  v = objscheme_unbundle_bool(p[0], "wx:key-event%::meta-down");
  ((wxKeyEvent *)cobj->primdata)->metaDown = v;

  return scheme_void;
}

static Scheme_Object *objscheme_wxKeyEvent_GetaltDown(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  Scheme_Class_Object *cobj;
  Bool v;

  objscheme_check_valid(obj);
  if (n) scheme_wrong_count("get-alt-down", 0, 0, n, p);
  cobj = (Scheme_Class_Object *)obj;
  if (cobj->primflag)
    v = ((os_wxKeyEvent *)cobj->primdata)->wxKeyEvent::altDown;
  else
    v = ((wxKeyEvent *)cobj->primdata)->altDown;

  return (v ? scheme_true : scheme_false);
}

static Scheme_Object *objscheme_wxKeyEvent_SetaltDown(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  objscheme_check_valid(obj);
  Scheme_Class_Object *cobj=(Scheme_Class_Object *)obj;
  Bool v;

  if (n != 1) scheme_wrong_count("set-alt-down", 1, 1, n, p);

  v = objscheme_unbundle_bool(p[0], "wx:key-event%::alt-down");
  ((wxKeyEvent *)cobj->primdata)->altDown = v;

  return scheme_void;
}

static Scheme_Object *objscheme_wxKeyEvent_GettimeStamp(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  Scheme_Class_Object *cobj;
  long v;

  objscheme_check_valid(obj);
  if (n) scheme_wrong_count("get-time-stamp", 0, 0, n, p);
  cobj = (Scheme_Class_Object *)obj;
  if (cobj->primflag)
    v = ((os_wxKeyEvent *)cobj->primdata)->wxKeyEvent::timeStamp;
  else
    v = ((wxKeyEvent *)cobj->primdata)->timeStamp;

  return scheme_make_integer(v);
}

static Scheme_Object *objscheme_wxKeyEvent_SettimeStamp(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  objscheme_check_valid(obj);
  Scheme_Class_Object *cobj=(Scheme_Class_Object *)obj;
  long v;

  if (n != 1) scheme_wrong_count("set-time-stamp", 1, 1, n, p);

  v = objscheme_unbundle_integer(p[0], "wx:key-event%::time-stamp");
  ((wxKeyEvent *)cobj->primdata)->timeStamp = v;

  return scheme_void;
}

static Scheme_Object *objscheme_wxKeyEvent_Getx(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  Scheme_Class_Object *cobj;
  float v;

  objscheme_check_valid(obj);
  if (n) scheme_wrong_count("get-x", 0, 0, n, p);
  cobj = (Scheme_Class_Object *)obj;
  if (cobj->primflag)
    v = ((os_wxKeyEvent *)cobj->primdata)->wxKeyEvent::x;
  else
    v = ((wxKeyEvent *)cobj->primdata)->x;

  return scheme_make_double(v);
}

static Scheme_Object *objscheme_wxKeyEvent_Setx(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  objscheme_check_valid(obj);
  Scheme_Class_Object *cobj=(Scheme_Class_Object *)obj;
  float v;

  if (n != 1) scheme_wrong_count("set-x", 1, 1, n, p);

  v = objscheme_unbundle_float(p[0], "wx:key-event%::x");
  ((wxKeyEvent *)cobj->primdata)->x = v;

  return scheme_void;
}

static Scheme_Object *objscheme_wxKeyEvent_Gety(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  Scheme_Class_Object *cobj;
  float v;

  objscheme_check_valid(obj);
  if (n) scheme_wrong_count("get-y", 0, 0, n, p);
  cobj = (Scheme_Class_Object *)obj;
  if (cobj->primflag)
    v = ((os_wxKeyEvent *)cobj->primdata)->wxKeyEvent::y;
  else
    v = ((wxKeyEvent *)cobj->primdata)->y;

  return scheme_make_double(v);
}

static Scheme_Object *objscheme_wxKeyEvent_Sety(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  objscheme_check_valid(obj);
  Scheme_Class_Object *cobj=(Scheme_Class_Object *)obj;
  float v;

  if (n != 1) scheme_wrong_count("set-y", 1, 1, n, p);

  v = objscheme_unbundle_float(p[0], "wx:key-event%::y");
  ((wxKeyEvent *)cobj->primdata)->y = v;

  return scheme_void;
}

#pragma argsused
static Scheme_Object *os_wxKeyEvent_ConstructScheme(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  os_wxKeyEvent *realobj;
  int x0;

  
  if (n != 0) 
    scheme_wrong_count("wx:key-event%::initialization", 0, 0, n, p);

  x0=wxEVENT_TYPE_CHAR;
  realobj = new os_wxKeyEvent(obj, x0);
  
  
  ((Scheme_Class_Object *)obj)->primdata = realobj;
  objscheme_register_primpointer(&((Scheme_Class_Object *)obj)->primdata);
  ((Scheme_Class_Object *)obj)->primflag = 1;
  return obj;
}

static Scheme_Object *objscheme_classname_os_wxKeyEvent(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
 WXS_USE_ARGUMENT(obj);
  if (n) scheme_wrong_count("wx:key-event%" "::get-class-name", 0, 0, n, p);
  return scheme_intern_symbol("wx:key-event%");
}

void objscheme_setup_wxKeyEvent(void *env)
{
if (os_wxKeyEvent_class) {
    objscheme_add_global_class(os_wxKeyEvent_class,  "wx:key-event%", env);
} else {
  os_wxKeyEvent_class = objscheme_def_prim_class(env, "wx:key-event%", "wx:event%", os_wxKeyEvent_ConstructScheme, 17);

  scheme_add_method_w_arity(os_wxKeyEvent_class,"get-class-name",objscheme_classname_os_wxKeyEvent, 0, 0);


  scheme_add_method_w_arity(os_wxKeyEvent_class,"get-key-code", objscheme_wxKeyEvent_GetkeyCode, 0, 0);
  scheme_add_method_w_arity(os_wxKeyEvent_class,"set-key-code", objscheme_wxKeyEvent_SetkeyCode, 1, 1);
  scheme_add_method_w_arity(os_wxKeyEvent_class,"get-shift-down", objscheme_wxKeyEvent_GetshiftDown, 0, 0);
  scheme_add_method_w_arity(os_wxKeyEvent_class,"set-shift-down", objscheme_wxKeyEvent_SetshiftDown, 1, 1);
  scheme_add_method_w_arity(os_wxKeyEvent_class,"get-control-down", objscheme_wxKeyEvent_GetcontrolDown, 0, 0);
  scheme_add_method_w_arity(os_wxKeyEvent_class,"set-control-down", objscheme_wxKeyEvent_SetcontrolDown, 1, 1);
  scheme_add_method_w_arity(os_wxKeyEvent_class,"get-meta-down", objscheme_wxKeyEvent_GetmetaDown, 0, 0);
  scheme_add_method_w_arity(os_wxKeyEvent_class,"set-meta-down", objscheme_wxKeyEvent_SetmetaDown, 1, 1);
  scheme_add_method_w_arity(os_wxKeyEvent_class,"get-alt-down", objscheme_wxKeyEvent_GetaltDown, 0, 0);
  scheme_add_method_w_arity(os_wxKeyEvent_class,"set-alt-down", objscheme_wxKeyEvent_SetaltDown, 1, 1);
  scheme_add_method_w_arity(os_wxKeyEvent_class,"get-time-stamp", objscheme_wxKeyEvent_GettimeStamp, 0, 0);
  scheme_add_method_w_arity(os_wxKeyEvent_class,"set-time-stamp", objscheme_wxKeyEvent_SettimeStamp, 1, 1);
  scheme_add_method_w_arity(os_wxKeyEvent_class,"get-x", objscheme_wxKeyEvent_Getx, 0, 0);
  scheme_add_method_w_arity(os_wxKeyEvent_class,"set-x", objscheme_wxKeyEvent_Setx, 1, 1);
  scheme_add_method_w_arity(os_wxKeyEvent_class,"get-y", objscheme_wxKeyEvent_Gety, 0, 0);
  scheme_add_method_w_arity(os_wxKeyEvent_class,"set-y", objscheme_wxKeyEvent_Sety, 1, 1);

  scheme_made_class(os_wxKeyEvent_class);


}
}

int objscheme_istype_wxKeyEvent(Scheme_Object *obj, const char *stop, int nullOK)
{
  if (nullOK && XC_SCHEME_NULLP(obj)) return 1;
  if (SAME_TYPE(SCHEME_TYPE(obj), scheme_object_type)
      && scheme_is_subclass(((Scheme_Class_Object *)obj)->sclass,          os_wxKeyEvent_class))
    return 1;
  else {
    if (!stop)
       return 0;
    scheme_wrong_type(stop, nullOK ? "wx:key-event% object or " XC_NULL_STR: "wx:key-event% object", -1, 0, &obj);
    return 0;
  }
}

Scheme_Object *objscheme_bundle_wxKeyEvent(class wxKeyEvent *realobj)
{
  Scheme_Class_Object *obj;
  Scheme_Object *sobj;

  if (!realobj) return XC_SCHEME_NULL;

  if (realobj->__gc_external)
    return (Scheme_Object *)realobj->__gc_external;
  if ((sobj = objscheme_bundle_by_type(realobj, realobj->__type)))
    return sobj;
  obj = (Scheme_Class_Object *)scheme_make_uninited_object(os_wxKeyEvent_class);

  obj->primdata = realobj;
  objscheme_register_primpointer(&obj->primdata);
  obj->primflag = 0;

  realobj->__gc_external = (void *)obj;
  objscheme_backpointer(&realobj->__gc_external);
  return (Scheme_Object *)obj;
}

class wxKeyEvent *objscheme_unbundle_wxKeyEvent(Scheme_Object *obj, const char *where, int nullOK)
{
  if (nullOK && XC_SCHEME_NULLP(obj)) return NULL;

  (void)objscheme_istype_wxKeyEvent(obj, where, nullOK);
  Scheme_Class_Object *o = (Scheme_Class_Object *)obj;
  objscheme_check_valid(obj);
  if (o->primflag)
    return (os_wxKeyEvent *)o->primdata;
  else
    return (wxKeyEvent *)o->primdata;
}


static Scheme_Object *mouseEventType_wxEVENT_TYPE_LEFT_DOWN_sym = NULL;
static Scheme_Object *mouseEventType_wxEVENT_TYPE_LEFT_UP_sym = NULL;
static Scheme_Object *mouseEventType_wxEVENT_TYPE_MIDDLE_DOWN_sym = NULL;
static Scheme_Object *mouseEventType_wxEVENT_TYPE_MIDDLE_UP_sym = NULL;
static Scheme_Object *mouseEventType_wxEVENT_TYPE_RIGHT_DOWN_sym = NULL;
static Scheme_Object *mouseEventType_wxEVENT_TYPE_RIGHT_UP_sym = NULL;
static Scheme_Object *mouseEventType_wxEVENT_TYPE_MOTION_sym = NULL;
static Scheme_Object *mouseEventType_wxEVENT_TYPE_ENTER_WINDOW_sym = NULL;
static Scheme_Object *mouseEventType_wxEVENT_TYPE_LEAVE_WINDOW_sym = NULL;
static Scheme_Object *mouseEventType_wxEVENT_TYPE_LEFT_DCLICK_sym = NULL;
static Scheme_Object *mouseEventType_wxEVENT_TYPE_MIDDLE_DCLICK_sym = NULL;
static Scheme_Object *mouseEventType_wxEVENT_TYPE_RIGHT_DCLICK_sym = NULL;

static void init_symset_mouseEventType(void) {
  mouseEventType_wxEVENT_TYPE_LEFT_DOWN_sym = scheme_intern_symbol("left-down");
  mouseEventType_wxEVENT_TYPE_LEFT_UP_sym = scheme_intern_symbol("left-up");
  mouseEventType_wxEVENT_TYPE_MIDDLE_DOWN_sym = scheme_intern_symbol("middle-down");
  mouseEventType_wxEVENT_TYPE_MIDDLE_UP_sym = scheme_intern_symbol("middle-up");
  mouseEventType_wxEVENT_TYPE_RIGHT_DOWN_sym = scheme_intern_symbol("right-down");
  mouseEventType_wxEVENT_TYPE_RIGHT_UP_sym = scheme_intern_symbol("right-up");
  mouseEventType_wxEVENT_TYPE_MOTION_sym = scheme_intern_symbol("motion");
  mouseEventType_wxEVENT_TYPE_ENTER_WINDOW_sym = scheme_intern_symbol("enter-window");
  mouseEventType_wxEVENT_TYPE_LEAVE_WINDOW_sym = scheme_intern_symbol("leave-window");
  mouseEventType_wxEVENT_TYPE_LEFT_DCLICK_sym = scheme_intern_symbol("left-dclick");
  mouseEventType_wxEVENT_TYPE_MIDDLE_DCLICK_sym = scheme_intern_symbol("middle-dclick");
  mouseEventType_wxEVENT_TYPE_RIGHT_DCLICK_sym = scheme_intern_symbol("right-dclick");
}

static int unbundle_symset_mouseEventType(Scheme_Object *v, const char *where) {
  if (!mouseEventType_wxEVENT_TYPE_RIGHT_DCLICK_sym) init_symset_mouseEventType();
  if (0) { }
  else if (v == mouseEventType_wxEVENT_TYPE_LEFT_DOWN_sym) { return wxEVENT_TYPE_LEFT_DOWN; }
  else if (v == mouseEventType_wxEVENT_TYPE_LEFT_UP_sym) { return wxEVENT_TYPE_LEFT_UP; }
  else if (v == mouseEventType_wxEVENT_TYPE_MIDDLE_DOWN_sym) { return wxEVENT_TYPE_MIDDLE_DOWN; }
  else if (v == mouseEventType_wxEVENT_TYPE_MIDDLE_UP_sym) { return wxEVENT_TYPE_MIDDLE_UP; }
  else if (v == mouseEventType_wxEVENT_TYPE_RIGHT_DOWN_sym) { return wxEVENT_TYPE_RIGHT_DOWN; }
  else if (v == mouseEventType_wxEVENT_TYPE_RIGHT_UP_sym) { return wxEVENT_TYPE_RIGHT_UP; }
  else if (v == mouseEventType_wxEVENT_TYPE_MOTION_sym) { return wxEVENT_TYPE_MOTION; }
  else if (v == mouseEventType_wxEVENT_TYPE_ENTER_WINDOW_sym) { return wxEVENT_TYPE_ENTER_WINDOW; }
  else if (v == mouseEventType_wxEVENT_TYPE_LEAVE_WINDOW_sym) { return wxEVENT_TYPE_LEAVE_WINDOW; }
  else if (v == mouseEventType_wxEVENT_TYPE_LEFT_DCLICK_sym) { return wxEVENT_TYPE_LEFT_DCLICK; }
  else if (v == mouseEventType_wxEVENT_TYPE_MIDDLE_DCLICK_sym) { return wxEVENT_TYPE_MIDDLE_DCLICK; }
  else if (v == mouseEventType_wxEVENT_TYPE_RIGHT_DCLICK_sym) { return wxEVENT_TYPE_RIGHT_DCLICK; }
  if (where) scheme_wrong_type(where, "mouseEventType symbol", -1, 0, &v);
  return 0;
}

static int istype_symset_mouseEventType(Scheme_Object *v, const char *where) {
  if (!mouseEventType_wxEVENT_TYPE_RIGHT_DCLICK_sym) init_symset_mouseEventType();
  if (0) { }
  else if (v == mouseEventType_wxEVENT_TYPE_LEFT_DOWN_sym) { return 1; }
  else if (v == mouseEventType_wxEVENT_TYPE_LEFT_UP_sym) { return 1; }
  else if (v == mouseEventType_wxEVENT_TYPE_MIDDLE_DOWN_sym) { return 1; }
  else if (v == mouseEventType_wxEVENT_TYPE_MIDDLE_UP_sym) { return 1; }
  else if (v == mouseEventType_wxEVENT_TYPE_RIGHT_DOWN_sym) { return 1; }
  else if (v == mouseEventType_wxEVENT_TYPE_RIGHT_UP_sym) { return 1; }
  else if (v == mouseEventType_wxEVENT_TYPE_MOTION_sym) { return 1; }
  else if (v == mouseEventType_wxEVENT_TYPE_ENTER_WINDOW_sym) { return 1; }
  else if (v == mouseEventType_wxEVENT_TYPE_LEAVE_WINDOW_sym) { return 1; }
  else if (v == mouseEventType_wxEVENT_TYPE_LEFT_DCLICK_sym) { return 1; }
  else if (v == mouseEventType_wxEVENT_TYPE_MIDDLE_DCLICK_sym) { return 1; }
  else if (v == mouseEventType_wxEVENT_TYPE_RIGHT_DCLICK_sym) { return 1; }
  if (where) scheme_wrong_type(where, "mouseEventType symbol", -1, 0, &v);
  return 0;
}

static Scheme_Object *bundle_symset_mouseEventType(int v) {
  if (!mouseEventType_wxEVENT_TYPE_RIGHT_DCLICK_sym) init_symset_mouseEventType();
  switch (v) {
  case wxEVENT_TYPE_LEFT_DOWN: return mouseEventType_wxEVENT_TYPE_LEFT_DOWN_sym;
  case wxEVENT_TYPE_LEFT_UP: return mouseEventType_wxEVENT_TYPE_LEFT_UP_sym;
  case wxEVENT_TYPE_MIDDLE_DOWN: return mouseEventType_wxEVENT_TYPE_MIDDLE_DOWN_sym;
  case wxEVENT_TYPE_MIDDLE_UP: return mouseEventType_wxEVENT_TYPE_MIDDLE_UP_sym;
  case wxEVENT_TYPE_RIGHT_DOWN: return mouseEventType_wxEVENT_TYPE_RIGHT_DOWN_sym;
  case wxEVENT_TYPE_RIGHT_UP: return mouseEventType_wxEVENT_TYPE_RIGHT_UP_sym;
  case wxEVENT_TYPE_MOTION: return mouseEventType_wxEVENT_TYPE_MOTION_sym;
  case wxEVENT_TYPE_ENTER_WINDOW: return mouseEventType_wxEVENT_TYPE_ENTER_WINDOW_sym;
  case wxEVENT_TYPE_LEAVE_WINDOW: return mouseEventType_wxEVENT_TYPE_LEAVE_WINDOW_sym;
  case wxEVENT_TYPE_LEFT_DCLICK: return mouseEventType_wxEVENT_TYPE_LEFT_DCLICK_sym;
  case wxEVENT_TYPE_MIDDLE_DCLICK: return mouseEventType_wxEVENT_TYPE_MIDDLE_DCLICK_sym;
  case wxEVENT_TYPE_RIGHT_DCLICK: return mouseEventType_wxEVENT_TYPE_RIGHT_DCLICK_sym;
  default: return NULL;
  }
}






class os_wxMouseEvent : public wxMouseEvent {
 public:

  os_wxMouseEvent(Scheme_Object * obj, int x0);
  ~os_wxMouseEvent();
};

Scheme_Object *os_wxMouseEvent_class;

os_wxMouseEvent::os_wxMouseEvent(Scheme_Object * o, int x0)
: wxMouseEvent(x0)
{
  __gc_external = (void *)o;
  objscheme_backpointer(&__gc_external);
  objscheme_note_creation(o);
}

os_wxMouseEvent::~os_wxMouseEvent()
{
    objscheme_destroy(this, (Scheme_Object *)__gc_external);
}

#pragma argsused
static Scheme_Object *os_wxMouseEventMoving(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
 WXS_USE_ARGUMENT(n) WXS_USE_ARGUMENT(p)
  Bool r;
  objscheme_check_valid(obj);

  

  
  r = ((wxMouseEvent *)((Scheme_Class_Object *)obj)->primdata)->Moving();

  
  
  return (r ? scheme_true : scheme_false);
}

#pragma argsused
static Scheme_Object *os_wxMouseEventIsButton(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
 WXS_USE_ARGUMENT(n) WXS_USE_ARGUMENT(p)
  Bool r;
  objscheme_check_valid(obj);

  

  
  r = ((wxMouseEvent *)((Scheme_Class_Object *)obj)->primdata)->IsButton();

  
  
  return (r ? scheme_true : scheme_false);
}

#pragma argsused
static Scheme_Object *os_wxMouseEventLeaving(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
 WXS_USE_ARGUMENT(n) WXS_USE_ARGUMENT(p)
  Bool r;
  objscheme_check_valid(obj);

  

  
  r = ((wxMouseEvent *)((Scheme_Class_Object *)obj)->primdata)->Leaving();

  
  
  return (r ? scheme_true : scheme_false);
}

#pragma argsused
static Scheme_Object *os_wxMouseEventEntering(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
 WXS_USE_ARGUMENT(n) WXS_USE_ARGUMENT(p)
  Bool r;
  objscheme_check_valid(obj);

  

  
  r = ((wxMouseEvent *)((Scheme_Class_Object *)obj)->primdata)->Entering();

  
  
  return (r ? scheme_true : scheme_false);
}

#pragma argsused
static Scheme_Object *os_wxMouseEventDragging(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
 WXS_USE_ARGUMENT(n) WXS_USE_ARGUMENT(p)
  Bool r;
  objscheme_check_valid(obj);

  

  
  r = ((wxMouseEvent *)((Scheme_Class_Object *)obj)->primdata)->Dragging();

  
  
  return (r ? scheme_true : scheme_false);
}

#pragma argsused
static Scheme_Object *os_wxMouseEventButtonUp(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
 WXS_USE_ARGUMENT(n) WXS_USE_ARGUMENT(p)
  Bool r;
  objscheme_check_valid(obj);
  int x0;

  
  if (n > 0) {
    x0 = objscheme_unbundle_integer(p[0], "wx:mouse-event%::button-up?");
  } else
    x0 = -1;

  
  r = ((wxMouseEvent *)((Scheme_Class_Object *)obj)->primdata)->ButtonUp(x0);

  
  
  return (r ? scheme_true : scheme_false);
}

#pragma argsused
static Scheme_Object *os_wxMouseEventButtonDown(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
 WXS_USE_ARGUMENT(n) WXS_USE_ARGUMENT(p)
  Bool r;
  objscheme_check_valid(obj);
  int x0;

  
  if (n > 0) {
    x0 = objscheme_unbundle_integer(p[0], "wx:mouse-event%::button-down?");
  } else
    x0 = -1;

  
  r = ((wxMouseEvent *)((Scheme_Class_Object *)obj)->primdata)->ButtonDown(x0);

  
  
  return (r ? scheme_true : scheme_false);
}

#pragma argsused
static Scheme_Object *os_wxMouseEventButtonDClick(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
 WXS_USE_ARGUMENT(n) WXS_USE_ARGUMENT(p)
  Bool r;
  objscheme_check_valid(obj);
  int x0;

  
  if (n > 0) {
    x0 = objscheme_unbundle_integer(p[0], "wx:mouse-event%::button-d-click?");
  } else
    x0 = -1;

  
  r = ((wxMouseEvent *)((Scheme_Class_Object *)obj)->primdata)->ButtonDClick(x0);

  
  
  return (r ? scheme_true : scheme_false);
}

#pragma argsused
static Scheme_Object *os_wxMouseEventButton(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
 WXS_USE_ARGUMENT(n) WXS_USE_ARGUMENT(p)
  Bool r;
  objscheme_check_valid(obj);
  int x0;

  
  x0 = objscheme_unbundle_integer(p[0], "wx:mouse-event%::button?");

  
  r = ((wxMouseEvent *)((Scheme_Class_Object *)obj)->primdata)->Button(x0);

  
  
  return (r ? scheme_true : scheme_false);
}

static Scheme_Object *objscheme_wxMouseEvent_GeteventType(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  Scheme_Class_Object *cobj;
  int v;

  objscheme_check_valid(obj);
  if (n) scheme_wrong_count("get-event-type", 0, 0, n, p);
  cobj = (Scheme_Class_Object *)obj;
  if (cobj->primflag)
    v = ((os_wxMouseEvent *)cobj->primdata)->wxMouseEvent::eventType;
  else
    v = ((wxMouseEvent *)cobj->primdata)->eventType;

  return bundle_symset_mouseEventType(v);
}

static Scheme_Object *objscheme_wxMouseEvent_SeteventType(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  objscheme_check_valid(obj);
  Scheme_Class_Object *cobj=(Scheme_Class_Object *)obj;
  int v;

  if (n != 1) scheme_wrong_count("set-event-type", 1, 1, n, p);

  v = unbundle_symset_mouseEventType(p[0], "wx:mouse-event%::event-type");
  ((wxMouseEvent *)cobj->primdata)->eventType = v;

  return scheme_void;
}

static Scheme_Object *objscheme_wxMouseEvent_GetleftDown(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  Scheme_Class_Object *cobj;
  Bool v;

  objscheme_check_valid(obj);
  if (n) scheme_wrong_count("get-left-down", 0, 0, n, p);
  cobj = (Scheme_Class_Object *)obj;
  if (cobj->primflag)
    v = ((os_wxMouseEvent *)cobj->primdata)->wxMouseEvent::leftDown;
  else
    v = ((wxMouseEvent *)cobj->primdata)->leftDown;

  return (v ? scheme_true : scheme_false);
}

static Scheme_Object *objscheme_wxMouseEvent_SetleftDown(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  objscheme_check_valid(obj);
  Scheme_Class_Object *cobj=(Scheme_Class_Object *)obj;
  Bool v;

  if (n != 1) scheme_wrong_count("set-left-down", 1, 1, n, p);

  v = objscheme_unbundle_bool(p[0], "wx:mouse-event%::left-down");
  ((wxMouseEvent *)cobj->primdata)->leftDown = v;

  return scheme_void;
}

static Scheme_Object *objscheme_wxMouseEvent_GetmiddleDown(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  Scheme_Class_Object *cobj;
  Bool v;

  objscheme_check_valid(obj);
  if (n) scheme_wrong_count("get-middle-down", 0, 0, n, p);
  cobj = (Scheme_Class_Object *)obj;
  if (cobj->primflag)
    v = ((os_wxMouseEvent *)cobj->primdata)->wxMouseEvent::middleDown;
  else
    v = ((wxMouseEvent *)cobj->primdata)->middleDown;

  return (v ? scheme_true : scheme_false);
}

static Scheme_Object *objscheme_wxMouseEvent_SetmiddleDown(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  objscheme_check_valid(obj);
  Scheme_Class_Object *cobj=(Scheme_Class_Object *)obj;
  Bool v;

  if (n != 1) scheme_wrong_count("set-middle-down", 1, 1, n, p);

  v = objscheme_unbundle_bool(p[0], "wx:mouse-event%::middle-down");
  ((wxMouseEvent *)cobj->primdata)->middleDown = v;

  return scheme_void;
}

static Scheme_Object *objscheme_wxMouseEvent_GetrightDown(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  Scheme_Class_Object *cobj;
  Bool v;

  objscheme_check_valid(obj);
  if (n) scheme_wrong_count("get-right-down", 0, 0, n, p);
  cobj = (Scheme_Class_Object *)obj;
  if (cobj->primflag)
    v = ((os_wxMouseEvent *)cobj->primdata)->wxMouseEvent::rightDown;
  else
    v = ((wxMouseEvent *)cobj->primdata)->rightDown;

  return (v ? scheme_true : scheme_false);
}

static Scheme_Object *objscheme_wxMouseEvent_SetrightDown(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  objscheme_check_valid(obj);
  Scheme_Class_Object *cobj=(Scheme_Class_Object *)obj;
  Bool v;

  if (n != 1) scheme_wrong_count("set-right-down", 1, 1, n, p);

  v = objscheme_unbundle_bool(p[0], "wx:mouse-event%::right-down");
  ((wxMouseEvent *)cobj->primdata)->rightDown = v;

  return scheme_void;
}

static Scheme_Object *objscheme_wxMouseEvent_GetshiftDown(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  Scheme_Class_Object *cobj;
  Bool v;

  objscheme_check_valid(obj);
  if (n) scheme_wrong_count("get-shift-down", 0, 0, n, p);
  cobj = (Scheme_Class_Object *)obj;
  if (cobj->primflag)
    v = ((os_wxMouseEvent *)cobj->primdata)->wxMouseEvent::shiftDown;
  else
    v = ((wxMouseEvent *)cobj->primdata)->shiftDown;

  return (v ? scheme_true : scheme_false);
}

static Scheme_Object *objscheme_wxMouseEvent_SetshiftDown(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  objscheme_check_valid(obj);
  Scheme_Class_Object *cobj=(Scheme_Class_Object *)obj;
  Bool v;

  if (n != 1) scheme_wrong_count("set-shift-down", 1, 1, n, p);

  v = objscheme_unbundle_bool(p[0], "wx:mouse-event%::shift-down");
  ((wxMouseEvent *)cobj->primdata)->shiftDown = v;

  return scheme_void;
}

static Scheme_Object *objscheme_wxMouseEvent_GetcontrolDown(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  Scheme_Class_Object *cobj;
  Bool v;

  objscheme_check_valid(obj);
  if (n) scheme_wrong_count("get-control-down", 0, 0, n, p);
  cobj = (Scheme_Class_Object *)obj;
  if (cobj->primflag)
    v = ((os_wxMouseEvent *)cobj->primdata)->wxMouseEvent::controlDown;
  else
    v = ((wxMouseEvent *)cobj->primdata)->controlDown;

  return (v ? scheme_true : scheme_false);
}

static Scheme_Object *objscheme_wxMouseEvent_SetcontrolDown(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  objscheme_check_valid(obj);
  Scheme_Class_Object *cobj=(Scheme_Class_Object *)obj;
  Bool v;

  if (n != 1) scheme_wrong_count("set-control-down", 1, 1, n, p);

  v = objscheme_unbundle_bool(p[0], "wx:mouse-event%::control-down");
  ((wxMouseEvent *)cobj->primdata)->controlDown = v;

  return scheme_void;
}

static Scheme_Object *objscheme_wxMouseEvent_GetmetaDown(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  Scheme_Class_Object *cobj;
  Bool v;

  objscheme_check_valid(obj);
  if (n) scheme_wrong_count("get-meta-down", 0, 0, n, p);
  cobj = (Scheme_Class_Object *)obj;
  if (cobj->primflag)
    v = ((os_wxMouseEvent *)cobj->primdata)->wxMouseEvent::metaDown;
  else
    v = ((wxMouseEvent *)cobj->primdata)->metaDown;

  return (v ? scheme_true : scheme_false);
}

static Scheme_Object *objscheme_wxMouseEvent_SetmetaDown(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  objscheme_check_valid(obj);
  Scheme_Class_Object *cobj=(Scheme_Class_Object *)obj;
  Bool v;

  if (n != 1) scheme_wrong_count("set-meta-down", 1, 1, n, p);

  v = objscheme_unbundle_bool(p[0], "wx:mouse-event%::meta-down");
  ((wxMouseEvent *)cobj->primdata)->metaDown = v;

  return scheme_void;
}

static Scheme_Object *objscheme_wxMouseEvent_GetaltDown(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  Scheme_Class_Object *cobj;
  Bool v;

  objscheme_check_valid(obj);
  if (n) scheme_wrong_count("get-alt-down", 0, 0, n, p);
  cobj = (Scheme_Class_Object *)obj;
  if (cobj->primflag)
    v = ((os_wxMouseEvent *)cobj->primdata)->wxMouseEvent::altDown;
  else
    v = ((wxMouseEvent *)cobj->primdata)->altDown;

  return (v ? scheme_true : scheme_false);
}

static Scheme_Object *objscheme_wxMouseEvent_SetaltDown(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  objscheme_check_valid(obj);
  Scheme_Class_Object *cobj=(Scheme_Class_Object *)obj;
  Bool v;

  if (n != 1) scheme_wrong_count("set-alt-down", 1, 1, n, p);

  v = objscheme_unbundle_bool(p[0], "wx:mouse-event%::alt-down");
  ((wxMouseEvent *)cobj->primdata)->altDown = v;

  return scheme_void;
}

static Scheme_Object *objscheme_wxMouseEvent_Getx(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  Scheme_Class_Object *cobj;
  float v;

  objscheme_check_valid(obj);
  if (n) scheme_wrong_count("get-x", 0, 0, n, p);
  cobj = (Scheme_Class_Object *)obj;
  if (cobj->primflag)
    v = ((os_wxMouseEvent *)cobj->primdata)->wxMouseEvent::x;
  else
    v = ((wxMouseEvent *)cobj->primdata)->x;

  return scheme_make_double(v);
}

static Scheme_Object *objscheme_wxMouseEvent_Setx(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  objscheme_check_valid(obj);
  Scheme_Class_Object *cobj=(Scheme_Class_Object *)obj;
  float v;

  if (n != 1) scheme_wrong_count("set-x", 1, 1, n, p);

  v = objscheme_unbundle_float(p[0], "wx:mouse-event%::x");
  ((wxMouseEvent *)cobj->primdata)->x = v;

  return scheme_void;
}

static Scheme_Object *objscheme_wxMouseEvent_Gety(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  Scheme_Class_Object *cobj;
  float v;

  objscheme_check_valid(obj);
  if (n) scheme_wrong_count("get-y", 0, 0, n, p);
  cobj = (Scheme_Class_Object *)obj;
  if (cobj->primflag)
    v = ((os_wxMouseEvent *)cobj->primdata)->wxMouseEvent::y;
  else
    v = ((wxMouseEvent *)cobj->primdata)->y;

  return scheme_make_double(v);
}

static Scheme_Object *objscheme_wxMouseEvent_Sety(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  objscheme_check_valid(obj);
  Scheme_Class_Object *cobj=(Scheme_Class_Object *)obj;
  float v;

  if (n != 1) scheme_wrong_count("set-y", 1, 1, n, p);

  v = objscheme_unbundle_float(p[0], "wx:mouse-event%::y");
  ((wxMouseEvent *)cobj->primdata)->y = v;

  return scheme_void;
}

static Scheme_Object *objscheme_wxMouseEvent_GettimeStamp(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  Scheme_Class_Object *cobj;
  long v;

  objscheme_check_valid(obj);
  if (n) scheme_wrong_count("get-time-stamp", 0, 0, n, p);
  cobj = (Scheme_Class_Object *)obj;
  if (cobj->primflag)
    v = ((os_wxMouseEvent *)cobj->primdata)->wxMouseEvent::timeStamp;
  else
    v = ((wxMouseEvent *)cobj->primdata)->timeStamp;

  return scheme_make_integer(v);
}

static Scheme_Object *objscheme_wxMouseEvent_SettimeStamp(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  objscheme_check_valid(obj);
  Scheme_Class_Object *cobj=(Scheme_Class_Object *)obj;
  long v;

  if (n != 1) scheme_wrong_count("set-time-stamp", 1, 1, n, p);

  v = objscheme_unbundle_integer(p[0], "wx:mouse-event%::time-stamp");
  ((wxMouseEvent *)cobj->primdata)->timeStamp = v;

  return scheme_void;
}

#pragma argsused
static Scheme_Object *os_wxMouseEvent_ConstructScheme(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
  os_wxMouseEvent *realobj;
  int x0;

  
  if (n != 1) 
    scheme_wrong_count("wx:mouse-event%::initialization", 1, 1, n, p);
  x0 = objscheme_unbundle_integer(p[0], "wx:mouse-event%::initialization");

  
  realobj = new os_wxMouseEvent(obj, x0);
  
  
  ((Scheme_Class_Object *)obj)->primdata = realobj;
  objscheme_register_primpointer(&((Scheme_Class_Object *)obj)->primdata);
  ((Scheme_Class_Object *)obj)->primflag = 1;
  return obj;
}

static Scheme_Object *objscheme_classname_os_wxMouseEvent(Scheme_Object *obj, int n,  Scheme_Object *p[])
{
 WXS_USE_ARGUMENT(obj);
  if (n) scheme_wrong_count("wx:mouse-event%" "::get-class-name", 0, 0, n, p);
  return scheme_intern_symbol("wx:mouse-event%");
}

void objscheme_setup_wxMouseEvent(void *env)
{
if (os_wxMouseEvent_class) {
    objscheme_add_global_class(os_wxMouseEvent_class,  "wx:mouse-event%", env);
} else {
  os_wxMouseEvent_class = objscheme_def_prim_class(env, "wx:mouse-event%", "wx:event%", os_wxMouseEvent_ConstructScheme, 32);

  scheme_add_method_w_arity(os_wxMouseEvent_class,"get-class-name",objscheme_classname_os_wxMouseEvent, 0, 0);

 scheme_add_method_w_arity(os_wxMouseEvent_class, "moving?", os_wxMouseEventMoving, 0, 0);
 scheme_add_method_w_arity(os_wxMouseEvent_class, "is-button?", os_wxMouseEventIsButton, 0, 0);
 scheme_add_method_w_arity(os_wxMouseEvent_class, "leaving?", os_wxMouseEventLeaving, 0, 0);
 scheme_add_method_w_arity(os_wxMouseEvent_class, "entering?", os_wxMouseEventEntering, 0, 0);
 scheme_add_method_w_arity(os_wxMouseEvent_class, "dragging?", os_wxMouseEventDragging, 0, 0);
 scheme_add_method_w_arity(os_wxMouseEvent_class, "button-up?", os_wxMouseEventButtonUp, 0, 1);
 scheme_add_method_w_arity(os_wxMouseEvent_class, "button-down?", os_wxMouseEventButtonDown, 0, 1);
 scheme_add_method_w_arity(os_wxMouseEvent_class, "button-d-click?", os_wxMouseEventButtonDClick, 0, 1);
 scheme_add_method_w_arity(os_wxMouseEvent_class, "button?", os_wxMouseEventButton, 1, 1);

  scheme_add_method_w_arity(os_wxMouseEvent_class,"get-event-type", objscheme_wxMouseEvent_GeteventType, 0, 0);
  scheme_add_method_w_arity(os_wxMouseEvent_class,"set-event-type", objscheme_wxMouseEvent_SeteventType, 1, 1);
  scheme_add_method_w_arity(os_wxMouseEvent_class,"get-left-down", objscheme_wxMouseEvent_GetleftDown, 0, 0);
  scheme_add_method_w_arity(os_wxMouseEvent_class,"set-left-down", objscheme_wxMouseEvent_SetleftDown, 1, 1);
  scheme_add_method_w_arity(os_wxMouseEvent_class,"get-middle-down", objscheme_wxMouseEvent_GetmiddleDown, 0, 0);
  scheme_add_method_w_arity(os_wxMouseEvent_class,"set-middle-down", objscheme_wxMouseEvent_SetmiddleDown, 1, 1);
  scheme_add_method_w_arity(os_wxMouseEvent_class,"get-right-down", objscheme_wxMouseEvent_GetrightDown, 0, 0);
  scheme_add_method_w_arity(os_wxMouseEvent_class,"set-right-down", objscheme_wxMouseEvent_SetrightDown, 1, 1);
  scheme_add_method_w_arity(os_wxMouseEvent_class,"get-shift-down", objscheme_wxMouseEvent_GetshiftDown, 0, 0);
  scheme_add_method_w_arity(os_wxMouseEvent_class,"set-shift-down", objscheme_wxMouseEvent_SetshiftDown, 1, 1);
  scheme_add_method_w_arity(os_wxMouseEvent_class,"get-control-down", objscheme_wxMouseEvent_GetcontrolDown, 0, 0);
  scheme_add_method_w_arity(os_wxMouseEvent_class,"set-control-down", objscheme_wxMouseEvent_SetcontrolDown, 1, 1);
  scheme_add_method_w_arity(os_wxMouseEvent_class,"get-meta-down", objscheme_wxMouseEvent_GetmetaDown, 0, 0);
  scheme_add_method_w_arity(os_wxMouseEvent_class,"set-meta-down", objscheme_wxMouseEvent_SetmetaDown, 1, 1);
  scheme_add_method_w_arity(os_wxMouseEvent_class,"get-alt-down", objscheme_wxMouseEvent_GetaltDown, 0, 0);
  scheme_add_method_w_arity(os_wxMouseEvent_class,"set-alt-down", objscheme_wxMouseEvent_SetaltDown, 1, 1);
  scheme_add_method_w_arity(os_wxMouseEvent_class,"get-x", objscheme_wxMouseEvent_Getx, 0, 0);
  scheme_add_method_w_arity(os_wxMouseEvent_class,"set-x", objscheme_wxMouseEvent_Setx, 1, 1);
  scheme_add_method_w_arity(os_wxMouseEvent_class,"get-y", objscheme_wxMouseEvent_Gety, 0, 0);
  scheme_add_method_w_arity(os_wxMouseEvent_class,"set-y", objscheme_wxMouseEvent_Sety, 1, 1);
  scheme_add_method_w_arity(os_wxMouseEvent_class,"get-time-stamp", objscheme_wxMouseEvent_GettimeStamp, 0, 0);
  scheme_add_method_w_arity(os_wxMouseEvent_class,"set-time-stamp", objscheme_wxMouseEvent_SettimeStamp, 1, 1);

  scheme_made_class(os_wxMouseEvent_class);


}
}

int objscheme_istype_wxMouseEvent(Scheme_Object *obj, const char *stop, int nullOK)
{
  if (nullOK && XC_SCHEME_NULLP(obj)) return 1;
  if (SAME_TYPE(SCHEME_TYPE(obj), scheme_object_type)
      && scheme_is_subclass(((Scheme_Class_Object *)obj)->sclass,          os_wxMouseEvent_class))
    return 1;
  else {
    if (!stop)
       return 0;
    scheme_wrong_type(stop, nullOK ? "wx:mouse-event% object or " XC_NULL_STR: "wx:mouse-event% object", -1, 0, &obj);
    return 0;
  }
}

Scheme_Object *objscheme_bundle_wxMouseEvent(class wxMouseEvent *realobj)
{
  Scheme_Class_Object *obj;
  Scheme_Object *sobj;

  if (!realobj) return XC_SCHEME_NULL;

  if (realobj->__gc_external)
    return (Scheme_Object *)realobj->__gc_external;
  if ((sobj = objscheme_bundle_by_type(realobj, realobj->__type)))
    return sobj;
  obj = (Scheme_Class_Object *)scheme_make_uninited_object(os_wxMouseEvent_class);

  obj->primdata = realobj;
  objscheme_register_primpointer(&obj->primdata);
  obj->primflag = 0;

  realobj->__gc_external = (void *)obj;
  objscheme_backpointer(&realobj->__gc_external);
  return (Scheme_Object *)obj;
}

class wxMouseEvent *objscheme_unbundle_wxMouseEvent(Scheme_Object *obj, const char *where, int nullOK)
{
  if (nullOK && XC_SCHEME_NULLP(obj)) return NULL;

  (void)objscheme_istype_wxMouseEvent(obj, where, nullOK);
  Scheme_Class_Object *o = (Scheme_Class_Object *)obj;
  objscheme_check_valid(obj);
  if (o->primflag)
    return (os_wxMouseEvent *)o->primdata;
  else
    return (wxMouseEvent *)o->primdata;
}

