(module windows (lib "mzrestricted.ss" "file-browser")
  (require (lib "script.ss" "file-browser"))
  (provide (all-defined))
  (define (left-mouse-file file)
    (clear-selection)
    (cons-selection file))
  (define (middle-mouse-file file) (printf "2~n"))
  (define (right-mouse-file file) (printf "3~n"))
  (define (double-mouse-file file) (printf "4~n"))
  (define (box-select-file file)
    (cons-selection file))
  (define (left-mouse-dir file) 
    (clear-selection)
    (cons-selection file))
  (define (middle-mouse-dir file) (printf "7~n"))
  (define (right-mouse-dir file) (printf "8~n"))
  (define (double-mouse-dir file) (printf "9~n"))
  (define (box-select-dir file)
    (cons-selection file))
  (define filter-files all-files)
  (define sort-files dirs-first))