.\" dummy line
.TH DRSCHEME 1 "16 May 1996"
.UC 4
.SH NAME
DrScheme \- The Rice PLT Scheme programming environment
.SH SYNOPSIS
.B DrScheme
.SH DESCRIPTION
.I DrScheme
is an alias for drscheme that also removes most 
user-settable system limits (such as memory use limits).
.SH SEE ALSO
.BR drscheme(1)
