.TH tex2page 1 "2003-06-23"  \" last change

.SH NAME

TeX2page \- converts TeX documents to Web pages 

.SH SYNOPSIS

tex2page { --help | --version | \fIfilename\fP }

.SH DESCRIPTION

tex2page makes Web pages from LaTeX and plain-TeX
documents.  
.PP
The command
.RS
tex2page doc.tex
.RE
converts the TeX source file doc.tex to the HTML
file doc.html, with possibly some auxiliary HTML
files and some image files.  The argument
filename can be a full or relative pathname.  If the
latter, it is reckoned relative to the current
directory.  The extension may be omitted if it is .tex. 
.PP
In order to resolve cross-references, it may be
necessary to invoke tex2page a couple of times.
The log displayed on the console will inform you
if such is the case.  This log is also saved in the
file with the same basename as the input TeX file but
with extension .hlog.
.PP
If tex2page is called without an argument, or if the file
named by the argument doesn't exist,
tex2page prints a brief help message and exits.  
.PP
The complete documentation for tex2page is included in
the tex2page distribution, and may also be viewed on
the Web at 
.ce 1
http://www.ccs.neu.edu/~dorai/tex2page/tex2page-doc.html

.SH OPTIONS

tex2page can be called with the following options
instead of an argument filename.
.TP
--help
.br
Print help message and exit.
.TP
--version
.br
Print version information and exit.

.SH ENVIRONMENT

.TP
TEXINPUTS
.br
tex2page uses the same search path as TeX
to search for 
\einput and \eopenin files.  The default search path is
implementation-dependent but can be changed by setting 
the environment variable TEXINPUTS to a list of
colon-separated directories.  (If you wish to
merely prepend your list to the default list, end your
list with a colon.)  Add two trailing forward slashes
to any directory in TEXINPUTS that you want to
recursively search all subdirectories of.
.TP
TIIPINPUTS
.br
tex2page will use a search path specified in the
environment variable TIIPINPUTS
instead of TEXINPUTS, if TIIPINPUTS exists.
TIIPINPUTS  
does not support the double-slash mechanism of
\%TEXINPUTS.
.TP
TEXEDIT
.br
If tex2page encounters a fatal error in the document,
you can type e to edit the offending file (which may or
may not be the main input file) at the line containing
the error.  The editor call can be specified as a
string value (e.g., "vim\ +%d\ %s") 
assigned to the
environment variable TEXEDIT, with %d standing for the
line number and %s for the filename.  
.TP
EDITOR
.br
If TEXEDIT is not set, $EDITOR is chosen as the editor.
If \%EDITOR is also not set, "vi" is chosen as the
editor.  The editor is called with the arguments
"\ +\fIn\fP \fIf\fP", where \fIn\fP is the line
number and \fIf\fP is the filename.

.SH FILES

.TP 
\fIjobname\fP.hdir, .tex2page.hdir, ~/.tex2page.hdir
.br
By default, tex2page generates its output HTML files in
the current directory.  You can specify a different
directory by naming it in the file \fIjobname\fP.hdir
(where \fIjobname\fP is the basename of the input
document) in the current directory, the file
\&.tex2page.hdir in the current directory, or the file
\&.tex2page.hdir in your home directory.  The first of
these files that exists is considered.
.IP
The name in the .hdir file can be, or contain, the TeX
control-sequence \ejobname, which expands to the
basename of the input file.
.PP
.TP 
\fIjobname\fP.t2p
.br
Before processing a TeX source file whose basename is
\fIjobname\fP, tex2page will automatically load the file 
\fIjobname\fP.t2p, if it exists.  \fIjobname\fP.t2p is a good place
to put macros that are specific to the HTML version of 
the document.

.SH SYSTEM REQUIREMENTS

tex2page runs on Scheme or Common Lisp.  It may 
also make
use of the following programs: BibTeX, MakeIndex,
Ghostscript, Dvips, MetaPost, and the NetPBM library.
.PP
Out of the box, tex2page runs in MzScheme, but
the distribution includes configuration information
to allow tex2page to run on a variety of Scheme 
and Common Lisp implementations.

.SH BUGS

Email to dorai <at> ccs <dot> neu <dot> edu.

.SH SEE ALSO

tex(1), latex(1), mzscheme(1), bibtex(1),
makeindex(1L), mpost(1)

.SH COPYRIGHT

Copyright (c) 1997-2003, Dorai Sitaram.
All rights reserved.
.PP
Permission to distribute and use this work for any
purpose is hereby granted provided this copyright
notice is included in the copy.  This work is provided
as is, with no warranty of any kind.
