(define-signature mred:wx^
  (wx:const-k-numpad9
   wx:const-msnipbox-xmargin
   wx:const-needed-sb
   wx:const-stipple
   wx:const-k-numpad8
   wx:const-event-type-set-focus
   wx:const-vertical-hatch
   wx:const-k-numpad7
   wx:const-sb-mask
   wx:const-cross-hatch
   wx:const-k-numpad6
   wx:const-event-type-text-enter-command
   wx:const-snip-uses-buffer-path
   wx:const-extended
   wx:const-mcanvas-hide-v-scroll
   wx:const-solid
   wx:const-k-numpad5
   wx:const-snip-height-depends-on-y
   wx:the-clipboard
   wx:const-transparent
   wx:const-k-numpad4
   wx:const-event-type-radiobox-command
   wx:const-mcanvas-hide-h-scroll
   wx:const-k-numpad3
   wx:const-snip-width-depends-on-y
   wx:const-single
   wx:const-k-numpad2
   wx:const-event-type-slider-command
   wx:const-mcanvas-no-v-scroll
   wx:const-k-numpad1
   wx:const-multiple-mask
   wx:const-k-numpad0
   wx:const-event-type-menu-command
   wx:const-mcanvas-no-h-scroll
   wx:const-k-help
   wx:const-snip-width-depends-on-x
   wx:const-k-insert
   wx:const-event-type-multitext-command
   wx:const-k-snapshot
   wx:const-snip-handles-events
   wx:const-snip-height-depends-on-x
   wx:const-k-execute
   wx:const-event-type-text-command
   wx:the-style-list
   wx:const-overwrite-prompt
   wx:const-k-print
   wx:const-snip-hard-newline
   wx:the-colour-database
   wx:const-k-select
   wx:const-event-type-listbox-command
   wx:const-icon-information
   wx:const-k-down
   wx:const-snip-can-append
   wx:const-k-right
   wx:const-event-type-choice-command
   wx:const-icon-exclamation
   wx:const-k-up
   wx:const-k-left
   wx:const-event-type-checkbox-command
   wx:get-single-choice-index
   wx:const-k-home
   wx:hourglass-cursor
   wx:const-k-end
   wx:const-event-type-button-command
   wx:const-hide-readonly
   wx:get-single-choice-data
   wx:the-font-list
   wx:const-k-next
   wx:const-save
   wx:const-k-prior
   wx:const-type-mouse-event
   wx:const-open
   wx:make-meta-file-placeable
   wx:const-k-capital
   wx:const-dir
   wx:const-k-pause
   wx:const-type-command-event
   wx:const-file
   wx:get-print-preview-command
   wx:const-slant
   wx:const-k-menu
   wx:const-default-dialog-style
   wx:const-centre
   wx:const-italic
   wx:const-k-control
   wx:const-event-type-scroll-thumbtrack
   wx:const-center
   wx:get-printer-orientation
   wx:const-bold
   wx:const-k-shift
   wx:const-icon-mask
   wx:const-light
   wx:const-k-clear
   wx:const-event-type-scroll-pagedown
   wx:const-icon-asterisk
   wx:get-printer-translation
   wx:const-normal
   wx:const-k-mbutton
   wx:const-icon-stop
   wx:const-teletype
   wx:const-k-cancel
   wx:const-event-type-scroll-pageup
   wx:const-icon-question
   wx:set-printer-preview-command
   wx:const-modern
   wx:const-k-rbutton
   wx:const-icon-hand
   wx:const-swiss
   wx:const-k-lbutton
   wx:const-event-type-scroll-linedown
   wx:const-align-center
   wx:const-no
   wx:set-printer-orientation
   wx:const-script
   wx:const-k-start
   wx:const-align-bottom
   wx:const-yes
   wx:const-roman
   wx:const-k-delete
   wx:const-event-type-scroll-lineup
   wx:const-edit-buffer
   wx:const-cancel
   wx:set-printer-translation
   wx:const-decorative
   wx:const-k-space
   wx:const-change-family
   wx:const-yes-no
   wx:const-default
   wx:const-k-escape
   wx:const-event-type-scroll-bottom
   wx:const-change-smaller
   wx:const-ok
   wx:const-k-return
   wx:const-k-tab
   wx:const-change-bigger
   wx:concat-files
   wx:const-k-back
   wx:const-change-italic
   wx:copy-file
   wx:the-font-name-directory
   wx:const-cursor-spraycan
   wx:const-change-bold
   wx:get-temp-file-name
   wx:get-host-name
   wx:const-change-size
   wx:get-email-address
   wx:const-cursor-sizenwse
   wx:const-change-weight
   wx:get-user-id
   wx:const-change-style
   wx:get-user-name
   wx:const-cursor-sizenesw
   wx:const-change-normal
   wx:get-media-print-margin
   wx:string-match?
   wx:const-change-nothing
   wx:set-display
   wx:const-cursor-right-button
   wx:const-base
   wx:set-media-print-margin
   wx:get-display-name
   wx:file-selector
   wx:const-cursor-question-arrow
   wx:read-media-global-header
   wx:message-box
   wx:const-vertical
   wx:get-text-from-user
   wx:const-horizontal
   wx:const-cursor-point-right
   wx:const-bitmap-type-bmp
   wx:read-media-global-footer
   wx:get-multiple-choice
   wx:const-both
   wx:get-single-choice
   wx:const-default-frame
   wx:const-cursor-point-left
   wx:write-media-global-header
   wx:colour-display?
   wx:const-resize-border
   wx:display-depth
   wx:const-resize-box
   wx:const-cursor-painr-brush
   wx:exit
   wx:write-media-global-footer
   wx:set-cursor
   wx:const-maximize-box
   wx:const-type-key-event
   wx:get-printer-command
   wx:const-minimize-box
   wx:const-cursor-no-entry
   wx:add-media-buffer-functions
   wx:get-printer-file
   wx:const-system-menu
   wx:const-snip-anchored
   wx:get-printer-mode
   wx:const-thick-frame
   wx:const-cursor-middle-button
   wx:const-snip-invisible
   wx:add-media-editor-functions
   wx:get-printer-options
   wx:const-mdi-child
   wx:const-snip-is-text
   wx:get-printer-scaling
   wx:const-mdi-parent
   wx:const-cursor-magnifier
   wx:const-snip-newline
   wx:add-media-pasteboard-functions
   wx:get-print-paper-name
   wx:const-sdi
   wx:get-afm-path
   wx:const-maximize
   wx:const-cursor-left-button
   wx:media-set-x-selection-mode
   wx:set-printer-command
   wx:const-minimize
   wx:set-printer-file
   wx:const-iconize
   wx:const-cursor-bullseye
   wx:get-the-snip-class-list
   wx:set-printer-mode
   wx:const-stay-on-top
   wx:set-printer-options
   wx:set-printer-scaling
   wx:set-print-paper-name
   wx:const-horizontal-hatch
   wx:get-the-buffer-data-class-list
   wx:set-afm-path
   wx:new-id
   wx:const-fdiagonal-hatch
   wx:const-pasteboard-buffer
   wx:register-id
   wx:const-crossdiag-hatch
   wx:begin-busy-cursor
   wx:const-mm-text
   wx:is-busy?
   wx:const-bdiagonal-hatch
   wx:const-mm-lometric
   wx:end-busy-cursor
   wx:const-hscroll
   wx:const-mm-metric
   wx:display-size
   wx:const-mm-points
   wx:find-window-by-label
   wx:const-mm-twips
   wx:find-window-by-name
   wx:const-xor
   wx:const-local-select
   wx:strip-menu-codes
   wx:const-src-invert
   wx:const-x-select
   wx:get-free-memory
   wx:const-password
   wx:const-set
   wx:const-default-select
   wx:const-break-for-user-2
   wx:get-resource
   wx:const-or-reverse
   wx:const-break-for-line
   wx:write-resource
   wx:const-or-invert
   wx:const-snip-after
   wx:const-break-for-user-1
   wx:bell
   wx:const-pos-use-minus-one
   wx:const-or
   wx:const-snip-before
   wx:yield
   wx:const-no-op
   wx:const-media-ff-copy
   wx:const-break-for-selection
   wx:flush-display
   duplicate-key-event
   wx:const-size-use-exsiting
   wx:const-nor
   wx:const-media-ff-same
   duplicate-mouse-event
   wx:const-nand
   wx:const-media-ff-text
   wx:const-break-for-caret
   wx:const-size-auto-height
   wx:const-invert
   wx:const-media-ff-std
   wx:const-equiv
   wx:const-media-ff-guess
   wx:const-snip-after-or-null
   wx:const-size-auto-width
   wx:const-copy
   wx:const-move-word
   wx:const-allow-auto-resize
   wx:const-clear
   wx:const-move-page
   wx:const-snip-before-or-null
   wx:const-and-reverse
   wx:const-move-line
   wx:const-tiny-caption-vert
   wx:const-and-invert
   wx:const-move-simple
   wx:const-snip-draw-show-inactive-caret
   wx:const-and
   wx:const-edit-kill
   wx:const-tiny-caption-horiz
   wx:const-winding-rule
   wx:const-edit-paste
   wx:const-snip-draw-show-caret
   wx:const-cursor-watch
   wx:const-multiple
   wx:const-oddeven-rule
   wx:const-edit-copy
   wx:const-cursor-wait
   wx:const-edit-cut
   wx:const-snip-draw-no-caret
   wx:const-cursor-sizing
   wx:const-edit-clear
   wx:const-cursor-sizewe
   wx:const-k-numlock
   wx:const-event-type-right-dclick
   wx:const-edit-redo
   wx:const-media-ff-text-force-cr
   wx:const-cursor-sizens
   wx:const-k-f24
   wx:const-edit-undo
   wx:const-cursor-pencil
   wx:const-k-f23
   wx:const-event-type-middle-dclick
   wx:const-edit-select-all
   wx:const-cursor-ibeam
   wx:const-k-f22
   wx:const-cursor-hand
   wx:const-k-f21
   wx:const-event-type-left-dclick
   wx:const-edit-insert-image
   wx:const-cursor-cross
   wx:const-k-f20
   wx:const-change-normal-colour
   wx:const-cursor-char
   wx:const-k-f19
   wx:const-event-type-leave-window
   wx:const-size-auto
   wx:const-edit-insert-graphic-box
   wx:const-cursor-arrow
   wx:const-k-f18
   wx:const-change-alignment
   wx:const-k-f17
   wx:const-event-type-enter-window
   wx:const-edit-insert-text-box
   wx:const-k-f16
   wx:const-change-toggle-underline
   wx:const-bitmap-type-pict-resource
   wx:the-pen-list
   wx:const-k-f15
   wx:const-event-type-motion
   wx:const-k-f14
   wx:const-change-toggle-weight
   wx:const-bitmap-type-pict
   wx:const-k-f13
   wx:const-event-type-right-up
   wx:const-k-f12
   wx:const-change-toggle-style
   wx:const-bitmap-type-xpm
   wx:const-dot-dash
   wx:const-k-f11
   wx:const-event-type-right-down
   wx:const-short-dash
   wx:const-k-f10
   wx:const-change-underline
   wx:const-bitmap-type-xbm
   wx:const-long-dash
   wx:const-k-f9
   wx:const-event-type-middle-up
   wx:const-msnipbox-xinset
   wx:const-dot
   wx:const-k-f8
   wx:const-bitmap-type-gif
   wx:const-cap-butt
   wx:const-k-f7
   wx:const-event-type-middle-down
   wx:const-cap-projecting
   wx:const-k-f6
   wx:const-bitmap-type-bmp-resource
   wx:const-readonly
   wx:const-align-top
   wx:const-cap-round
   wx:const-k-f5
   wx:const-event-type-left-up
   wx:const-backingstore
   wx:const-join-round
   wx:const-k-f4
   wx:const-editable
   wx:const-retained
   wx:const-join-miter
   wx:const-k-f3
   wx:const-event-type-left-down
   wx:const-border
   wx:const-caption
   wx:the-media-wordbreak-map
   wx:const-join-bevel
   wx:const-k-f2
   wx:const-bitmap-discard-colourmap
   wx:const-k-f1
   wx:const-event-type-char
   wx:const-k-divide
   wx:const-msnipbox-yinset
   wx:const-bitmap-type-default
   wx:const-vscroll
   wx:const-k-decimal
   wx:const-event-type-virt-listbox-command
   wx:const-k-subtract
   wx:const-event-type-scroll-top
   wx:the-brush-list
   wx:const-k-separator
   wx:const-event-type-scrollbar-command
   wx:const-process-enter
   wx:const-k-add
   wx:const-msnipbox-ymargin
   wx:const-always-sb
   wx:const-k-multiply
   wx:const-event-type-kill-focus
   wx:object%
   wx:dc%
   wx:keymap%
   wx:menu%
   wx:brush-list%
   wx:clipboard-client%
   wx:event%
   wx:printer-dc%
   wx:window%
   wx:canvas%
   wx:snip-class-list%
   wx:item%
   wx:canvas-dc%
   wx:media-stream-out-base%
   wx:panel%
   wx:style-list%
   wx:snip%
   wx:media-stream-in-base%
   wx:slider%
   wx:list-box%
   wx:media-stream-out-string-base%
   wx:group-box%
   wx:choice%
   wx:clipboard%
   wx:memory-dc%
   wx:media-snip%
   wx:message%
   wx:cursor%
   wx:button%
   wx:radio-box%
   wx:media-stream-in-string-base%
   wx:timer%
   wx:text-window%
   wx:dialog-box%
   wx:brush%
   wx:snip-class%
   wx:media-buffer%
   wx:text%
   wx:int-point%
   wx:media-edit%
   wx:meta-file%
   wx:pen%
   wx:point%
   wx:multi-text%
   wx:font%
   wx:pen-list%
   wx:media-stream-out%
   wx:media-wordbreak-map%
   wx:style%
   wx:tool-bar%
   wx:gauge%
   wx:snip-admin%
   wx:key-event%
   wx:colour-database%
   wx:media-stream-in%
   wx:colour-map%
   wx:frame%
   wx:image-snip%
   wx:colour%
   wx:style-delta%
   wx:text-snip%
   wx:add-colour%
   wx:tab-snip%
   wx:buffer-data-class-list%
   wx:mult-colour%
   wx:media-canvas%
   wx:command-event%
   wx:media-admin%
   wx:mouse-event%
   wx:post-script-dc%
   wx:meta-file-dc%
   wx:bitmap%
   wx:menu-bar%
   wx:font-list%
   wx:button-bar%
   wx:buffer-data%
   wx:check-box%
   wx:tool-bar-tool%
   wx:buffer-data-class%
   wx:media-pasteboard%
   wx:font-name-directory%
   wx:icon%))