(define-signature mred:wx^
  (wx:set-afm-path
  wx:const-event-type-scroll-bottom
  wx:const-snip-newline
  wx:const-default-dialog-style
  wx:new-id
  wx:register-id
  wx:const-event-type-scroll-top
  wx:const-local-select
  wx:the-font-name-directory
  wx:const-x-select
  wx:begin-busy-cursor
  wx:const-mm-text
  wx:const-default-select
  wx:is-busy?
  wx:const-cursor-spraycan
  wx:const-mm-lometric
  wx:const-break-for-line
  wx:end-busy-cursor
  wx:const-mm-metric
  wx:const-snip-after
  wx:display-size
  wx:const-cursor-sizenwse
  wx:const-mm-points
  wx:const-snip-before
  wx:find-window-by-label
  wx:const-mm-twips
  wx:const-media-ff-copy
  wx:find-window-by-name
  wx:const-cursor-sizenesw
  wx:const-colour
  wx:const-media-ff-same
  wx:strip-menu-codes
  wx:const-xor
  wx:const-media-ff-text
  wx:get-free-memory
  wx:const-cursor-right-button
  wx:const-src-invert
  wx:const-media-ff-std
  wx:get-resource
  wx:const-set
  wx:const-media-ff-guess
  wx:write-resource
  wx:const-cursor-question-arrow
  wx:const-or-reverse
  wx:const-move-word
  wx:const-or-invert
  wx:const-move-page
  wx:yield
  wx:const-cursor-point-right
  duplicate-key-event
  wx:const-or
  wx:const-move-line
  wx:flush-display
  duplicate-mouse-event
  wx:const-no-op
  wx:const-move-simple
  wx:const-cursor-point-left
  wx:const-nor
  wx:const-edit-kill
  wx:const-nand
  wx:const-edit-paste
  wx:const-cursor-painr-brush
  wx:const-invert
  wx:const-edit-copy
  wx:const-equiv
  wx:const-edit-cut
  wx:const-cursor-no-entry
  wx:const-copy
  wx:const-edit-clear
  wx:const-clear
  wx:const-edit-redo
  wx:const-cursor-middle-button
  wx:const-and-reverse
  wx:const-size-auto
  wx:const-edit-undo
  wx:const-and-invert
  wx:const-process-enter
  wx:const-cursor-magnifier
  wx:const-and
  wx:const-always-sb
  wx:const-cursor-watch
  wx:const-winding-rule
  wx:const-bitmap-type-pict-resource
  wx:const-needed-sb
  wx:const-cursor-wait
  wx:const-cursor-left-button
  wx:const-oddeven-rule
  wx:const-sb-mask
  wx:const-cursor-sizing
  wx:const-k-scroll
  wx:const-bitmap-type-pict
  wx:const-extended
  wx:get-media-print-margin
  wx:const-cursor-sizewe
  wx:const-cursor-bullseye
  wx:const-k-numlock
  wx:const-multiple
  wx:const-cursor-sizens
  wx:const-k-f24
  wx:const-bitmap-type-xpm
  wx:const-single
  wx:set-media-print-margin
  wx:const-pos-use-minus-one
  wx:const-cursor-pencil
  wx:const-k-f23
  wx:const-multiple-mask
  wx:const-cursor-ibeam
  wx:const-k-f22
  wx:const-bitmap-type-xbm
  wx:read-media-global-header
  wx:const-cursor-hand
  wx:const-horizontal-hatch
  wx:const-k-f21
  wx:const-size-use-exsiting
  wx:const-cursor-cross
  wx:const-k-f20
  wx:const-bitmap-type-gif
  wx:read-media-global-footer
  wx:const-cursor-char
  wx:const-fdiagonal-hatch
  wx:const-k-f19
  wx:const-cursor-arrow
  wx:const-k-f18
  wx:const-bitmap-type-bmp-resource
  wx:write-media-global-header
  wx:const-size-auto-height
  wx:const-crossdiag-hatch
  wx:const-k-f17
  wx:const-k-f16
  wx:const-bitmap-type-bmp
  wx:write-media-global-footer
  wx:the-pen-list
  wx:const-bdiagonal-hatch
  wx:const-k-f15
  wx:const-editable
  wx:const-size-auto-width
  wx:const-k-f14
  wx:const-bitmap-discard-colourmap
  wx:add-media-buffer-functions
  wx:const-k-f13
  wx:const-dot-dash
  wx:const-k-f12
  wx:const-bitmap-type-default
  wx:add-media-editor-functions
  wx:const-short-dash
  wx:const-k-f11
  wx:const-long-dash
  wx:const-k-f10
  wx:add-media-pasteboard-functions
  wx:const-dot
  wx:const-k-f9
  wx:const-cap-butt
  wx:const-k-f8
  wx:media-set-x-selection-mode
  wx:const-cap-projecting
  wx:const-k-f7
  wx:const-cap-round
  wx:const-join-round
  wx:const-k-f6
  wx:the-style-list
  wx:get-the-snip-class-list
  wx:const-join-miter
  wx:const-k-f5
  wx:const-snip-draw-show-inactive-caret
  wx:const-join-bevel
  wx:const-k-f4
  wx:const-k-f3
  wx:const-backingstore
  wx:const-snip-draw-show-caret
  wx:const-k-f2
  wx:the-clipboard
  wx:const-retained
  wx:get-the-buffer-data-class-list
  wx:const-k-f1
  wx:const-allow-auto-resize
  wx:const-border
  wx:const-snip-draw-no-caret
  wx:exit
  wx:const-k-divide
  wx:bell
  wx:const-focus-immediate
  wx:const-change-normal-colour
  wx:the-brush-list
  wx:const-k-decimal
  wx:const-tiny-caption-vert
  wx:const-media-ff-text-force-cr
  wx:const-k-subtract
  wx:const-pasteboard-buffer
  wx:const-k-separator
  wx:const-tiny-caption-horiz
  wx:const-change-alignment
  wx:const-edit-select-all
  wx:const-stipple
  wx:const-k-add
  wx:const-vertical-hatch
  wx:const-k-multiply
  wx:const-edit-insert-image
  wx:const-cross-hatch
  wx:const-k-numpad9
  wx:const-change-toggle-underline
  wx:const-solid
  wx:const-k-numpad8
  wx:const-event-type-right-dclick
  wx:const-edit-insert-graphic-box
  wx:const-transparent
  wx:const-k-numpad7
  wx:const-k-numpad6
  wx:const-event-type-middle-dclick
  wx:const-change-toggle-weight
  wx:const-edit-insert-text-box
  wx:const-k-numpad5
  wx:const-k-numpad4
  wx:const-event-type-left-dclick
  wx:const-k-numpad3
  wx:const-change-toggle-style
  wx:const-k-numpad2
  wx:const-event-type-leave-window
  wx:const-k-numpad1
  wx:const-align-center
  wx:const-k-numpad0
  wx:const-event-type-enter-window
  wx:const-align-bottom
  wx:const-k-help
  wx:const-align-top
  wx:const-k-insert
  wx:const-event-type-motion
  wx:const-change-family
  wx:the-colour-database
  wx:const-k-snapshot
  wx:const-change-smaller
  wx:const-k-execute
  wx:const-event-type-right-up
  wx:const-change-bigger
  wx:const-k-print
  wx:const-change-italic
  wx:const-break-for-user-2
  wx:const-k-select
  wx:const-event-type-right-down
  wx:const-change-bold
  wx:const-k-down
  wx:const-change-size
  wx:const-break-for-user-1
  wx:hourglass-cursor
  wx:const-k-right
  wx:const-event-type-middle-up
  wx:const-change-weight
  wx:const-hide-readonly
  wx:the-media-wordbreak-map
  wx:const-k-up
  wx:const-change-style
  wx:const-break-for-selection
  wx:const-save
  wx:the-font-list
  wx:const-k-left
  wx:const-event-type-middle-down
  wx:const-change-normal
  wx:const-open
  wx:const-k-home
  wx:const-change-nothing
  wx:const-break-for-caret
  wx:const-ps-printer
  wx:const-k-end
  wx:const-event-type-left-up
  wx:const-base
  wx:const-ps-file
  wx:const-slant
  wx:const-k-next
  wx:const-snip-after-or-null
  wx:const-ps-preview
  wx:const-italic
  wx:const-k-prior
  wx:const-event-type-left-down
  wx:const-ps-landscape
  wx:const-bold
  wx:const-k-capital
  wx:const-snip-before-or-null
  wx:const-ps-portrait
  wx:const-light
  wx:const-k-pause
  wx:const-event-type-char
  wx:const-focus-global
  wx:const-centre
  wx:const-normal
  wx:const-k-menu
  wx:const-focus-display
  wx:const-center
  wx:const-system
  wx:const-k-control
  wx:const-event-type-virt-listbox-command
  wx:const-edit-buffer
  wx:const-change-underline
  wx:const-icon-mask
  wx:const-teletype
  wx:const-k-shift
  wx:const-icon-asterisk
  wx:const-modern
  wx:const-k-clear
  wx:const-event-type-scrollbar-command
  wx:const-icon-stop
  wx:const-swiss
  wx:const-k-mbutton
  wx:const-icon-question
  wx:const-script
  wx:const-k-cancel
  wx:const-event-type-kill-focus
  wx:const-icon-hand
  wx:const-mcanvas-hide-v-scroll
  wx:const-roman
  wx:const-k-rbutton
  wx:const-readonly
  wx:const-no
  wx:const-decorative
  wx:const-k-lbutton
  wx:const-event-type-set-focus
  wx:const-yes
  wx:const-mcanvas-hide-h-scroll
  wx:const-default
  wx:const-k-start
  wx:const-cancel
  wx:const-k-delete
  wx:const-event-type-text-enter-command
  wx:const-caption
  wx:const-yes-no
  wx:const-mcanvas-no-v-scroll
  wx:const-k-space
  wx:const-ok
  wx:const-hscroll
  wx:const-k-escape
  wx:const-event-type-radiobox-command
  wx:const-msnipbox-yinset
  wx:concat-files
  wx:const-mcanvas-no-h-scroll
  wx:const-k-return
  wx:const-vscroll
  wx:copy-file
  wx:const-k-tab
  wx:const-event-type-slider-command
  wx:const-msnipbox-xinset
  wx:get-temp-file-name
  wx:const-password
  wx:const-k-back
  wx:get-host-name
  wx:const-event-type-menu-command
  wx:const-msnipbox-ymargin
  wx:get-email-address
  wx:get-user-id
  wx:const-event-type-multitext-command
  wx:const-msnipbox-xmargin
  wx:get-user-name
  wx:string-match?
  wx:const-event-type-text-command
  wx:const-snip-uses-buffer-path
  wx:set-display
  wx:const-overwrite-prompt
  wx:get-display-name
  wx:const-vertical
  wx:const-event-type-listbox-command
  wx:const-snip-height-depends-on-y
  wx:file-selector
  wx:const-icon-information
  wx:const-horizontal
  wx:message-box
  wx:const-both
  wx:const-event-type-choice-command
  wx:const-snip-width-depends-on-y
  wx:get-text-from-user
  wx:const-icon-exclamation
  wx:const-default-frame
  wx:get-multiple-choice
  wx:const-resize-border
  wx:const-event-type-checkbox-command
  wx:const-snip-height-depends-on-x
  wx:get-single-choice
  wx:get-single-choice-index
  wx:const-resize-box
  wx:colour-display?
  wx:const-maximize-box
  wx:const-event-type-button-command
  wx:const-snip-width-depends-on-x
  wx:display-depth
  wx:get-single-choice-data
  wx:const-minimize-box
  wx:set-cursor
  wx:const-system-menu
  wx:const-type-mouse-event
  wx:const-snip-handles-events
  wx:get-printer-command
  wx:make-meta-file-placeable
  wx:const-thick-frame
  wx:const-type-key-event
  wx:get-printer-file
  wx:const-mdi-child
  wx:const-type-command-event
  wx:const-snip-hard-newline
  wx:get-printer-mode
  wx:get-printer-preview-command
  wx:const-mdi-parent
  wx:get-printer-options
  wx:const-sdi
  wx:const-event-type-scroll-thumbtrack
  wx:const-snip-can-append
  wx:get-printer-scaling
  wx:get-printer-orientation
  wx:const-maximize
  wx:get-print-paper-name
  wx:const-minimize
  wx:const-event-type-scroll-pagedown
  wx:get-afm-path
  wx:get-printer-translation
  wx:const-iconize
  wx:set-printer-command
  wx:const-stay-on-top
  wx:const-event-type-scroll-pageup
  wx:set-printer-file
  wx:set-printer-preview-command
  wx:set-printer-mode
  wx:const-event-type-scroll-linedown
  wx:set-printer-options
  wx:set-printer-orientation
  wx:const-snip-anchored
  wx:set-printer-scaling
  wx:const-event-type-scroll-lineup
  wx:const-snip-invisible
  wx:set-print-paper-name
  wx:set-printer-translation
  wx:const-snip-is-text
  wx:object%
  wx:window%
  wx:item%
  wx:message%
  wx:canvas%
  wx:clipboard-client%
  wx:dc%
  wx:media-stream-in%
  wx:cursor%
  wx:media-stream-in-base%
  wx:list-box%
  wx:int-point%
  wx:brush%
  wx:mult-colour%
  wx:media-wordbreak-map%
  wx:panel%
  wx:point%
  wx:snip%
  wx:bitmap%
  wx:font%
  wx:style-list%
  wx:media-admin%
  wx:pen-list%
  wx:media-stream-in-string-base%
  wx:check-box%
  wx:media-stream-out-base%
  wx:gauge%
  wx:image-snip%
  wx:menu-bar%
  wx:colour-database%
  wx:text-snip%
  wx:colour-map%
  wx:tab-snip%
  wx:colour%
  wx:event%
  wx:pen%
  wx:frame%
  wx:buffer-data-class-list%
  wx:canvas-media-admin%
  wx:font-list%
  wx:menu%
  wx:choice%
  wx:keymap%
  wx:style%
  wx:canvas-dc%
  wx:command-event%
  wx:snip-admin%
  wx:snip-class-list%
  wx:text-window%
  wx:media-stream-out-string-base%
  wx:post-script-dc%
  wx:style-delta%
  wx:font-name-directory%
  wx:button%
  wx:add-colour%
  wx:clipboard%
  wx:icon%
  wx:brush-list%
  wx:key-event%
  wx:media-snip-media-admin%
  wx:media-snip%
  wx:media-canvas%
  wx:meta-file-dc%
  wx:timer%
  wx:memory-dc%
  wx:mouse-event%
  wx:printer-dc%
  wx:buffer-data%
  wx:meta-file%
  wx:text%
  wx:slider%
  wx:snip-class%
  wx:media-buffer%
  wx:buffer-data-class%
  wx:media-stream-out%
  wx:multi-text%
  wx:media-pasteboard%
  wx:media-edit%
  wx:radio-box%
  wx:dialog-box%))

