/********************************************
 ** Do not edit this file!
 ** This file is generated from lightning.ssc,
 ** to make changes, edit that file and
 ** run it to generate an updated version
 ** of this file.
 ********************************************/


#include "escheme.h"
#include <lightning.h>
#include <sys/mman.h>

/*****************************************************************************/
/* Main code */

#define MAX_INSTR_SIZE 10

inline Scheme_Object *assq(Scheme_Object *x, Scheme_Object *l)
{
  Scheme_Object *args[2];
  args[0] = x;
  args[1] = l;
  return _scheme_apply(scheme_builtin_value("assq"), 2, args);
}

#define JIT_KIND_R (1<<16)
#define JIT_KIND_I (2<<16)

#define JIT_TYPE_C    1
#define JIT_TYPE_UC   2
#define JIT_TYPE_S    3
#define JIT_TYPE_US   4
#define JIT_TYPE_I    5
#define JIT_TYPE_UI   6
#define JIT_TYPE_L    7
#define JIT_TYPE_UL   8
#define JIT_TYPE_P    9
#define JIT_TYPE_F  256
#define JIT_TYPE_D  257

static Scheme_Object *c_sym;
static Scheme_Object *uc_sym;
static Scheme_Object *s_sym;
static Scheme_Object *us_sym;
static Scheme_Object *i_sym;
static Scheme_Object *ui_sym;
static Scheme_Object *l_sym;
static Scheme_Object *ul_sym;
static Scheme_Object *p_sym;
static Scheme_Object *f_sym;
static Scheme_Object *d_sym;

inline int mzjit_get_type(const Scheme_Object *sym)
{
  if      (SAME_OBJ(sym,c_sym)) return JIT_TYPE_C;
  else if (SAME_OBJ(sym,uc_sym)) return JIT_TYPE_UC;
  else if (SAME_OBJ(sym,s_sym)) return JIT_TYPE_S;
  else if (SAME_OBJ(sym,us_sym)) return JIT_TYPE_US;
  else if (SAME_OBJ(sym,i_sym)) return JIT_TYPE_I;
  else if (SAME_OBJ(sym,ui_sym)) return JIT_TYPE_UI;
  else if (SAME_OBJ(sym,l_sym)) return JIT_TYPE_L;
  else if (SAME_OBJ(sym,ul_sym)) return JIT_TYPE_UL;
  else if (SAME_OBJ(sym,p_sym)) return JIT_TYPE_P;
  else if (SAME_OBJ(sym,f_sym)) return JIT_TYPE_F;
  else if (SAME_OBJ(sym,d_sym)) return JIT_TYPE_D;
  scheme_signal_error("jit-proc: got a bad type spec %V", sym);
  return -1; /* shush the compiler */
}

static Scheme_Object *r_sym;
static Scheme_Object *v_sym;
static Scheme_Object *fpr_sym;
static Scheme_Object *r0_sym;
static Scheme_Object *r1_sym;
static Scheme_Object *r2_sym;
static Scheme_Object *v0_sym;
static Scheme_Object *v1_sym;
static Scheme_Object *v2_sym;
static Scheme_Object *fpr0_sym;
static Scheme_Object *fpr1_sym;
static Scheme_Object *fpr2_sym;
static Scheme_Object *fpr3_sym;
static Scheme_Object *fpr4_sym;
static Scheme_Object *fpr5_sym;
static Scheme_Object *sp_sym;
static Scheme_Object *fp_sym;
static Scheme_Object *ret_sym;

char *errorstr_bad_register_spec="jit-proc: got a bad register spec `%V' (%s)";

inline void mzjit_check_register(const Scheme_Object *sym, int floatp)
{
  char *s = SCHEME_SYM_VAL(sym);
  if (floatp) {
    if (s[0] == 'r' || s[0] == 'v')
      scheme_signal_error(errorstr_bad_register_spec, sym,
                          "expecting a floating point (`fpr') register");
  } else {
    if (!strncmp(s, "fpr", 3))
      scheme_signal_error(errorstr_bad_register_spec, sym,
                          "expecting an integer (`r' or `v') register");
  }
}

inline int mzjit_get_register(const Scheme_Object *reg, int floatp)
{
  if (SCHEME_PAIRP(reg)) {
    int r;
    Scheme_Object *rname;
    if (!SCHEME_PAIRP(SCHEME_CDR(reg))   ||
        !SCHEME_NULLP(SCHEME_CDDR(reg))  ||
        !SCHEME_SYMBOLP(SCHEME_CAR(reg)) ||
        !SCHEME_INTP(SCHEME_CADR(reg)))
      scheme_signal_error(errorstr_bad_register_spec, reg, "bad value");
    r = SCHEME_INT_VAL(SCHEME_CADR(reg));
    rname = SCHEME_CAR(reg);
    mzjit_check_register(rname,floatp);
    if (SAME_OBJ(rname,r_sym) && r < JIT_R_NUM) return JIT_R(r);
    else if (SAME_OBJ(rname,v_sym) && r < JIT_V_NUM) return JIT_V(r);
    else if (SAME_OBJ(rname,fpr_sym) && r < JIT_FPR_NUM) return JIT_FPR(r);
    else scheme_signal_error(errorstr_bad_register_spec, reg,
                             "unknown register, or too few registers");
  } else {
    mzjit_check_register(reg,floatp);
    if      (SAME_OBJ(reg,r0_sym)) return JIT_R0;
    else if (SAME_OBJ(reg,r1_sym)) return JIT_R1;
    else if (SAME_OBJ(reg,r2_sym)) return JIT_R2;
    else if (SAME_OBJ(reg,v0_sym)) return JIT_V0;
    else if (SAME_OBJ(reg,v1_sym)) return JIT_V1;
    else if (SAME_OBJ(reg,v2_sym)) return JIT_V2;
    else if (SAME_OBJ(reg,fpr0_sym)) return JIT_FPR0;
    else if (SAME_OBJ(reg,fpr1_sym)) return JIT_FPR1;
    else if (SAME_OBJ(reg,fpr2_sym)) return JIT_FPR2;
    else if (SAME_OBJ(reg,fpr3_sym)) return JIT_FPR3;
    else if (SAME_OBJ(reg,fpr4_sym)) return JIT_FPR4;
    else if (SAME_OBJ(reg,fpr5_sym)) return JIT_FPR5;
    else if (SAME_OBJ(reg,sp_sym)) return JIT_SP;
    else if (SAME_OBJ(reg,fp_sym)) return JIT_FP;
    else if (SAME_OBJ(reg,ret_sym)) return JIT_RET;
    else scheme_signal_error(errorstr_bad_register_spec, reg,
                             "unknown register");
  }
  return -1; /* shush the compiler */
}

inline void mzjit_set_label(Scheme_Object *sym,
                            Scheme_Object **bwdsp, Scheme_Object **fwdsp)
{
  Scheme_Object *a;
  jit_insn *r;
  a = assq(sym,*bwdsp);
  if (!SCHEME_FALSEP(a))
    scheme_signal_error("jit-proc: label already set: %V", sym);
  r = jit_get_label();
  *bwdsp = scheme_make_pair(scheme_make_pair(sym,scheme_make_cptr(r,NULL)),
                            *bwdsp);
  a = assq(sym,*fwdsp);
  if (!SCHEME_FALSEP(a)) {
    /* found fwd entries, patch them */
    SCHEME_CAR(a) = scheme_false;
    while ( !SCHEME_NULLP(a = SCHEME_CDR(a)) ) {
      r = SCHEME_CPTR_VAL(SCHEME_CAR(a));
      jit_patch(r);
    }
  }
}

void mzjit_set_fwd_label(Scheme_Object *sym, Scheme_Object **fwdsp,
                         jit_insn *fwd)
{
  Scheme_Object *a, *p;
  a = assq(sym,*fwdsp);
  p = scheme_make_pair(scheme_make_cptr(fwd,NULL),scheme_null);
  if (!SCHEME_FALSEP(a)) {
    SCHEME_CDR(p) = SCHEME_CDR(a);
    SCHEME_CDR(a) = p;
  } else {
    *fwdsp = scheme_make_pair(scheme_make_pair(sym,p), *fwdsp);
  }
}

inline jit_insn *mzjit_get_label(Scheme_Object *sym, Scheme_Object *bwds)
{
  Scheme_Object *a = assq(sym,bwds);
  if (!SCHEME_FALSEP(a)) return SCHEME_CPTR_VAL(SCHEME_CDR(a));
  else return NULL; /* return NULL if no label found */
}

inline long mzjit_get_imm(Scheme_Object *o)
{
  long i;
  if ( !scheme_get_int_val(o,&i) )
    scheme_signal_error("jit-proc: got a bad immediate %V", o);
  return i;
}

#define jit_finishi(sub) jit_finish(sub)

#define JIT_OP_add (scheme_make_integer(0))
#define JIT_OP_addx (scheme_make_integer(1))
#define JIT_OP_addc (scheme_make_integer(2))
#define JIT_OP_sub (scheme_make_integer(3))
#define JIT_OP_subx (scheme_make_integer(4))
#define JIT_OP_subc (scheme_make_integer(5))
#define JIT_OP_rsb (scheme_make_integer(6))
#define JIT_OP_mul (scheme_make_integer(7))
#define JIT_OP_hmul (scheme_make_integer(8))
#define JIT_OP_div (scheme_make_integer(9))
#define JIT_OP_mod (scheme_make_integer(10))
#define JIT_OP_and (scheme_make_integer(11))
#define JIT_OP_or (scheme_make_integer(12))
#define JIT_OP_xor (scheme_make_integer(13))
#define JIT_OP_lsh (scheme_make_integer(14))
#define JIT_OP_rsh (scheme_make_integer(15))
#define JIT_OP_neg (scheme_make_integer(16))
#define JIT_OP_not (scheme_make_integer(17))
#define JIT_OP_lt (scheme_make_integer(18))
#define JIT_OP_le (scheme_make_integer(19))
#define JIT_OP_gt (scheme_make_integer(20))
#define JIT_OP_ge (scheme_make_integer(21))
#define JIT_OP_eq (scheme_make_integer(22))
#define JIT_OP_ne (scheme_make_integer(23))
#define JIT_OP_unlt (scheme_make_integer(24))
#define JIT_OP_unle (scheme_make_integer(25))
#define JIT_OP_ungt (scheme_make_integer(26))
#define JIT_OP_unge (scheme_make_integer(27))
#define JIT_OP_uneq (scheme_make_integer(28))
#define JIT_OP_ltgt (scheme_make_integer(29))
#define JIT_OP_ord (scheme_make_integer(30))
#define JIT_OP_unord (scheme_make_integer(31))
#define JIT_OP_mov (scheme_make_integer(32))
#define JIT_OP_ext (scheme_make_integer(33))
#define JIT_OP_round (scheme_make_integer(34))
#define JIT_OP_trunc (scheme_make_integer(35))
#define JIT_OP_floor (scheme_make_integer(36))
#define JIT_OP_ceil (scheme_make_integer(37))
#define JIT_OP_hton (scheme_make_integer(38))
#define JIT_OP_ntoh (scheme_make_integer(39))
#define JIT_OP_ld (scheme_make_integer(40))
#define JIT_OP_ldx (scheme_make_integer(41))
#define JIT_OP_st (scheme_make_integer(42))
#define JIT_OP_stx (scheme_make_integer(43))
#define JIT_OP_push (scheme_make_integer(44))
#define JIT_OP_pop (scheme_make_integer(45))
#define JIT_OP_prepare (scheme_make_integer(46))
#define JIT_OP_pusharg (scheme_make_integer(47))
#define JIT_OP_getarg (scheme_make_integer(48))
#define JIT_OP_blt (scheme_make_integer(49))
#define JIT_OP_ble (scheme_make_integer(50))
#define JIT_OP_bgt (scheme_make_integer(51))
#define JIT_OP_bge (scheme_make_integer(52))
#define JIT_OP_beq (scheme_make_integer(53))
#define JIT_OP_bne (scheme_make_integer(54))
#define JIT_OP_bms (scheme_make_integer(55))
#define JIT_OP_bmc (scheme_make_integer(56))
#define JIT_OP_boadd (scheme_make_integer(57))
#define JIT_OP_bosub (scheme_make_integer(58))
#define JIT_OP_call (scheme_make_integer(59))
#define JIT_OP_finish (scheme_make_integer(60))
#define JIT_OP_jmp (scheme_make_integer(61))
#define JIT_OP_jmpi (scheme_make_integer(62))
#define JIT_OP_prolog (scheme_make_integer(63))
#define JIT_OP_leaf (scheme_make_integer(64))
#define JIT_OP_ret (scheme_make_integer(65))
#define JIT_OP_retval (scheme_make_integer(66))
char *errorstr_wrong_args_num = "jit-proc: wrong number of arguments to `%V' expecting %d, got %V";
char *errorstr_bad_command_format = "jit-proc: bad format for `%V' in %V";

Scheme_Object *op_alist;

#define SCHEME_REGP(x) \
  ((SCHEME_SYMBOLP(x))||((SCHEME_PAIRP(x))&&(SCHEME_SYMBOLP(SCHEME_CAR(x)))))

size_t mzjit_make (Scheme_Object * list , char * code , size_t len)
{
  char * current_location = 0 ;
  Scheme_Object * p = list , * command , * pc , * operator , * a ;
  Scheme_Object *bwd_labels=scheme_null, *fwd_labels=scheme_null, *labelsym;
  int cmd_arg_num, operator_id;
  int type1, type2, kind, reg1=0, reg2=0, reg3=0, in;
  unsigned long imm=0;
  jit_insn *labeladdr, *patch=NULL;
  current_location = jit_set_ip(code).ptr;
  while (SCHEME_PAIRP(p)) {
    current_location = jit_get_ip().ptr;
    command = SCHEME_CAR(p);
    p = SCHEME_CDR(p);
    /* check the current block size */
    if ((((char*)current_location) - ((char*)code)) + MAX_INSTR_SIZE > len)
      return -1;
    if (SCHEME_SYMBOLP(command)) {
      mzjit_set_label(command, &bwd_labels, &fwd_labels);
      continue;
    }
    cmd_arg_num = scheme_proper_list_length(command) - 1;
    if ( cmd_arg_num < 0 )
      scheme_signal_error("jit-proc: got a bad command %V in %V",
                          command, list);
    operator = SCHEME_CAR(command);
    pc = SCHEME_CDR(command);
    a = assq(operator, op_alist);
    if (SCHEME_FALSEP(a))
      scheme_signal_error("jit-proc: unknown operator %V in %V",operator,list);
    operator_id = (int)(SCHEME_CDR(a));
    kind = type1 = type2 = 0;
    labelsym = NULL;
    switch (operator_id) {
    /* ========== Binary ALU operations ========== */
    case ((int)(JIT_OP_add)):
    case ((int)(JIT_OP_addx)):
    case ((int)(JIT_OP_addc)):
    case ((int)(JIT_OP_sub)):
    case ((int)(JIT_OP_subx)):
    case ((int)(JIT_OP_subc)):
    case ((int)(JIT_OP_rsb)):
    case ((int)(JIT_OP_mul)):
    case ((int)(JIT_OP_hmul)):
    case ((int)(JIT_OP_div)):
    case ((int)(JIT_OP_mod)):
    case ((int)(JIT_OP_and)):
    case ((int)(JIT_OP_or)):
    case ((int)(JIT_OP_xor)):
    case ((int)(JIT_OP_lsh)):
    case ((int)(JIT_OP_rsh)):
      if (cmd_arg_num != 4)
        scheme_signal_error(errorstr_wrong_args_num, operator, 4, pc);
      /* process `t' argument */
      type1 = (mzjit_get_type(SCHEME_CAR(pc)));
      pc = SCHEME_CDR(pc);
      /* process `r' argument */
      reg1 = mzjit_get_register(SCHEME_CAR(pc),(type1>=JIT_TYPE_F));
      pc = SCHEME_CDR(pc);
      /* process `r' argument */
      reg2 = mzjit_get_register(SCHEME_CAR(pc),(type1>=JIT_TYPE_F));
      pc = SCHEME_CDR(pc);
      /* process `r/i' argument */
      if (SCHEME_REGP(SCHEME_CAR(pc))) {
        reg3 = mzjit_get_register(SCHEME_CAR(pc),(type1>=JIT_TYPE_F));
        kind = JIT_KIND_R;
      } else {
        imm = mzjit_get_imm(SCHEME_CAR(pc));
        kind = JIT_KIND_I;
      }
      pc = SCHEME_CDR(pc);
      switch (operator_id) {
      case ((int)(JIT_OP_add)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_I): jit_addr_i(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UI): jit_addr_ui(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_L): jit_addr_l(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UL): jit_addr_ul(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_P): jit_addr_p(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_F): jit_addr_f(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_D): jit_addr_d(reg1,reg2,reg3); break;
        case (JIT_KIND_I | JIT_TYPE_I): jit_addi_i(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UI): jit_addi_ui(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_L): jit_addi_l(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UL): jit_addi_ul(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_P): jit_addi_p(reg1,reg2,imm); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_addx)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_I): jit_addxr_i(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UI): jit_addxr_ui(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_L): jit_addxr_l(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UL): jit_addxr_ul(reg1,reg2,reg3); break;
        case (JIT_KIND_I | JIT_TYPE_I): jit_addxi_i(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UI): jit_addxi_ui(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_L): jit_addxi_l(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UL): jit_addxi_ul(reg1,reg2,imm); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_addc)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_I): jit_addcr_i(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UI): jit_addcr_ui(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_L): jit_addcr_l(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UL): jit_addcr_ul(reg1,reg2,reg3); break;
        case (JIT_KIND_I | JIT_TYPE_I): jit_addci_i(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UI): jit_addci_ui(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_L): jit_addci_l(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UL): jit_addci_ul(reg1,reg2,imm); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_sub)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_I): jit_subr_i(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UI): jit_subr_ui(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_L): jit_subr_l(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UL): jit_subr_ul(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_P): jit_subr_p(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_F): jit_subr_f(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_D): jit_subr_d(reg1,reg2,reg3); break;
        case (JIT_KIND_I | JIT_TYPE_I): jit_subi_i(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UI): jit_subi_ui(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_L): jit_subi_l(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UL): jit_subi_ul(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_P): jit_subi_p(reg1,reg2,imm); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_subx)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_I): jit_subxr_i(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UI): jit_subxr_ui(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_L): jit_subxr_l(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UL): jit_subxr_ul(reg1,reg2,reg3); break;
        case (JIT_KIND_I | JIT_TYPE_I): jit_subxi_i(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UI): jit_subxi_ui(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_L): jit_subxi_l(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UL): jit_subxi_ul(reg1,reg2,imm); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_subc)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_I): jit_subcr_i(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UI): jit_subcr_ui(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_L): jit_subcr_l(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UL): jit_subcr_ul(reg1,reg2,reg3); break;
        case (JIT_KIND_I | JIT_TYPE_I): jit_subci_i(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UI): jit_subci_ui(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_L): jit_subci_l(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UL): jit_subci_ul(reg1,reg2,imm); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_rsb)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_I): jit_rsbr_i(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UI): jit_rsbr_ui(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_L): jit_rsbr_l(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UL): jit_rsbr_ul(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_P): jit_rsbr_p(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_F): jit_rsbr_f(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_D): jit_rsbr_d(reg1,reg2,reg3); break;
        case (JIT_KIND_I | JIT_TYPE_I): jit_rsbi_i(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UI): jit_rsbi_ui(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_L): jit_rsbi_l(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UL): jit_rsbi_ul(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_P): jit_rsbi_p(reg1,reg2,imm); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_mul)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_I): jit_mulr_i(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UI): jit_mulr_ui(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_L): jit_mulr_l(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UL): jit_mulr_ul(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_F): jit_mulr_f(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_D): jit_mulr_d(reg1,reg2,reg3); break;
        case (JIT_KIND_I | JIT_TYPE_I): jit_muli_i(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UI): jit_muli_ui(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_L): jit_muli_l(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UL): jit_muli_ul(reg1,reg2,imm); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_hmul)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_I): jit_hmulr_i(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UI): jit_hmulr_ui(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_L): jit_hmulr_l(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UL): jit_hmulr_ul(reg1,reg2,reg3); break;
        case (JIT_KIND_I | JIT_TYPE_I): jit_hmuli_i(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UI): jit_hmuli_ui(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_L): jit_hmuli_l(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UL): jit_hmuli_ul(reg1,reg2,imm); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_div)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_I): jit_divr_i(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UI): jit_divr_ui(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_L): jit_divr_l(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UL): jit_divr_ul(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_F): jit_divr_f(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_D): jit_divr_d(reg1,reg2,reg3); break;
        case (JIT_KIND_I | JIT_TYPE_I): jit_divi_i(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UI): jit_divi_ui(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_L): jit_divi_l(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UL): jit_divi_ul(reg1,reg2,imm); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_mod)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_I): jit_modr_i(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UI): jit_modr_ui(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_L): jit_modr_l(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UL): jit_modr_ul(reg1,reg2,reg3); break;
        case (JIT_KIND_I | JIT_TYPE_I): jit_modi_i(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UI): jit_modi_ui(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_L): jit_modi_l(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UL): jit_modi_ul(reg1,reg2,imm); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_and)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_I): jit_andr_i(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UI): jit_andr_ui(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_L): jit_andr_l(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UL): jit_andr_ul(reg1,reg2,reg3); break;
        case (JIT_KIND_I | JIT_TYPE_I): jit_andi_i(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UI): jit_andi_ui(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_L): jit_andi_l(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UL): jit_andi_ul(reg1,reg2,imm); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_or)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_I): jit_orr_i(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UI): jit_orr_ui(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_L): jit_orr_l(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UL): jit_orr_ul(reg1,reg2,reg3); break;
        case (JIT_KIND_I | JIT_TYPE_I): jit_ori_i(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UI): jit_ori_ui(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_L): jit_ori_l(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UL): jit_ori_ul(reg1,reg2,imm); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_xor)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_I): jit_xorr_i(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UI): jit_xorr_ui(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_L): jit_xorr_l(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UL): jit_xorr_ul(reg1,reg2,reg3); break;
        case (JIT_KIND_I | JIT_TYPE_I): jit_xori_i(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UI): jit_xori_ui(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_L): jit_xori_l(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UL): jit_xori_ul(reg1,reg2,imm); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_lsh)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_I): jit_lshr_i(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UI): jit_lshr_ui(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_L): jit_lshr_l(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UL): jit_lshr_ul(reg1,reg2,reg3); break;
        case (JIT_KIND_I | JIT_TYPE_I): jit_lshi_i(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UI): jit_lshi_ui(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_L): jit_lshi_l(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UL): jit_lshi_ul(reg1,reg2,imm); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_rsh)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_I): jit_rshr_i(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UI): jit_rshr_ui(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_L): jit_rshr_l(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UL): jit_rshr_ul(reg1,reg2,reg3); break;
        case (JIT_KIND_I | JIT_TYPE_I): jit_rshi_i(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UI): jit_rshi_ui(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_L): jit_rshi_l(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UL): jit_rshi_ul(reg1,reg2,imm); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      }
      break;
    /* ========== Unary ALU operations ========== */
    case ((int)(JIT_OP_neg)):
    case ((int)(JIT_OP_not)):
      if (cmd_arg_num != 3)
        scheme_signal_error(errorstr_wrong_args_num, operator, 3, pc);
      /* process `t' argument */
      type1 = (mzjit_get_type(SCHEME_CAR(pc)));
      pc = SCHEME_CDR(pc);
      /* process `r' argument */
      reg1 = mzjit_get_register(SCHEME_CAR(pc),(type1>=JIT_TYPE_F));
      pc = SCHEME_CDR(pc);
      /* process `r' argument */
      reg2 = mzjit_get_register(SCHEME_CAR(pc),(type1>=JIT_TYPE_F));
      pc = SCHEME_CDR(pc);
      switch (operator_id) {
      case ((int)(JIT_OP_neg)):
        switch (type1) {
        case (JIT_TYPE_I): jit_negr_i(reg1,reg2); break;
        case (JIT_TYPE_L): jit_negr_l(reg1,reg2); break;
        case (JIT_TYPE_F): jit_negr_f(reg1,reg2); break;
        case (JIT_TYPE_D): jit_negr_d(reg1,reg2); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_not)):
        switch (type1) {
        case (JIT_TYPE_I): jit_notr_i(reg1,reg2); break;
        case (JIT_TYPE_UI): jit_notr_ui(reg1,reg2); break;
        case (JIT_TYPE_L): jit_notr_l(reg1,reg2); break;
        case (JIT_TYPE_UL): jit_notr_ul(reg1,reg2); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      }
      break;
    /* ========== Compare instructions ========== */
    case ((int)(JIT_OP_lt)):
    case ((int)(JIT_OP_le)):
    case ((int)(JIT_OP_gt)):
    case ((int)(JIT_OP_ge)):
    case ((int)(JIT_OP_eq)):
    case ((int)(JIT_OP_ne)):
    case ((int)(JIT_OP_unlt)):
    case ((int)(JIT_OP_unle)):
    case ((int)(JIT_OP_ungt)):
    case ((int)(JIT_OP_unge)):
    case ((int)(JIT_OP_uneq)):
    case ((int)(JIT_OP_ltgt)):
    case ((int)(JIT_OP_ord)):
    case ((int)(JIT_OP_unord)):
      if (cmd_arg_num != 4)
        scheme_signal_error(errorstr_wrong_args_num, operator, 4, pc);
      /* process `t' argument */
      type1 = (mzjit_get_type(SCHEME_CAR(pc)));
      pc = SCHEME_CDR(pc);
      /* process `r' argument */
      reg1 = mzjit_get_register(SCHEME_CAR(pc),(type1>=JIT_TYPE_F));
      pc = SCHEME_CDR(pc);
      /* process `r' argument */
      reg2 = mzjit_get_register(SCHEME_CAR(pc),(type1>=JIT_TYPE_F));
      pc = SCHEME_CDR(pc);
      /* process `r/i' argument */
      if (SCHEME_REGP(SCHEME_CAR(pc))) {
        reg3 = mzjit_get_register(SCHEME_CAR(pc),(type1>=JIT_TYPE_F));
        kind = JIT_KIND_R;
      } else {
        imm = mzjit_get_imm(SCHEME_CAR(pc));
        kind = JIT_KIND_I;
      }
      pc = SCHEME_CDR(pc);
      switch (operator_id) {
      case ((int)(JIT_OP_lt)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_I): jit_ltr_i(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UI): jit_ltr_ui(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_L): jit_ltr_l(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UL): jit_ltr_ul(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_P): jit_ltr_p(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_F): jit_ltr_f(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_D): jit_ltr_d(reg1,reg2,reg3); break;
        case (JIT_KIND_I | JIT_TYPE_I): jit_lti_i(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UI): jit_lti_ui(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_L): jit_lti_l(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UL): jit_lti_ul(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_P): jit_lti_p(reg1,reg2,imm); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_le)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_I): jit_ler_i(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UI): jit_ler_ui(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_L): jit_ler_l(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UL): jit_ler_ul(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_P): jit_ler_p(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_F): jit_ler_f(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_D): jit_ler_d(reg1,reg2,reg3); break;
        case (JIT_KIND_I | JIT_TYPE_I): jit_lei_i(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UI): jit_lei_ui(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_L): jit_lei_l(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UL): jit_lei_ul(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_P): jit_lei_p(reg1,reg2,imm); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_gt)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_I): jit_gtr_i(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UI): jit_gtr_ui(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_L): jit_gtr_l(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UL): jit_gtr_ul(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_P): jit_gtr_p(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_F): jit_gtr_f(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_D): jit_gtr_d(reg1,reg2,reg3); break;
        case (JIT_KIND_I | JIT_TYPE_I): jit_gti_i(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UI): jit_gti_ui(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_L): jit_gti_l(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UL): jit_gti_ul(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_P): jit_gti_p(reg1,reg2,imm); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_ge)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_I): jit_ger_i(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UI): jit_ger_ui(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_L): jit_ger_l(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UL): jit_ger_ul(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_P): jit_ger_p(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_F): jit_ger_f(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_D): jit_ger_d(reg1,reg2,reg3); break;
        case (JIT_KIND_I | JIT_TYPE_I): jit_gei_i(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UI): jit_gei_ui(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_L): jit_gei_l(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UL): jit_gei_ul(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_P): jit_gei_p(reg1,reg2,imm); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_eq)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_I): jit_eqr_i(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UI): jit_eqr_ui(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_L): jit_eqr_l(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UL): jit_eqr_ul(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_P): jit_eqr_p(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_F): jit_eqr_f(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_D): jit_eqr_d(reg1,reg2,reg3); break;
        case (JIT_KIND_I | JIT_TYPE_I): jit_eqi_i(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UI): jit_eqi_ui(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_L): jit_eqi_l(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UL): jit_eqi_ul(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_P): jit_eqi_p(reg1,reg2,imm); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_ne)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_I): jit_ner_i(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UI): jit_ner_ui(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_L): jit_ner_l(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UL): jit_ner_ul(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_P): jit_ner_p(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_F): jit_ner_f(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_D): jit_ner_d(reg1,reg2,reg3); break;
        case (JIT_KIND_I | JIT_TYPE_I): jit_nei_i(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UI): jit_nei_ui(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_L): jit_nei_l(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UL): jit_nei_ul(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_P): jit_nei_p(reg1,reg2,imm); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_unlt)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_F): jit_unltr_f(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_D): jit_unltr_d(reg1,reg2,reg3); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_unle)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_F): jit_unler_f(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_D): jit_unler_d(reg1,reg2,reg3); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_ungt)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_F): jit_ungtr_f(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_D): jit_ungtr_d(reg1,reg2,reg3); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_unge)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_F): jit_unger_f(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_D): jit_unger_d(reg1,reg2,reg3); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_uneq)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_F): jit_uneqr_f(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_D): jit_uneqr_d(reg1,reg2,reg3); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_ltgt)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_F): jit_ltgtr_f(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_D): jit_ltgtr_d(reg1,reg2,reg3); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_ord)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_F): jit_ordr_f(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_D): jit_ordr_d(reg1,reg2,reg3); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_unord)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_F): jit_unordr_f(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_D): jit_unordr_d(reg1,reg2,reg3); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      }
      break;
    /* ========== Transfer operations 1 ========== */
    case ((int)(JIT_OP_mov)):
      if (cmd_arg_num != 3)
        scheme_signal_error(errorstr_wrong_args_num, operator, 3, pc);
      /* process `t' argument */
      type1 = (mzjit_get_type(SCHEME_CAR(pc)));
      pc = SCHEME_CDR(pc);
      /* process `r' argument */
      reg1 = mzjit_get_register(SCHEME_CAR(pc),(type1>=JIT_TYPE_F));
      pc = SCHEME_CDR(pc);
      /* process `r/i' argument */
      if (SCHEME_REGP(SCHEME_CAR(pc))) {
        reg2 = mzjit_get_register(SCHEME_CAR(pc),(type1>=JIT_TYPE_F));
        kind = JIT_KIND_R;
      } else {
        imm = mzjit_get_imm(SCHEME_CAR(pc));
        kind = JIT_KIND_I;
      }
      pc = SCHEME_CDR(pc);
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_I): jit_movr_i(reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_UI): jit_movr_ui(reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_L): jit_movr_l(reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_UL): jit_movr_ul(reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_P): jit_movr_p(reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_F): jit_movr_f(reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_D): jit_movr_d(reg1,reg2); break;
        case (JIT_KIND_I | JIT_TYPE_I): jit_movi_i(reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UI): jit_movi_ui(reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_L): jit_movi_l(reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UL): jit_movi_ul(reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_P): jit_movi_p(reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_F): jit_movi_f(reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_D): jit_movi_d(reg1,imm); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
      break;
    /* ========== Transfer operations 2 ========== */
    case ((int)(JIT_OP_ext)):
    case ((int)(JIT_OP_round)):
    case ((int)(JIT_OP_trunc)):
    case ((int)(JIT_OP_floor)):
    case ((int)(JIT_OP_ceil)):
      if (cmd_arg_num != 4)
        scheme_signal_error(errorstr_wrong_args_num, operator, 4, pc);
      /* process `t' argument */
      type1 = (mzjit_get_type(SCHEME_CAR(pc)));
      pc = SCHEME_CDR(pc);
      /* process `t' argument */
      type2 = (mzjit_get_type(SCHEME_CAR(pc)))<<8;
      pc = SCHEME_CDR(pc);
      /* process `r' argument */
      reg1 = mzjit_get_register(SCHEME_CAR(pc),(type2>=(JIT_TYPE_F<<8)));
      pc = SCHEME_CDR(pc);
      /* process `r' argument */
      reg2 = mzjit_get_register(SCHEME_CAR(pc),(type1>=JIT_TYPE_F));
      pc = SCHEME_CDR(pc);
      switch (operator_id) {
      case ((int)(JIT_OP_ext)):
        switch (type1 | type2) {
        case (JIT_TYPE_C | (JIT_TYPE_S<<8)): jit_extr_c_s(reg1,reg2); break;
        case (JIT_TYPE_C | (JIT_TYPE_US<<8)): jit_extr_c_us(reg1,reg2); break;
        case (JIT_TYPE_C | (JIT_TYPE_I<<8)): jit_extr_c_i(reg1,reg2); break;
        case (JIT_TYPE_C | (JIT_TYPE_UI<<8)): jit_extr_c_ui(reg1,reg2); break;
        case (JIT_TYPE_C | (JIT_TYPE_L<<8)): jit_extr_c_l(reg1,reg2); break;
        case (JIT_TYPE_C | (JIT_TYPE_UL<<8)): jit_extr_c_ul(reg1,reg2); break;
        case (JIT_TYPE_UC | (JIT_TYPE_S<<8)): jit_extr_uc_s(reg1,reg2); break;
        case (JIT_TYPE_UC | (JIT_TYPE_US<<8)): jit_extr_uc_us(reg1,reg2); break;
        case (JIT_TYPE_UC | (JIT_TYPE_I<<8)): jit_extr_uc_i(reg1,reg2); break;
        case (JIT_TYPE_UC | (JIT_TYPE_UI<<8)): jit_extr_uc_ui(reg1,reg2); break;
        case (JIT_TYPE_UC | (JIT_TYPE_L<<8)): jit_extr_uc_l(reg1,reg2); break;
        case (JIT_TYPE_UC | (JIT_TYPE_UL<<8)): jit_extr_uc_ul(reg1,reg2); break;
        case (JIT_TYPE_S | (JIT_TYPE_I<<8)): jit_extr_s_i(reg1,reg2); break;
        case (JIT_TYPE_S | (JIT_TYPE_UI<<8)): jit_extr_s_ui(reg1,reg2); break;
        case (JIT_TYPE_S | (JIT_TYPE_L<<8)): jit_extr_s_l(reg1,reg2); break;
        case (JIT_TYPE_S | (JIT_TYPE_UL<<8)): jit_extr_s_ul(reg1,reg2); break;
        case (JIT_TYPE_US | (JIT_TYPE_I<<8)): jit_extr_us_i(reg1,reg2); break;
        case (JIT_TYPE_US | (JIT_TYPE_UI<<8)): jit_extr_us_ui(reg1,reg2); break;
        case (JIT_TYPE_US | (JIT_TYPE_L<<8)): jit_extr_us_l(reg1,reg2); break;
        case (JIT_TYPE_US | (JIT_TYPE_UL<<8)): jit_extr_us_ul(reg1,reg2); break;
        case (JIT_TYPE_I | (JIT_TYPE_L<<8)): jit_extr_i_l(reg1,reg2); break;
        case (JIT_TYPE_I | (JIT_TYPE_UL<<8)): jit_extr_i_ul(reg1,reg2); break;
        case (JIT_TYPE_UI | (JIT_TYPE_L<<8)): jit_extr_ui_l(reg1,reg2); break;
        case (JIT_TYPE_UI | (JIT_TYPE_UL<<8)): jit_extr_ui_ul(reg1,reg2); break;
        case (JIT_TYPE_I | (JIT_TYPE_F<<8)): jit_extr_i_f(reg1,reg2); break;
        case (JIT_TYPE_I | (JIT_TYPE_D<<8)): jit_extr_i_d(reg1,reg2); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_round)):
        switch (type1 | type2) {
        case (JIT_TYPE_F | (JIT_TYPE_I<<8)): jit_roundr_f_i(reg1,reg2); break;
        case (JIT_TYPE_D | (JIT_TYPE_I<<8)): jit_roundr_d_i(reg1,reg2); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_trunc)):
        switch (type1 | type2) {
        case (JIT_TYPE_F | (JIT_TYPE_I<<8)): jit_truncr_f_i(reg1,reg2); break;
        case (JIT_TYPE_D | (JIT_TYPE_I<<8)): jit_truncr_d_i(reg1,reg2); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_floor)):
        switch (type1 | type2) {
        case (JIT_TYPE_F | (JIT_TYPE_I<<8)): jit_floorr_f_i(reg1,reg2); break;
        case (JIT_TYPE_D | (JIT_TYPE_I<<8)): jit_floorr_d_i(reg1,reg2); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_ceil)):
        switch (type1 | type2) {
        case (JIT_TYPE_F | (JIT_TYPE_I<<8)): jit_ceilr_f_i(reg1,reg2); break;
        case (JIT_TYPE_D | (JIT_TYPE_I<<8)): jit_ceilr_d_i(reg1,reg2); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      }
      break;
    /* ========== Network extensions ========== */
    case ((int)(JIT_OP_hton)):
    case ((int)(JIT_OP_ntoh)):
      if (cmd_arg_num != 3)
        scheme_signal_error(errorstr_wrong_args_num, operator, 3, pc);
      /* process `t' argument */
      type1 = (mzjit_get_type(SCHEME_CAR(pc)));
      pc = SCHEME_CDR(pc);
      /* process `r' argument */
      reg1 = mzjit_get_register(SCHEME_CAR(pc),(type1>=JIT_TYPE_F));
      pc = SCHEME_CDR(pc);
      /* process `r' argument */
      reg2 = mzjit_get_register(SCHEME_CAR(pc),(type1>=JIT_TYPE_F));
      pc = SCHEME_CDR(pc);
      switch (operator_id) {
      case ((int)(JIT_OP_hton)):
        switch (type1) {
        case (JIT_TYPE_US): jit_hton_us(reg1,reg2); break;
        case (JIT_TYPE_UI): jit_hton_ui(reg1,reg2); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_ntoh)):
        switch (type1) {
        case (JIT_TYPE_US): jit_ntoh_us(reg1,reg2); break;
        case (JIT_TYPE_UI): jit_ntoh_ui(reg1,reg2); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      }
      break;
    /* ========== Load operations 1 ========== */
    case ((int)(JIT_OP_ld)):
      if (cmd_arg_num != 3)
        scheme_signal_error(errorstr_wrong_args_num, operator, 3, pc);
      /* process `t' argument */
      type1 = (mzjit_get_type(SCHEME_CAR(pc)));
      pc = SCHEME_CDR(pc);
      /* process `r' argument */
      reg1 = mzjit_get_register(SCHEME_CAR(pc),(type1>=JIT_TYPE_F));
      pc = SCHEME_CDR(pc);
      /* process `r/i' argument */
      if (SCHEME_REGP(SCHEME_CAR(pc))) {
        reg2 = mzjit_get_register(SCHEME_CAR(pc),(type1>=JIT_TYPE_F));
        kind = JIT_KIND_R;
      } else {
        imm = mzjit_get_imm(SCHEME_CAR(pc));
        kind = JIT_KIND_I;
      }
      pc = SCHEME_CDR(pc);
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_C): jit_ldr_c(reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_UC): jit_ldr_uc(reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_S): jit_ldr_s(reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_US): jit_ldr_us(reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_I): jit_ldr_i(reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_UI): jit_ldr_ui(reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_L): jit_ldr_l(reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_UL): jit_ldr_ul(reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_P): jit_ldr_p(reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_F): jit_ldr_f(reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_D): jit_ldr_d(reg1,reg2); break;
        case (JIT_KIND_I | JIT_TYPE_C): jit_ldi_c(reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UC): jit_ldi_uc(reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_S): jit_ldi_s(reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_US): jit_ldi_us(reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_I): jit_ldi_i(reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UI): jit_ldi_ui(reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_L): jit_ldi_l(reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UL): jit_ldi_ul(reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_P): jit_ldi_p(reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_F): jit_ldi_f(reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_D): jit_ldi_d(reg1,imm); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
      break;
    /* ========== Load operations 2 ========== */
    case ((int)(JIT_OP_ldx)):
      if (cmd_arg_num != 4)
        scheme_signal_error(errorstr_wrong_args_num, operator, 4, pc);
      /* process `t' argument */
      type1 = (mzjit_get_type(SCHEME_CAR(pc)));
      pc = SCHEME_CDR(pc);
      /* process `r' argument */
      reg1 = mzjit_get_register(SCHEME_CAR(pc),(type1>=JIT_TYPE_F));
      pc = SCHEME_CDR(pc);
      /* process `r' argument */
      reg2 = mzjit_get_register(SCHEME_CAR(pc),(type1>=JIT_TYPE_F));
      pc = SCHEME_CDR(pc);
      /* process `r/i' argument */
      if (SCHEME_REGP(SCHEME_CAR(pc))) {
        reg3 = mzjit_get_register(SCHEME_CAR(pc),(type1>=JIT_TYPE_F));
        kind = JIT_KIND_R;
      } else {
        imm = mzjit_get_imm(SCHEME_CAR(pc));
        kind = JIT_KIND_I;
      }
      pc = SCHEME_CDR(pc);
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_C): jit_ldxr_c(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UC): jit_ldxr_uc(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_S): jit_ldxr_s(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_US): jit_ldxr_us(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_I): jit_ldxr_i(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UI): jit_ldxr_ui(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_L): jit_ldxr_l(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UL): jit_ldxr_ul(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_P): jit_ldxr_p(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_F): jit_ldxr_f(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_D): jit_ldxr_d(reg1,reg2,reg3); break;
        case (JIT_KIND_I | JIT_TYPE_C): jit_ldxi_c(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UC): jit_ldxi_uc(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_S): jit_ldxi_s(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_US): jit_ldxi_us(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_I): jit_ldxi_i(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UI): jit_ldxi_ui(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_L): jit_ldxi_l(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UL): jit_ldxi_ul(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_P): jit_ldxi_p(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_F): jit_ldxi_f(reg1,reg2,imm); break;
        case (JIT_KIND_I | JIT_TYPE_D): jit_ldxi_d(reg1,reg2,imm); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
      break;
    /* ========== Store operations 1 ========== */
    case ((int)(JIT_OP_st)):
      if (cmd_arg_num != 3)
        scheme_signal_error(errorstr_wrong_args_num, operator, 3, pc);
      /* process `t' argument */
      type1 = (mzjit_get_type(SCHEME_CAR(pc)));
      pc = SCHEME_CDR(pc);
      /* process `r/i' argument */
      if (SCHEME_REGP(SCHEME_CAR(pc))) {
        reg1 = mzjit_get_register(SCHEME_CAR(pc),(type1>=JIT_TYPE_F));
        kind = JIT_KIND_R;
      } else {
        imm = mzjit_get_imm(SCHEME_CAR(pc));
        kind = JIT_KIND_I;
      }
      pc = SCHEME_CDR(pc);
      /* process `r' argument */
      reg2 = mzjit_get_register(SCHEME_CAR(pc),(type1>=JIT_TYPE_F));
      pc = SCHEME_CDR(pc);
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_C): jit_str_c(reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_UC): jit_str_uc(reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_S): jit_str_s(reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_US): jit_str_us(reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_I): jit_str_i(reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_UI): jit_str_ui(reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_L): jit_str_l(reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_UL): jit_str_ul(reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_P): jit_str_p(reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_F): jit_str_f(reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_D): jit_str_d(reg1,reg2); break;
        case (JIT_KIND_I | JIT_TYPE_C): jit_sti_c(imm,reg2); break;
        case (JIT_KIND_I | JIT_TYPE_UC): jit_sti_uc(imm,reg2); break;
        case (JIT_KIND_I | JIT_TYPE_S): jit_sti_s(imm,reg2); break;
        case (JIT_KIND_I | JIT_TYPE_US): jit_sti_us(imm,reg2); break;
        case (JIT_KIND_I | JIT_TYPE_I): jit_sti_i(imm,reg2); break;
        case (JIT_KIND_I | JIT_TYPE_UI): jit_sti_ui(imm,reg2); break;
        case (JIT_KIND_I | JIT_TYPE_L): jit_sti_l(imm,reg2); break;
        case (JIT_KIND_I | JIT_TYPE_UL): jit_sti_ul(imm,reg2); break;
        case (JIT_KIND_I | JIT_TYPE_P): jit_sti_p(imm,reg2); break;
        case (JIT_KIND_I | JIT_TYPE_F): jit_sti_f(imm,reg2); break;
        case (JIT_KIND_I | JIT_TYPE_D): jit_sti_d(imm,reg2); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
      break;
    /* ========== Store operations 2 ========== */
    case ((int)(JIT_OP_stx)):
      if (cmd_arg_num != 4)
        scheme_signal_error(errorstr_wrong_args_num, operator, 4, pc);
      /* process `t' argument */
      type1 = (mzjit_get_type(SCHEME_CAR(pc)));
      pc = SCHEME_CDR(pc);
      /* process `r/i' argument */
      if (SCHEME_REGP(SCHEME_CAR(pc))) {
        reg1 = mzjit_get_register(SCHEME_CAR(pc),(type1>=JIT_TYPE_F));
        kind = JIT_KIND_R;
      } else {
        imm = mzjit_get_imm(SCHEME_CAR(pc));
        kind = JIT_KIND_I;
      }
      pc = SCHEME_CDR(pc);
      /* process `r' argument */
      reg2 = mzjit_get_register(SCHEME_CAR(pc),(type1>=JIT_TYPE_F));
      pc = SCHEME_CDR(pc);
      /* process `r' argument */
      reg3 = mzjit_get_register(SCHEME_CAR(pc),(type1>=JIT_TYPE_F));
      pc = SCHEME_CDR(pc);
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_C): jit_stxr_c(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UC): jit_stxr_uc(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_S): jit_stxr_s(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_US): jit_stxr_us(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_I): jit_stxr_i(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UI): jit_stxr_ui(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_L): jit_stxr_l(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_UL): jit_stxr_ul(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_P): jit_stxr_p(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_F): jit_stxr_f(reg1,reg2,reg3); break;
        case (JIT_KIND_R | JIT_TYPE_D): jit_stxr_d(reg1,reg2,reg3); break;
        case (JIT_KIND_I | JIT_TYPE_C): jit_stxi_c(imm,reg2,reg3); break;
        case (JIT_KIND_I | JIT_TYPE_UC): jit_stxi_uc(imm,reg2,reg3); break;
        case (JIT_KIND_I | JIT_TYPE_S): jit_stxi_s(imm,reg2,reg3); break;
        case (JIT_KIND_I | JIT_TYPE_US): jit_stxi_us(imm,reg2,reg3); break;
        case (JIT_KIND_I | JIT_TYPE_I): jit_stxi_i(imm,reg2,reg3); break;
        case (JIT_KIND_I | JIT_TYPE_UI): jit_stxi_ui(imm,reg2,reg3); break;
        case (JIT_KIND_I | JIT_TYPE_L): jit_stxi_l(imm,reg2,reg3); break;
        case (JIT_KIND_I | JIT_TYPE_UL): jit_stxi_ul(imm,reg2,reg3); break;
        case (JIT_KIND_I | JIT_TYPE_P): jit_stxi_p(imm,reg2,reg3); break;
        case (JIT_KIND_I | JIT_TYPE_F): jit_stxi_f(imm,reg2,reg3); break;
        case (JIT_KIND_I | JIT_TYPE_D): jit_stxi_d(imm,reg2,reg3); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
      break;
    /* ========== Stack management ========== */
    case ((int)(JIT_OP_push)):
    case ((int)(JIT_OP_pop)):
      if (cmd_arg_num != 2)
        scheme_signal_error(errorstr_wrong_args_num, operator, 2, pc);
      /* process `t' argument */
      type1 = (mzjit_get_type(SCHEME_CAR(pc)));
      pc = SCHEME_CDR(pc);
      /* process `r' argument */
      reg1 = mzjit_get_register(SCHEME_CAR(pc),(type1>=JIT_TYPE_F));
      pc = SCHEME_CDR(pc);
      switch (operator_id) {
      case ((int)(JIT_OP_push)):
        switch (type1) {
        case (JIT_TYPE_I): jit_pushr_i(reg1); break;
        case (JIT_TYPE_UI): jit_pushr_ui(reg1); break;
        case (JIT_TYPE_L): jit_pushr_l(reg1); break;
        case (JIT_TYPE_UL): jit_pushr_ul(reg1); break;
        case (JIT_TYPE_P): jit_pushr_p(reg1); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_pop)):
        switch (type1) {
        case (JIT_TYPE_I): jit_popr_i(reg1); break;
        case (JIT_TYPE_UI): jit_popr_ui(reg1); break;
        case (JIT_TYPE_L): jit_popr_l(reg1); break;
        case (JIT_TYPE_UL): jit_popr_ul(reg1); break;
        case (JIT_TYPE_P): jit_popr_p(reg1); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      }
      break;
    /* ========== Argument management ========== */
    case ((int)(JIT_OP_prepare)):
      if (cmd_arg_num != 2)
        scheme_signal_error(errorstr_wrong_args_num, operator, 2, pc);
      /* process `t' argument */
      type1 = (mzjit_get_type(SCHEME_CAR(pc)));
      pc = SCHEME_CDR(pc);
      /* process `i' argument */
      imm = mzjit_get_imm(SCHEME_CAR(pc));
      pc = SCHEME_CDR(pc);
        switch (type1) {
        case (JIT_TYPE_I): jit_prepare_i(imm); break;
        case (JIT_TYPE_F): jit_prepare_f(imm); break;
        case (JIT_TYPE_D): jit_prepare_d(imm); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
      break;
    /* ========== Argument management 2 ========== */
    case ((int)(JIT_OP_pusharg)):
    case ((int)(JIT_OP_getarg)):
      if (cmd_arg_num != 2)
        scheme_signal_error(errorstr_wrong_args_num, operator, 2, pc);
      /* process `t' argument */
      type1 = (mzjit_get_type(SCHEME_CAR(pc)));
      pc = SCHEME_CDR(pc);
      /* process `r' argument */
      reg1 = mzjit_get_register(SCHEME_CAR(pc),(type1>=JIT_TYPE_F));
      pc = SCHEME_CDR(pc);
      switch (operator_id) {
      case ((int)(JIT_OP_pusharg)):
        switch (type1) {
        case (JIT_TYPE_C): jit_pusharg_c(reg1); break;
        case (JIT_TYPE_UC): jit_pusharg_uc(reg1); break;
        case (JIT_TYPE_S): jit_pusharg_s(reg1); break;
        case (JIT_TYPE_US): jit_pusharg_us(reg1); break;
        case (JIT_TYPE_I): jit_pusharg_i(reg1); break;
        case (JIT_TYPE_UI): jit_pusharg_ui(reg1); break;
        case (JIT_TYPE_L): jit_pusharg_l(reg1); break;
        case (JIT_TYPE_UL): jit_pusharg_ul(reg1); break;
        case (JIT_TYPE_P): jit_pusharg_p(reg1); break;
        case (JIT_TYPE_F): jit_pusharg_f(reg1); break;
        case (JIT_TYPE_D): jit_pusharg_d(reg1); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_getarg)):
        switch (type1) {
        case (JIT_TYPE_C): in = jit_arg_c(); jit_getarg_c(reg1,in); break;
        case (JIT_TYPE_UC): in = jit_arg_uc(); jit_getarg_uc(reg1,in); break;
        case (JIT_TYPE_S): in = jit_arg_s(); jit_getarg_s(reg1,in); break;
        case (JIT_TYPE_US): in = jit_arg_us(); jit_getarg_us(reg1,in); break;
        case (JIT_TYPE_I): in = jit_arg_i(); jit_getarg_i(reg1,in); break;
        case (JIT_TYPE_UI): in = jit_arg_ui(); jit_getarg_ui(reg1,in); break;
        case (JIT_TYPE_L): in = jit_arg_l(); jit_getarg_l(reg1,in); break;
        case (JIT_TYPE_UL): in = jit_arg_ul(); jit_getarg_ul(reg1,in); break;
        case (JIT_TYPE_P): in = jit_arg_p(); jit_getarg_p(reg1,in); break;
        case (JIT_TYPE_F): in = jit_arg_f(); jit_getarg_f(reg1,in); break;
        case (JIT_TYPE_D): in = jit_arg_d(); jit_getarg_d(reg1,in); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      }
      break;
    /* ========== Branch instructions ========== */
    case ((int)(JIT_OP_blt)):
    case ((int)(JIT_OP_ble)):
    case ((int)(JIT_OP_bgt)):
    case ((int)(JIT_OP_bge)):
    case ((int)(JIT_OP_beq)):
    case ((int)(JIT_OP_bne)):
    case ((int)(JIT_OP_bms)):
    case ((int)(JIT_OP_bmc)):
    case ((int)(JIT_OP_boadd)):
    case ((int)(JIT_OP_bosub)):
      if (cmd_arg_num != 4)
        scheme_signal_error(errorstr_wrong_args_num, operator, 4, pc);
      /* process `t' argument */
      type1 = (mzjit_get_type(SCHEME_CAR(pc)));
      pc = SCHEME_CDR(pc);
      /* process `l' argument */
      labelsym  = SCHEME_CAR(pc);
      labeladdr = mzjit_get_label(labelsym,bwd_labels);
      if (labeladdr != NULL) labelsym = NULL; else labeladdr = jit_forward();
      pc = SCHEME_CDR(pc);
      /* process `r' argument */
      reg1 = mzjit_get_register(SCHEME_CAR(pc),(type1>=JIT_TYPE_F));
      pc = SCHEME_CDR(pc);
      /* process `r/i' argument */
      if (SCHEME_REGP(SCHEME_CAR(pc))) {
        reg2 = mzjit_get_register(SCHEME_CAR(pc),(type1>=JIT_TYPE_F));
        kind = JIT_KIND_R;
      } else {
        imm = mzjit_get_imm(SCHEME_CAR(pc));
        kind = JIT_KIND_I;
      }
      pc = SCHEME_CDR(pc);
      switch (operator_id) {
      case ((int)(JIT_OP_blt)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_I): patch = jit_bltr_i(labeladdr,reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_UI): patch = jit_bltr_ui(labeladdr,reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_L): patch = jit_bltr_l(labeladdr,reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_UL): patch = jit_bltr_ul(labeladdr,reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_P): patch = jit_bltr_p(labeladdr,reg1,reg2); break;
        case (JIT_KIND_I | JIT_TYPE_I): patch = jit_blti_i(labeladdr,reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UI): patch = jit_blti_ui(labeladdr,reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_L): patch = jit_blti_l(labeladdr,reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UL): patch = jit_blti_ul(labeladdr,reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_P): patch = jit_blti_p(labeladdr,reg1,imm); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_ble)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_I): patch = jit_bler_i(labeladdr,reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_UI): patch = jit_bler_ui(labeladdr,reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_L): patch = jit_bler_l(labeladdr,reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_UL): patch = jit_bler_ul(labeladdr,reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_P): patch = jit_bler_p(labeladdr,reg1,reg2); break;
        case (JIT_KIND_I | JIT_TYPE_I): patch = jit_blei_i(labeladdr,reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UI): patch = jit_blei_ui(labeladdr,reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_L): patch = jit_blei_l(labeladdr,reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UL): patch = jit_blei_ul(labeladdr,reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_P): patch = jit_blei_p(labeladdr,reg1,imm); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_bgt)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_I): patch = jit_bgtr_i(labeladdr,reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_UI): patch = jit_bgtr_ui(labeladdr,reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_L): patch = jit_bgtr_l(labeladdr,reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_UL): patch = jit_bgtr_ul(labeladdr,reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_P): patch = jit_bgtr_p(labeladdr,reg1,reg2); break;
        case (JIT_KIND_I | JIT_TYPE_I): patch = jit_bgti_i(labeladdr,reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UI): patch = jit_bgti_ui(labeladdr,reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_L): patch = jit_bgti_l(labeladdr,reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UL): patch = jit_bgti_ul(labeladdr,reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_P): patch = jit_bgti_p(labeladdr,reg1,imm); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_bge)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_I): patch = jit_bger_i(labeladdr,reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_UI): patch = jit_bger_ui(labeladdr,reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_L): patch = jit_bger_l(labeladdr,reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_UL): patch = jit_bger_ul(labeladdr,reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_P): patch = jit_bger_p(labeladdr,reg1,reg2); break;
        case (JIT_KIND_I | JIT_TYPE_I): patch = jit_bgei_i(labeladdr,reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UI): patch = jit_bgei_ui(labeladdr,reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_L): patch = jit_bgei_l(labeladdr,reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UL): patch = jit_bgei_ul(labeladdr,reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_P): patch = jit_bgei_p(labeladdr,reg1,imm); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_beq)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_I): patch = jit_beqr_i(labeladdr,reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_UI): patch = jit_beqr_ui(labeladdr,reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_L): patch = jit_beqr_l(labeladdr,reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_UL): patch = jit_beqr_ul(labeladdr,reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_P): patch = jit_beqr_p(labeladdr,reg1,reg2); break;
        case (JIT_KIND_I | JIT_TYPE_I): patch = jit_beqi_i(labeladdr,reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UI): patch = jit_beqi_ui(labeladdr,reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_L): patch = jit_beqi_l(labeladdr,reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UL): patch = jit_beqi_ul(labeladdr,reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_P): patch = jit_beqi_p(labeladdr,reg1,imm); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_bne)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_I): patch = jit_bner_i(labeladdr,reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_UI): patch = jit_bner_ui(labeladdr,reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_L): patch = jit_bner_l(labeladdr,reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_UL): patch = jit_bner_ul(labeladdr,reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_P): patch = jit_bner_p(labeladdr,reg1,reg2); break;
        case (JIT_KIND_I | JIT_TYPE_I): patch = jit_bnei_i(labeladdr,reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UI): patch = jit_bnei_ui(labeladdr,reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_L): patch = jit_bnei_l(labeladdr,reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UL): patch = jit_bnei_ul(labeladdr,reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_P): patch = jit_bnei_p(labeladdr,reg1,imm); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_bms)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_I): patch = jit_bmsr_i(labeladdr,reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_UI): patch = jit_bmsr_ui(labeladdr,reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_L): patch = jit_bmsr_l(labeladdr,reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_UL): patch = jit_bmsr_ul(labeladdr,reg1,reg2); break;
        case (JIT_KIND_I | JIT_TYPE_I): patch = jit_bmsi_i(labeladdr,reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UI): patch = jit_bmsi_ui(labeladdr,reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_L): patch = jit_bmsi_l(labeladdr,reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UL): patch = jit_bmsi_ul(labeladdr,reg1,imm); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_bmc)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_I): patch = jit_bmcr_i(labeladdr,reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_UI): patch = jit_bmcr_ui(labeladdr,reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_L): patch = jit_bmcr_l(labeladdr,reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_UL): patch = jit_bmcr_ul(labeladdr,reg1,reg2); break;
        case (JIT_KIND_I | JIT_TYPE_I): patch = jit_bmci_i(labeladdr,reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UI): patch = jit_bmci_ui(labeladdr,reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_L): patch = jit_bmci_l(labeladdr,reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_UL): patch = jit_bmci_ul(labeladdr,reg1,imm); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_boadd)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_I): patch = jit_boaddr_i(labeladdr,reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_L): patch = jit_boaddr_l(labeladdr,reg1,reg2); break;
        case (JIT_KIND_I | JIT_TYPE_I): patch = jit_boaddi_i(labeladdr,reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_L): patch = jit_boaddi_l(labeladdr,reg1,imm); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      case ((int)(JIT_OP_bosub)):
        switch (kind | type1) {
        case (JIT_KIND_R | JIT_TYPE_I): patch = jit_bosubr_i(labeladdr,reg1,reg2); break;
        case (JIT_KIND_R | JIT_TYPE_L): patch = jit_bosubr_l(labeladdr,reg1,reg2); break;
        case (JIT_KIND_I | JIT_TYPE_I): patch = jit_bosubi_i(labeladdr,reg1,imm); break;
        case (JIT_KIND_I | JIT_TYPE_L): patch = jit_bosubi_l(labeladdr,reg1,imm); break;
        default: scheme_signal_error(errorstr_bad_command_format,operator,command);
        }
        break;
      }
      break;
    /* ========== Jump and return operations 1 ========== */
    case ((int)(JIT_OP_jmp)):
      /* patch = jit_finishi(imm); */
      patch = (_jit.x.pc = jit_calli((imm)), ADDLir(4 * _jitl.argssize, JIT_SP), _jitl.argssize = 0, _jit.x.pc);
      break;
    }
    if (labelsym != NULL) mzjit_set_fwd_label(labelsym, &fwd_labels, patch);
  }
  while (!SCHEME_NULLP(fwd_labels)) {
    if ( !SCHEME_FALSEP(SCHEME_CAAR(fwd_labels)) )
      scheme_signal_error("jit-proc: reference to undefined label `%V'",
                          SCHEME_CAAR(fwd_labels));
    fwd_labels = SCHEME_CDR(fwd_labels);
  }
  current_location = jit_get_ip().ptr;
  jit_flush_code(code, current_location);
  return current_location - code;
}

void free_jit_code(void *ignored, void *code)
{
  free(code);
}

static char   *mzjit_code_buffer = NULL;
static size_t  mzjit_code_len = 0;

#undef MYNAME
#define MYNAME "jit-proc"
static Scheme_Object *lightning_jit_proc(int argc, Scheme_Object *argv[])
{
  char *code;
  Scheme_Object *r;
  size_t size = -1;
  if ( scheme_proper_list_length(argv[0]) <= 0 )
    scheme_wrong_type("jit-proc", "list", 0, argc, argv);
  /* generate into code */
  while (1) {
    size = mzjit_make(argv[0], mzjit_code_buffer, mzjit_code_len);
    if (size != -1) break;
    mzjit_code_len *= 2;
    mzjit_code_buffer = realloc(mzjit_code_buffer, mzjit_code_len);
  }
  code = malloc(size);
  /* generate into a fresh block */
  if ( mzjit_make(argv[0], code, size + MAX_INSTR_SIZE) == -1 )
    scheme_signal_error("mzjit_make failed on second pass");
  /* disassemble(stderr, code, ((char*)code)+size); */
  r = scheme_make_cptr(code, NULL);
  scheme_register_finalizer(r, free_jit_code, code, NULL, NULL);
  return r;
}

/*****************************************************************************/
/* Testing */

typedef int (*pifv)(void);
typedef int (*pifi)(int);
typedef int (*pifii)(int,int);

#undef MYNAME
#define MYNAME "pifv"
static Scheme_Object *lightning_pifv(int argc, Scheme_Object *argv[])
{
  pifv func;
  if (!SCHEME_CPTRP(argv[0]))
    scheme_wrong_type(MYNAME, "pointer", 0, argc, argv);
  func = (pifv)(SCHEME_CPTR_VAL(argv[0]));
  return scheme_make_integer_value(func());
}

#undef MYNAME
#define MYNAME "pifi"
static Scheme_Object *lightning_pifi(int argc, Scheme_Object *argv[])
{
  pifi func;
  if (!SCHEME_CPTRP(argv[0]))
    scheme_wrong_type(MYNAME, "pointer", 0, argc, argv);
  if (!SCHEME_INTP(argv[1]))
    scheme_wrong_type(MYNAME, "integer", 1, argc, argv);
  func = (pifi)(SCHEME_CPTR_VAL(argv[0]));
  return scheme_make_integer_value(func(SCHEME_INT_VAL(argv[1])));
}

#undef MYNAME
#define MYNAME "pifii"
static Scheme_Object *lightning_pifii(int argc, Scheme_Object *argv[])
{
  pifii func;
  if (!SCHEME_CPTRP(argv[0]))
    scheme_wrong_type(MYNAME, "pointer", 0, argc, argv);
  if (!SCHEME_INTP(argv[1]))
    scheme_wrong_type(MYNAME, "integer", 1, argc, argv);
  if (!SCHEME_INTP(argv[2]))
    scheme_wrong_type(MYNAME, "integer", 2, argc, argv);
  func = (pifii)(SCHEME_CPTR_VAL(argv[0]));
  return scheme_make_integer_value(func(SCHEME_INT_VAL(argv[1]),
                                        SCHEME_INT_VAL(argv[2])));
}

/*****************************************************************************/
/* Initialization */

/* Remove this when in MzScheme */
#define MZ_REGISTER_STATIC(x) scheme_register_static((void*)&x,sizeof(x))

Scheme_Object *scheme_reload(Scheme_Env *env)
{
  Scheme_Env *menv;
  menv = scheme_primitive_module(scheme_intern_symbol("#%lightning"), env);
  op_alist = scheme_null;
  MZ_REGISTER_STATIC(op_alist);
  mzjit_code_len = 1024;
  mzjit_code_buffer = malloc(mzjit_code_len);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("add"),
                 JIT_OP_add),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("addx"),
                 JIT_OP_addx),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("addc"),
                 JIT_OP_addc),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("sub"),
                 JIT_OP_sub),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("subx"),
                 JIT_OP_subx),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("subc"),
                 JIT_OP_subc),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("rsb"),
                 JIT_OP_rsb),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("mul"),
                 JIT_OP_mul),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("hmul"),
                 JIT_OP_hmul),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("div"),
                 JIT_OP_div),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("mod"),
                 JIT_OP_mod),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("and"),
                 JIT_OP_and),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("or"),
                 JIT_OP_or),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("xor"),
                 JIT_OP_xor),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("lsh"),
                 JIT_OP_lsh),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("rsh"),
                 JIT_OP_rsh),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("neg"),
                 JIT_OP_neg),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("not"),
                 JIT_OP_not),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("lt"),
                 JIT_OP_lt),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("le"),
                 JIT_OP_le),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("gt"),
                 JIT_OP_gt),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("ge"),
                 JIT_OP_ge),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("eq"),
                 JIT_OP_eq),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("ne"),
                 JIT_OP_ne),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("unlt"),
                 JIT_OP_unlt),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("unle"),
                 JIT_OP_unle),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("ungt"),
                 JIT_OP_ungt),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("unge"),
                 JIT_OP_unge),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("uneq"),
                 JIT_OP_uneq),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("ltgt"),
                 JIT_OP_ltgt),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("ord"),
                 JIT_OP_ord),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("unord"),
                 JIT_OP_unord),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("mov"),
                 JIT_OP_mov),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("ext"),
                 JIT_OP_ext),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("round"),
                 JIT_OP_round),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("trunc"),
                 JIT_OP_trunc),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("floor"),
                 JIT_OP_floor),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("ceil"),
                 JIT_OP_ceil),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("hton"),
                 JIT_OP_hton),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("ntoh"),
                 JIT_OP_ntoh),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("ld"),
                 JIT_OP_ld),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("ldx"),
                 JIT_OP_ldx),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("st"),
                 JIT_OP_st),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("stx"),
                 JIT_OP_stx),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("push"),
                 JIT_OP_push),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("pop"),
                 JIT_OP_pop),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("prepare"),
                 JIT_OP_prepare),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("pusharg"),
                 JIT_OP_pusharg),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("getarg"),
                 JIT_OP_getarg),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("blt"),
                 JIT_OP_blt),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("ble"),
                 JIT_OP_ble),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("bgt"),
                 JIT_OP_bgt),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("bge"),
                 JIT_OP_bge),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("beq"),
                 JIT_OP_beq),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("bne"),
                 JIT_OP_bne),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("bms"),
                 JIT_OP_bms),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("bmc"),
                 JIT_OP_bmc),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("boadd"),
                 JIT_OP_boadd),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("bosub"),
                 JIT_OP_bosub),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("call"),
                 JIT_OP_call),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("finish"),
                 JIT_OP_finish),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("jmp"),
                 JIT_OP_jmp),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("jmpi"),
                 JIT_OP_jmpi),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("prolog"),
                 JIT_OP_prolog),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("leaf"),
                 JIT_OP_leaf),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("ret"),
                 JIT_OP_ret),
               op_alist);
  op_alist = scheme_make_pair(
               scheme_make_pair(
                 scheme_intern_symbol("retval"),
                 JIT_OP_retval),
               op_alist);
  c_sym = scheme_intern_symbol("c");
  MZ_REGISTER_STATIC(c_sym);
  uc_sym = scheme_intern_symbol("uc");
  MZ_REGISTER_STATIC(uc_sym);
  s_sym = scheme_intern_symbol("s");
  MZ_REGISTER_STATIC(s_sym);
  us_sym = scheme_intern_symbol("us");
  MZ_REGISTER_STATIC(us_sym);
  i_sym = scheme_intern_symbol("i");
  MZ_REGISTER_STATIC(i_sym);
  ui_sym = scheme_intern_symbol("ui");
  MZ_REGISTER_STATIC(ui_sym);
  l_sym = scheme_intern_symbol("l");
  MZ_REGISTER_STATIC(l_sym);
  ul_sym = scheme_intern_symbol("ul");
  MZ_REGISTER_STATIC(ul_sym);
  p_sym = scheme_intern_symbol("p");
  MZ_REGISTER_STATIC(p_sym);
  f_sym = scheme_intern_symbol("f");
  MZ_REGISTER_STATIC(f_sym);
  d_sym = scheme_intern_symbol("d");
  MZ_REGISTER_STATIC(d_sym);
  r_sym = scheme_intern_symbol("r");
  MZ_REGISTER_STATIC(r_sym);
  v_sym = scheme_intern_symbol("v");
  MZ_REGISTER_STATIC(v_sym);
  fpr_sym = scheme_intern_symbol("fpr");
  MZ_REGISTER_STATIC(fpr_sym);
  r0_sym = scheme_intern_symbol("r0");
  MZ_REGISTER_STATIC(r0_sym);
  r1_sym = scheme_intern_symbol("r1");
  MZ_REGISTER_STATIC(r1_sym);
  r2_sym = scheme_intern_symbol("r2");
  MZ_REGISTER_STATIC(r2_sym);
  v0_sym = scheme_intern_symbol("v0");
  MZ_REGISTER_STATIC(v0_sym);
  v1_sym = scheme_intern_symbol("v1");
  MZ_REGISTER_STATIC(v1_sym);
  v2_sym = scheme_intern_symbol("v2");
  MZ_REGISTER_STATIC(v2_sym);
  fpr0_sym = scheme_intern_symbol("fpr0");
  MZ_REGISTER_STATIC(fpr0_sym);
  fpr1_sym = scheme_intern_symbol("fpr1");
  MZ_REGISTER_STATIC(fpr1_sym);
  fpr2_sym = scheme_intern_symbol("fpr2");
  MZ_REGISTER_STATIC(fpr2_sym);
  fpr3_sym = scheme_intern_symbol("fpr3");
  MZ_REGISTER_STATIC(fpr3_sym);
  fpr4_sym = scheme_intern_symbol("fpr4");
  MZ_REGISTER_STATIC(fpr4_sym);
  fpr5_sym = scheme_intern_symbol("fpr5");
  MZ_REGISTER_STATIC(fpr5_sym);
  sp_sym = scheme_intern_symbol("sp");
  MZ_REGISTER_STATIC(sp_sym);
  fp_sym = scheme_intern_symbol("fp");
  MZ_REGISTER_STATIC(fp_sym);
  ret_sym = scheme_intern_symbol("ret");
  MZ_REGISTER_STATIC(ret_sym);
  scheme_add_global("jit-proc",
    scheme_make_prim_w_arity(lightning_jit_proc, "jit-proc", 1, 1), menv);
  scheme_add_global("pifv",
    scheme_make_prim_w_arity(lightning_pifv, "pifv", 1, 1), menv);
  scheme_add_global("pifi",
    scheme_make_prim_w_arity(lightning_pifi, "pifi", 2, 2), menv);
  scheme_add_global("pifii",
    scheme_make_prim_w_arity(lightning_pifii, "pifii", 3, 3), menv);
  scheme_finish_primitive_module(menv);
  return scheme_void;
}

Scheme_Object *scheme_initialize(Scheme_Env *env)
{ return scheme_reload(env); }
Scheme_Object *scheme_module_name()
{ return scheme_intern_symbol("#%lightning"); }

/*****************************************************************************/
