#!/bin/sh

# This script helps manage the internal distribution process at Rice.
# Please ignore it.

RDIST=rdist

if [ "-r" = "$1" ] ; then
  shift
  RDIST=$1
  shift
fi

if [ "-self" = "$1" ] ; then
  shift
  FARHOST=`hostname`
elif [ "-local" = "$1" ] ; then
  shift
  FARHOST=localhost
else
  FARHOST=asia
fi

MRSYS=`/home/scheme/plt/bin/archsys -`$1

MRDEST=/home/scheme/plt/.bin/${MRSYS}/mred

echo ${MRBUILDDIR}mred to ${MRDEST}

strip ${MRBUILDDIR}mred

echo Installing MrEd
echo "${MRBUILDDIR}mred -> ${FARHOST} install $MRDEST ;" | $RDIST -f -
