(module info (lib "infotab.ss" "setup")
  (define name "Typeset")
  ;(define tools (list "tool.ss"))
  ;(define tool-icons (list '("typeset.xpm" "typeset")))
  ;(define tool-names (list "Typeset"))
)
