(module mzscheme-test mzscheme
  (provide (all-from-except mzscheme display newline)
           ;(rename read-local read)
           (rename display-local display)
           (rename newline-local newline)
           );(rename read-line-local read-line))
;  (define (read-local x)
;    (let ((i (read x)))
;      (write i)
;      (newline)
;      i))
;  (define (read-line-local x)
;    (let ((i (read-line x)))
;      (display i)
;      (newline)
;      i)))
  (define (newline-local o)
    (newline)
    (newline o))
    
  (define (display-local x o)
    (display x)
    (display x o)))